### ISSUE TITLE
Errors Integrating with project that does not use User Model

### ISSUE THREAD

**Issue by SteveKal** [waiting-for-dev/devise-jwt#1]
Hello, I recently wanted to try using the devise-jwt gem since it seems to be the only gem handling both overriding Devise's natural paths, and handling revoking JWTs after sign-out.

I am currently using the Employee model instead of the user model.

```ruby
include Devise::JWT::RevocationStrategies::JTIMatcher
devise :invitable, :database_authenticatable, :timeoutable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable,
         :jwt_authenticatable, jwt_revocation_strategy: self
```

I have defined the jti field in the employee table in the database and added null: false, index, and unique: true calls to the field as well.

I also added the configuration options to the devise initializer.

According to the documentation, these should be all of the steps required to make this gem function the way it is supposed to. However, at this time, this setup causes the basic helpers provided by devise itself to break and no longer function. I now have 600+ failing tests that all claim: 

V1::EmployeesController Recruiter Admin Capabilities should have a current employee
     Failure/Error: expect(subject.current_employee).to_not eq(nil)
     
     NoMethodError:
       undefined method `current_employee' for #<V1::EmployeesController:0x007fcb1d3feb08>
     # ./spec/controllers/v1/employees_controller_spec.rb:13:in `block (3 levels) in <top (required)>'

or:

V1::EmployeesController Recruiter Admin Capabilities GET #show Valid Employee JSON Request should respond with successful HTTP Code 200
     Failure/Error: get :show, id: @employee.id, format: :json
     
     NoMethodError:
       undefined method `authenticate_employee!' for #<V1::EmployeesController:0x007fcb1d4a1b28>
     # ./spec/controllers/v1/employees_controller_spec.rb:32:in `block (6 levels) in <top (required)>'

Note: I do have the devise controller helpers included in my spec_helper.rb and these tests were indeed passing up until setup of devise-jwt.

is there a step that I forgot? Or do I need to create these methods in the application controller to overwrite devise defaults? What is happening here?

**Comment by SteveKal** [comment]
Minor issue was that I accidentally set devise_for 'employees' in my routes.rb file. I have corrected, no longer gives undefined 'authenticate_employee', however it still gives me an undefined 'current_employee' method error and returns 401 on create and update functions. Is there perhaps a specific way that I would need to stub or call current_employee in order for it to return the employee?

**Comment by waiting-for-dev** [comment]
Hi @SteveKal .

`devise-jwt` does not override in any way devise controller helpers. In fact, it absolutely does nothing with devise controllers at all. So, I would be very surprised if your issue had something to do with this gem.

Maybe you coud inspect `Devise.mappings` in order to check whether your mappings have the name you suppose they have.

Please, feel free to reopen this issue if you end up with more information pointing to `devise-jwt` as responsible.

Thanks
