### ISSUE TITLE
Authorization header not sent on sign_in.json

### ISSUE THREAD

**Issue by qen** [waiting-for-dev/devise-jwt#10]
so i've setup the sessions controller to responds to json format request, but upon successfull login, the header `Authorization` is not set...

see screenshot
![screen shot 2017-04-28 at 8 48 33 pm](https://cloud.githubusercontent.com/assets/468237/25529351/40656a86-2c54-11e7-8f7f-1ee0b3dc4e23.png)

but if its a regular sign in, like it redirects upon successful authentication, its able to set the `Authoriztion` header
![screen shot 2017-04-28 at 8 50 42 pm](https://cloud.githubusercontent.com/assets/468237/25529421/80d7f70a-2c54-11e7-8e5d-8ea7319ef9b7.png)

**Comment by qen** [comment]
it's a misconfiguration on my end, the dispatch request needs to also be exactly `sign_in.json`

```
    jwt.dispatch_requests = [
      ['POST', %r{^/user/sign_in.json$}]
    ]
```

**Comment by BalGuldur** [comment]
thx. Trick with jwt.dispatch_requests help me.
`jwt.dispatch_requests = [
  ['POST', %r{^/users/sign_in.json$}]
]`

**Comment by waiting-for-dev** [comment]
This will be treated as duplicated of #13 See there for implemented fix
