### ISSUE TITLE
Remove Expiration tokens 

### ISSUE THREAD

**Issue by pdkproitf** [waiting-for-dev/devise-jwt#104]
Hi!
I'm doing some work with devise-jwt. I'm using Whitelist stratery. It's a great solution to let user login in multi devices.
But it seems to contain a problem: there is too much-expired token in the system. What should I do in this case?

Should I create a cron-job to destroy expired tokens?

**Comment by waiting-for-dev** [comment]
Hi @pdkproitf ,

as it depends a lot on the user stack, we don't provide any solution out of the box. If a cron-job works for you, go ahead with it.

At most, we could add from our side a `remove_expired_tokens` class method.

**Comment by pdkproitf** [comment]
yep, I just need the confirmation. I think it would be fine with a cronjob. 
Thank for your response.
