### ISSUE TITLE
A sample functioning app would be really helpful

### ISSUE THREAD

**Issue by 7seven7lst** [waiting-for-dev/devise-jwt#106]
Hi. This is not really an issue. But I feel like when I searched for some demo applications in google, those apps are either incomplete or misleading. Being a nodejs developer and Having used jwt for a long time I struggle big time with setting a minimum working app up with devise-jwt. If there's a full functioning demo app that would be great for others to pick it up and adapt this library more.

**Comment by waiting-for-dev** [comment]
Hi @7seven7lst .

You can look at the [fixture app](https://github.com/waiting-for-dev/devise-jwt/tree/master/spec/fixtures/rails_app) in the tests for a working simple demo.

**Comment by waiting-for-dev** [comment]
Also, you can look if some of the [dependants](https://github.com/waiting-for-dev/devise-jwt/network/dependents) help.

**Comment by waiting-for-dev** [comment]
Closing it, but feel free to add more comments if you need.
