### ISSUE TITLE
Set exp claim based on user type

### ISSUE THREAD

**Issue by stefanrendevski** [waiting-for-dev/devise-jwt#109]
Hello.
I assume the configuration option `jwt.exp` sets the exp claim on all issued tokens. Is it possible to override this behavior in different User classes? Say, for example, I have a RegularUser and AdminUser, and I want RegularUser tokens to expire within 5 hours, while AdminUser tokens expire within 10 hours. 

Could I do something like adding this information in `jwt_payload` by calling `super` and merge-ing a new exp claim?

**Comment by waiting-for-dev** [comment]
Hello @stefanrendevski ,

your assumption is correct. Right now there is no way to differentiate the expiration time depending on the user model. You are also right with the proposed workaround: you can add it in the `jwt_payload` method and your value will be respected.

**Comment by stefanrendevski** [comment]
Thank you for the quick response. I'm gonna close this issue, since my question was answered.
