### ISSUE TITLE
Cant install the gem in a fresh new Rails 5.1.0 project

### ISSUE THREAD

**Issue by jgonzalezd** [waiting-for-dev/devise-jwt#11]
I just created a new project in rails and when adding the gem I receive the following error:

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    devise-jwt (~> 0.1.1) was resolved to 0.1.1, which depends on
      devise (~> 4.0) was resolved to 4.0.0, which depends on
        railties (< 5.1, >= 4.1.0)

    rails (~> 5.1.0) was resolved to 5.1.0, which depends on
      railties (= 5.1.0)

```

**Comment by jonathanccalixto** [comment]
So, I had solved this problem by adding the design as follows:

gem 'devise', :git => 'https://github.com/plataformatec/devise.git' 
gem 'devise-jwt'

**Comment by jonathanccalixto** [comment]
@jgonzalezd

**Comment by jgonzalezd** [comment]
@jonathanccalixto  thanks a lot man, that made the trick

**Comment by jonathanccalixto** [comment]
thanks

**Comment by waiting-for-dev** [comment]
So this seems it is a [devise issue](https://github.com/plataformatec/devise/pull/4512). Going to close, then
