### ISSUE TITLE
Not returning Authorization header on custom devise signup route

### ISSUE THREAD

**Issue by fatalhck** [waiting-for-dev/devise-jwt#113]
## Expected behavior
Return Authorization token after signup
 ## Actual behavior
Don't return Authorization header on signup response
 ## Steps to Reproduce the Problem
 Extends the devise registration controller, `RegistrationsController < Devise::RegistrationsController`
 Edit routes to a new one in `devise for`
 Try to make a registration request, works fine but no token is returned
 ## Debugging information
 Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.
 
 * Version of `devise-jwt` in use 0.5.8
 * Version of `rails` in use 5.1.3
 * Output of `Devise::JWT.config` 
```
{:secret=>"32ca22caddb4d61ccf463cbc90c0cd634e83e251a87913bdd8a6b493bc191b4231145b81a132f5a27b77d18b77c18f2d1a8ede5a3e1c664995653744b61583bf",
   :expiration_time=>86400,
   :dispatch_requests=>nil,
   :revocation_requests=>nil,
   :aud_header=>nil,
   :request_formats=>{}}>
``` 
PS **already tried to add dispatch_requests**
 * Output of `Warden::JWTAuth.config`
  {:secret=>"32ca22caddb4d61ccf463cbc90c0cd634e83e251a87913bdd8a6b493bc191b4231145b81a132f5a27b77d18b77c18f2d1a8ede5a3e1c664995653744b61583bf",
   :expiration_time=>86400,
   :aud_header=>"JWT_AUD",
   :mappings=>{:user=>"User"},
   :dispatch_requests=>[["POST", /^\/login$/], ["POST", /^\/signup$/]],
   :revocation_requests=>[["DELETE", /^\/logout$/]],
   :revocation_strategies=>{:user=>"JwtBlacklist"}}>
 * Output of `Devise.mappings`
```
{:user=>
  #<Devise::Mapping:0x00007fae440e7730
   @class_name="User",
   @controllers={:sessions=>"sessions", :registrations=>"registrations", :passwords=>"devise/passwords"},
   @failure_app=Devise::FailureApp,
   @format=nil,
   @klass=#<Devise::Getter:0x00007fae440e6c90 @name="User">,
   @modules=[:database_authenticatable, :recoverable, :registerable, :jwt_authenticatable],
   @path="",
   @path_names={:registration=>"signup", :new=>"new", :edit=>"edit", :sign_in=>"login", :sign_out=>"logout", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel"},
   @path_prefix=nil,
   @router_name=nil,
   @routes=[:session, :password, :registration],
   @scoped_path="users",
   @sign_out_via=:delete,
   @singular=:user,
   @used_helpers=[:session, :password, :registration],
   @used_routes=[:session, :password, :registration]>}
```
 * If your issue is related with not getting a JWT from the server:
   
   * Involved request path, method and request headers
```
curl -X POST \
  http://127.0.0.1:3000/signup \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 2a378963-f6a9-ac3b-9982-07036429cc7c' \
  -d '{
	"user": {
		"password":"samplepwd",
        "email": "xpto@domain.com.br",
        "name": "XPTO"
      }
}'
```
   * Response headers for that request
```
Cache-Control:max-age=0, private, must-revalidate
Content-Type:application/json; charset=utf-8
ETag:W/"de32982ba6c3a71c5e1e3203ce2b720b"
Transfer-Encoding:chunked
Vary:Origin
X-Request-Id:b16e3f38-d02c-4957-b787-7686c519fd06
X-Runtime:346.581951
```

My cors configuration

```
Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    # TODO: come back here after and add the final DNSs
    origins '*'
    resource '*',
             headers: :any,
             methods: %i[get post put patch delete options head],
             expose: %w[Authorization]
  end
end
```
Could you check this?

**Comment by waiting-for-dev** [comment]
I take for granted that the sign up request is creating the user successfully.

You are overriding `RegistrationsController`. Could you paste your overriden `sign_up` action here?

Thanks

**Comment by fatalhck** [comment]
Thanks for the answer @waiting-for-dev ,

Yeah, the user was created successfully.

```
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  respond_to :json

  def create
    build_resource(sign_up_params)
    resource.save!
    render json: resource
  end

  def update_resource(resource, params)
    if params[:password].present?
      resource.password = params[:password]
      resource.password_confirmation = params[:password]
    end

    resource.update_without_password(params)
  end

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :phone, :role_id, :user_profile_id)
  end
end
```

**Comment by waiting-for-dev** [comment]
Ok, the problem is you are overriding too much, so much you are not using `devise` nor `warden` anymore, and `devise-jwt` has no way to hook into the later in order to create and dispatch the token. At least you should call the `sign_up` method present in the original `RegistrationsController`.

But the more important thing to keep in mind is to try to override the minimum or nothing at all. You can take a look at the [wiki in this repository](https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs) to get some ideas about how to do that.

**Comment by fatalhck** [comment]
I didn't get what is so customized, I have made a comparison with the original `sign_up` method and didn't find big differences in the behavior.

**Comment by waiting-for-dev** [comment]
The main difference in behavior for what is important to us, is that you are not authenticating the user in warden. You are just persisting it to the database. When you authenticate the user in warden, a series of hooks are fired. One of them is responsible of handcrafting a token and inserting it in the response headers. Check that devise original action is calling a `sign_up` method, which in turns calls a `sign_in` method, which in turns call the `set_user` method in warden proxy.

**Comment by fatalhck** [comment]
@waiting-for-dev thanks for the answer.

But I don't know if I'm looking into the wrong place, but my devise `sign_up` action code is the follow:

```
16: def create
    17:   build_resource(sign_up_params)
    18: 
    19:   resource.save
 => 20:   yield resource if block_given?
    21:   if resource.persisted?
    22:     if resource.active_for_authentication?
    23:       set_flash_message! :notice, :signed_up
    24:       sign_up(resource_name, resource)
    25:       respond_with resource, location: after_sign_up_path_for(resource)
    26:     else
    27:       set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
    28:       expire_data_after_sign_in!
    29:       respond_with resource, location: after_inactive_sign_up_path_for(resource)
    30:     end
    31:   else
    32:     clean_up_passwords resource
    33:     set_minimum_password_length
    34:     respond_with resource
    35:   end
    36: end
```

**Comment by waiting-for-dev** [comment]
? That's not was you pasted before. You pasted the following:

```ruby
  def create
    build_resource(sign_up_params)
    resource.save!
    render json: resource
  end
```

Which one are you using, then?

**Comment by waiting-for-dev** [comment]
Still an issue here?

**Comment by nicklayb** [comment]
I am having the same issue, I'm trying to make a route that authenticates using a token and returns a new token in the response headers. I only duplicated sign_in method and authenticated my user using token instead but no header are returned. I'm not sure exactly what nor where the token is being added to the headers.

```ruby
module V1
  class Users::SessionsController < Devise::SessionsController
    before_action :authenticate_user!, only: [:refresh]

    def create  # Has token on response
      self.resource = warden.authenticate!(auth_options)
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      yield resource if block_given?

      render json: resource.session_json
    end

    def refresh  # No token on response
      self.resource = warden.authenticate!(auth_options)
      sign_in(resource_name, current_user)
      render json: {status: 200}
    end
  end
end
```

As far as I looked, warden.authentiate! does nothing towards the token, it only fetches the user from credentials

**Comment by waiting-for-dev** [comment]
When warden authenticates, a series of hooks are fired. [One of them](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/hooks.rb) adds the token to the header. Maybe it will help you to debug. Also check carefully your configured dispatch requests.

**Comment by nicklayb** [comment]
I did not had any dispatch_requests at first, which may explained but It does not seem to be loaded at all. I have `/users/sign_in` and `/users/refresh`.

Here's how I set it up. 
```ruby
  config.jwt do |jwt|
    jwt.secret = ENV["DEVISE_JWT_SECRET_KEY"]
    jwt.dispatch_requests = [
        ["POST", %r{^/users/sign_in$}],
        ["POST", %r{^/users/refresh$}],
    ]
  end
```

`/users/sign_in` works as it was and `/users/refresh` does not work. The thing that is weird is that if I comment them both, I get the exact same behaviour...

I'm really sorry to annoy you but I don't get what I'm doing wrong

**Comment by nicklayb** [comment]
It was a mistake in my regular expression, but still it does not explain why `jwt.dispatch_requests = []` dispatches anyway on `/users/sign_in`... 

That's good for me thank you

**Comment by rands0n** [comment]
@nicklayb Which regular expression did you used? I'm having the same problem.

**Comment by nicklayb** [comment]
I used these (notice the missing ^ and $  versus the one I posted at [https://github.com/waiting-for-dev/devise-jwt/issues/113#issuecomment-439152651](https://github.com/waiting-for-dev/devise-jwt/issues/113#issuecomment-439152651)

```
jwt.dispatch_requests = [
        ["POST", %r{users/sign_in}],
        ["POST", %r{users/refresh}],
    ]
```

**Comment by Alagaesia93** [comment]
Hello @waiting-for-dev,

I'm trying to signup and signin a user, I don't get the token back. What am I missing? Thank you in advance

Rails: 5.2.3
Devise Jwt 0.5.9
Devise 4.6

Registrations_controller
```
def create
  super { @token = current_token }
end
[...]
private

  def respond_with(resource, _opts = {})
    render json: UserSerializer.new(resource, params: { token: @token })
  end

  def current_token
    request.env['warden-jwt_auth.token']
  end
```

In the response token is nil, because request.env['warden..'] is nil. 

What am I missing? 

Thank you in advance!

**Comment by waiting-for-dev** [comment]
Hey @Alagaesia93 . Please, open a new issue with all required debugging information. Thanks.

**Comment by Alagaesia93** [comment]
No need to open a new issue, I just solved.

I was doing a post request /users.json and not to /users, that's why the token was not set. IDK why, but thank you anyway!
