### ISSUE TITLE
Is there a way to revoke a token from a controller?

### ISSUE THREAD

**Issue by glapworth** [waiting-for-dev/devise-jwt#118]
Since devise-jwt doesn't yet support refreshing tokens, I've put together a very simple solution:

```
jwt.dispatch_requests = [
        ['POST', %r{^/auth/sign_in$}],
        ['GET', %r{^/auth/tokens/refresh$}],
    ]
```

I've created a controller action to compliment it:

```
class Auth::TokensController < ApplicationController
  before_action :authenticate_account!

  def refresh
    self.status        = 200
    self.content_type  = 'application/json'
    self.response_body = { data: [{ status: '200' }]}.to_json
  end
end
```

In my front end application, I watch for the expiry of the token, and when it's getting close, I call the endpoint `/auth/tokens/refresh` which generates me a new token.

I wonder if there is a way to kill the current token sent in the Authorization header when the user makes the request to `/auth/token/refresh'?  I

I've tried calling `Warden::JWTAuth::TokenRevoker.new.call(request.headers['Authorization'])` but that either stops execution during the refresh action, or it throws an exception : `JWT::DecodeError: Invalid segment encoding`.

Thanks for your help.

**Comment by waiting-for-dev** [comment]
Thanks for sharing your work. My view is that `devise-jwt` won't ever support refresh tokens, because there are better options for that, but anyway it can be helpful.

> I wonder if there is a way to kill the current token sent in the Authorization header when the user makes the request to `/auth/token/refresh'?

If I understand you well, you can add that request to [`revocation_requests`](https://github.com/waiting-for-dev/devise-jwt/#revocation_requests).

**Comment by glapworth** [comment]
I tried that but it didn’t seem to work. Could have been my configuration. I’ll have another go, but I suppose it depends on the order in which the requests are fulfilled. I’ll report back.

**Comment by glapworth** [comment]
BTW, what are the better options, in your opinion? I’m Just in the process of putting auth together for an API driven application with an ember front end and both iOS and android clients. I’m genuinely interested :)

**Comment by waiting-for-dev** [comment]
I'll copy here a related paragraph from the README:

> This gem is just a replacement for cookies when these can't be used. As cookies, a token expired with devise-jwt will mandatorily have an expiration time. If you need that your users never sign out, you will be better off with a solution using refresh tokens, like some implementation of OAuth2.

One option could be [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper), but I haven't used it.

**Comment by glapworth** [comment]
> If I understand you well, you can add that request to revocation_requests.

That worked. It must have been a typo previously.

```
 jwt.dispatch_requests = [
        ['POST', %r{^/auth/sign_in$}],
        ['GET', %r{^/auth/tokens/refresh$}],
    ]
 
jwt.revocation_requests = [
        ['DELETE', %r{^/auth/sign_out$}],
        ['GET', %r{^/auth/tokens/refresh$}],
    ]
```
In `devise.rb` with the following in my `tokens_controller.rb`

```
class Auth::TokensController < ApplicationController
  before_action :authenticate_account!

  def refresh
    self.status        = 200
    self.content_type  = 'application/json'
    self.response_body = { data: [{ status: '200' }]}.to_json
  end

end
```

Allows me to refresh tokens by calling the correct URI.

Thanks for your help.
