### ISSUE TITLE
sign_in_count increments on every request

### ISSUE THREAD

**Issue by Darkside73** [waiting-for-dev/devise-jwt#12]
Using ```trackable``` for devise. When client hits API protected by ```authenticate_user!```, ```sign_in_count``` increments even if user is signed in
Log:
```
Started GET "/v1/cities" for 127.0.0.1 at 2017-05-10 18:28:40 +0300
Processing by V1::CitiesController#index as JSON
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 5], ["LIMIT", 1]]
   (0.1ms)  BEGIN
  SQL (0.3ms)  UPDATE "users" SET "current_sign_in_at" = $1, "last_sign_in_at" = $2, "sign_in_count" = $3, "updated_at" = $4 WHERE "users"."id" = $5  [["current_sign_in_at", "2017-05-10 15:28:40.552873"], ["last_sign_in_at", "2017-05-10 15:28:27.810227"], ["sign_in_count", 127], ["updated_at", "2017-05-10 15:28:40.553390"], ["id", 5]]
   (2.2ms)  COMMIT
  City Load (0.2ms)  SELECT "cities".* FROM "cities"
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Attributes (0.05ms)
Completed 200 OK in 7ms (Views: 0.7ms | ActiveRecord: 2.9ms)

```
Not sure if it is a devise-jwt issue

**Comment by waiting-for-dev** [comment]
Probably not. This gem should not interfere with that. Feel free to reopen if you come with any clue pointing to this gem as guilty ;)

**Comment by phlegx** [comment]
I have the same problem. If I use `before_action :authenticate_user!, only: [:index]` all works fine and how it should, but if I look in the log there is an:

```
UPDATE "users" SET 
"current_sign_in_at" = $1, "last_sign_in_at" = $2, "sign_in_count" = $3, "updated_at" = $4 
WHERE "users"."id" = $5
```

**Comment by waiting-for-dev** [comment]
As you point out, it has to be fixed in plataformatec/devise#4584 . It belongs to the devise 5.0. roadmap.

Pull request #23 implements a workaround that can be used for now. That PR overwrites the warden strategy in use. Another option more secure would be to create a middleware adding `devise.skip_trackable` to `env` in any request not being the sign in one. That would not be too difficult to implement and maybe it could be shipped here until 5.0 is ready.

**Comment by Darkside73** [comment]
You can completely disable trackable or enable it only for certain API.
I came up with following initializer:
```ruby
Warden::Manager.after_set_user except: :fetch do |record, warden, options|
  root = Rails.application.config.relative_url_root || ''
  if warden.request.original_fullpath == "#{root}/v1/user" &&
     record.respond_to?(:update_tracked_fields!) &&
     warden.authenticated?(options[:scope]) &&
     !warden.request.env['devise.skip_trackable']
    record.update_tracked_fields!(warden.request)
  end
end
```

**Comment by phlegx** [comment]
Meanwhile I use a hook in `config/initializers/devise_jwt.rb` with the following code of the pull request #23. This works for me!

```
# https://github.com/waiting-for-dev/devise-jwt/pull/23
# https://github.com/plataformatec/devise/issues/4584

module Devise
  module JWT
    module WardenStrategy
      def authenticate!
        super
        env['devise.skip_trackable'.freeze] = true if self.valid?
      end
    end
  end
end

Warden::JWTAuth::Strategy.prepend Devise::JWT::WardenStrategy
```

**Comment by cesarjr** [comment]
The patch above worked for me. Does anyone know if it is still going to be solved in Devise?

**Comment by ackshaey** [comment]
Same, @phlegx thanks for posting it, just what I needed.
