### ISSUE TITLE
Having troubles integrating devise-jwt to Spree

### ISSUE THREAD

**Issue by efrenvalfonso** [waiting-for-dev/devise-jwt#120]
Hi there! I followed documentations steps to integrate this gem to Spree e-Commerce platform but is not working, I can't see Authorization Bearer Token in cookies. Some help with this? Best regards

**Comment by waiting-for-dev** [comment]
Please, fill the bug template with all the needed debug information.

**Comment by waiting-for-dev** [comment]
Closing for now but feel free to come back with the debug information.
