### ISSUE TITLE
Question: generate JWT after OmniAuth OAuth2 successfull authentication

### ISSUE THREAD

**Issue by netcitylife** [waiting-for-dev/devise-jwt#121]
Hi.

I need to generate JWT for a user, that successfully authenticated with Devise OmniAuth (OAuth2).
Successfull authentications are usually handled in omniauth_callbacks_controller.rb, my current code is:
```ruby
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def esia
      resource = User.from_omniauth(request.env['omniauth.auth'])

      sign_in(resource_name, resource)
      render json: { access_token: request.env['warden-jwt_auth.token'] }
    end
end
```

But access_token is always null in response. What should I do to generate it in this case?

**Comment by waiting-for-dev** [comment]
Does https://github.com/waiting-for-dev/devise-jwt/issues/3 help you?

**Comment by netcitylife** [comment]
Token is generated by that call, but revocation strategy is not taken into account (token is not inserted into whitelisted_jwts in my case), so it doen not work when authenticating with it... I may insert it manually, of course, but may be there is a more cleaner way which should execute all internals atomatically?

**Comment by waiting-for-dev** [comment]
If you need to revoke tokens at some requests add them to [revocation_requests](https://github.com/waiting-for-dev/devise-jwt#revocation_requests).

**Comment by netcitylife** [comment]
I found the correct way after watching through warden-jwt_auth source code. Token is dispached by a hook, which is called after warden.set_user(), which is called from Devise sign_in() method. And I already call this method in my code. So the only thing that stopped token from being automatically generated was "dispatch_requests" setting, and after adding my controller path there - everything started working, including revocation strategy :)

**Comment by waiting-for-dev** [comment]
Happy it works. I'll close it, then.

**Comment by netcitylife** [comment]
Thank you!

**Comment by khushwanth** [comment]
> I found the correct way after watching through warden-jwt_auth source code. Token is dispached by a hook, which is called after warden.set_user(), which is called from Devise sign_in() method. And I already call this method in my code. So the only thing that stopped token from being automatically generated was "dispatch_requests" setting, and after adding my controller path there - everything started working, including revocation strategy :)

can you please elaborate on this?

**Comment by Dainii** [comment]
I think she/he was talking about the `dispatch_requests` parameter (https://github.com/waiting-for-dev/devise-jwt#dispatch_requests). You have to list every additional requests that could request a token.
