### ISSUE TITLE
Details for using the aud header

### ISSUE THREAD

**Issue by subvertallchris** [waiting-for-dev/devise-jwt#128]
I see that 0.5.0 of this gem relies on 0.5.0 of warden-jwt_auth, which adds another layer of validation using the `JWT_AUD` header as described [here](https://github.com/waiting-for-dev/warden-jwt_auth#requesting-client-validation), pulled from the config [here](https://github.com/waiting-for-dev/warden-jwt_auth/blob/693f64d04dd1de8c697165ba0ebf7618d32168ec/lib/warden/jwt_auth/env_helper.rb#L55), and validated [here](https://github.com/waiting-for-dev/warden-jwt_auth/blob/693f64d04dd1de8c697165ba0ebf7618d32168ec/lib/warden/jwt_auth/strategy.rb#L20). Can you point me to documentation how we can set this value in this gem? I see how warden-jwt_auth gets the headers and compares it to the content of the token, I'm just not seeing where/how we should set this value when the token is generated. Is it entirely for use with the whitelist strategy?

Thanks for your help with this. I really like these gems and I appreciate the work you've put into them.

**Comment by waiting-for-dev** [comment]
You can [configure it](https://github.com/waiting-for-dev/devise-jwt#aud_header) as any other `devise-jwt` option. For example:

```ruby
Devise.setup do |config|
  config.jwt do |jwt|
    jwt.aud_header = "foo"
  end
end
```

It is independent from the revocation strategy in use. The `aud` claim will be set when the token is created, and it will be compared with the header value in every incoming request. This is a validation independent of the revocation strategy validation. If the `aud` claim does not match, the revocation strategy is not even called.

Is it clearer, now?

**Comment by subvertallchris** [comment]
Sure is! Thank you!
