### ISSUE TITLE
How to implement `current_user`?

### ISSUE THREAD

**Issue by dmoss18** [waiting-for-dev/devise-jwt#131]
I don't see a `current_user` helper anywhere in this repo, so I've just copied the implementation from the jwt auth gem. Is there an implementation already and I am just missing it? Here's what I have:

```
# in ApplicationController
def current_user
  return @user if @user
  token = Warden::JWTAuth::HeaderParser.from_env(request.headers.env)
  payload = Warden::JWTAuth::TokenDecoder.new.call(token)
  @user = Warden::JWTAuth::PayloadUserHelper.find_user(payload)
end
```

It just seems redundant to run this same code twice in a single request. Is there any better implementation that I am missing?

**Comment by waiting-for-dev** [comment]
This gem just adds another strategy to `devise`, but the user is set and can be retrieved in the same fashion. So `current_user` is available out of the box from the `devise` implementation (as long as your scope is named `user`, of course).

**Comment by andrezimpel** [comment]
Strange, got the same issue. Current_user is always nil. :/

**Comment by MutatedBread** [comment]
Did anyone got current_scope working? I am getting nil all the time despite there is an Authorization field with Bearer token in the header.
