### ISSUE TITLE
Authentication header not returned if using devise_for routes inside api/v1 module

### ISSUE THREAD

**Issue by likeuwill** [waiting-for-dev/devise-jwt#132]
Just for information if anyone stuck as me. You should use `devise_for :users` outside of api/v1 modules in routes.

Correct version:

```
  devise_for :users,
             defaults: { format: :json },
             class_name: 'Api::V1::User',
             controllers: {
               sessions: 'api/v1/sessions',
               registrations: 'api/v1/registrations'
             },
             path_prefix: '/api/v1'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users
```
jwt config:

```
  config.jwt do |jwt|
    jwt.secret = ENV['DEVISE_JWT_SECRET_KEY']
    jwt.request_formats = {
      user: [nil, :json],
    }
    jwt.dispatch_requests = [
      ['POST', %r{^/api/v1/users/sign_in$}],
      ['GET', %r{^/$}]
    ]
    jwt.revocation_requests = [
      ['DELETE', %r{^/api/v1/users/sign_out$}],
    ]
  end
```
Cors:
```
  allow do
    origins '*'
    resource '/api/v1/*',
             headers: %w(Authorization),
             methods: :any,
             expose: %w(Authorization)
  end
```
rails 5.2.3
devise-4.6.2
devise-jwt-0.5.9

**Comment by waiting-for-dev** [comment]
Thanks @likeuwill for the information. It can help others. I'll close it but if you or somebody is interested in digging into it just go ahead or open an issue with all required debugging information.

**Comment by farverio** [comment]
@likeuwill found this very helpful, thanks! Wish this was in the instructions...it's not really a question *shrugs*

**Comment by waiting-for-dev** [comment]
Well, I tagged it a question because, without debugging information, the closest I fount it to be is a self-answered question. As I said, please report an issue with all debugging information if you want it to be addressed.
