### ISSUE TITLE
Error: Revoked Token

### ISSUE THREAD

**Issue by rmammina** [waiting-for-dev/devise-jwt#135]
Running into an issue where I'm able to authenticate and get JWT token back, but when I send any request with `before_action  authenticate_user!` the token is automatically getting revoked. 

## Expected behavior
Status: 200
## Actual behavior
<img width="1380" alt="Screen Shot 2019-05-05 at 10 05 49 AM" src="https://user-images.githubusercontent.com/978280/57195945-89508100-6f1d-11e9-8419-21b5f69dd547.png">

Status:  401
`
{
    "error": "revoked token"
}
`

## Steps to Reproduce the Problem
`config.jwt do |jwt|
  jwt.secret = ENV["DEVISE_JWT_SECRET_KEY"]
  jwt.expiration_time = 48.hours.to_i

  jwt.dispatch_requests = [
    ['POST', %r{^/api/login$}],
    ['PUT', %r{^/api/users/invitations$}],
  ]
end`

## Debugging information

- Version of `devise-jwt` in use:  0.5.9
- Version of `rails` in use: 5.2.3
- Output of `Devise::JWT.config`
 ` => #<#<Class:0x007fc5642b5440>:0x007fc5642b51c0 @config={:secret=>"4bb363682d621b6fc6443b5d85061303bc276ef79771e5b73f93971713924656d2fb0a788b9b2ed1f8f71e8216c3dce9a5f63a23957444bd52ba4f0ac47a77d2", :expiration_time=>172800, :dispatch_requests=>[["POST", /^\/api\/login$/], ["PUT", /^\/api\/users\/invitations$/], ["POST", /^\/api\/users\/sign_in$/], ["POST", /^\/api\/users$/]], :revocation_requests=>nil, :aud_header=>nil, :request_formats=>{}}, @lock=#<Thread::Mutex:0x007fc5642b5170>, @defined=true>`

- Output of `Warden::JWTAuth.config`
 `=> #<#<Class:0x007fc563dc4120>:0x007fc563bd7e20 @config={:secret=>"4bb363682d621b6fc6443b5d85061303bc276ef79771e5b73f93971713924656d2fb0a788b9b2ed1f8f71e8216c3dce9a5f63a23957444bd52ba4f0ac47a77d2", :expiration_time=>172800, :aud_header=>"JWT_AUD", :mappings=>{:user=>"User"}, :dispatch_requests=>[["POST", /^\/api\/login$/], ["PUT", /^\/api\/users\/invitations$/], ["POST", /^\/api\/users\/sign_in$/], ["POST", /^\/api\/users$/]], :revocation_requests=>[["DELETE", /^\/api\/users\/sign_out$/]], :revocation_strategies=>{:user=>"User"}}, @lock=#<Thread::Mutex:0x007fc563bd7d58>, @defined=true>`

- Output of `Devise.mappings`
`=> {:user=>#<Devise::Mapping:0x007fc5689e6e18 @scoped_path="users", @singular=:user, @class_name="User", @klass=#<Devise::Getter:0x007fc5689e6a80 @name="User">, @path="users", @path_prefix="/api", @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:registrations=>"devise_invitable/registrations", :passwords=>"devise/passwords"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :password=>"password"}, @modules=[:database_authenticatable, :recoverable, :registerable, :validatable, :confirmable, :trackable, :jwt_authenticatable, :invitable], @routes=[:session, :password, :registration, :confirmation, :invitation], @used_routes=[:password], @used_helpers=[:session, :password, :registration, :confirmation, :invitation]>}`

**Comment by waiting-for-dev** [comment]
Which revocation strategy are you using?

**Comment by rmammina** [comment]
User revocation. So there's a JTI column on the user table

**Comment by waiting-for-dev** [comment]
Are you overriding `jwt_payload` in the user model? From the README:

```
Be aware that this strategy makes uses of jwt_payload method in the user model, so if you need to use it don't forget to call super:

def jwt_payload
  super.merge('foo' => 'bar')
end
```

**Comment by rmammina** [comment]
That fixed it, thanks!
