### ISSUE TITLE
Overriding destroy function

### ISSUE THREAD

**Issue by afzalsayed96** [waiting-for-dev/devise-jwt#136]
How do we override destroy method from Devise's `SessionsController` when using devise-jwt?
I'm using JWTBlacklist revocation strategy but after overriding revocation doesn't seem to work.
I'm defining the destroy function in `SessionsController` as follows:
```
def destroy
    if current_user
      sign_out(resource_name)
      # Do Something
      render status: :ok, json: {success: true}
    else
      render status: :unauthorized, json: {code: "E_UNAUTH"}
    end
  end
```
And I've defined routes as:
```
devise_scope :user do
    delete "/sessions/me", to: "sessions#destroy"
 end
```
Thanks

**Comment by afzalsayed96** [comment]
With normal devise authentication this technique works, refer: https://stackoverflow.com/questions/26241357/overriding-devise-sessionscontroller-destroy

**Comment by waiting-for-dev** [comment]
@afzalsayed96 I'm sorry, I was on holidays so I couldn't give support on this issue. Please, feel free to add more comments if you need some help.

**Comment by afzalsayed96** [comment]
For those who might want to do this - calling super after the custom logic
in destroy function solved my problem
