### ISSUE TITLE
support for http only cookie and csrf token.

### ISSUE THREAD

**Issue by navkumar2245** [waiting-for-dev/devise-jwt#137]
I think it is good idea for storing token in http only cookie.

**Comment by waiting-for-dev** [comment]
If the server has access to cookies then you don't need http header token authentication at all. Just go ahead with cookies.

**Comment by navkumar2245** [comment]
do I need to configure devise-jwt to accept cookie instead of authorisation header?

**Comment by waiting-for-dev** [comment]
I think I don't get your point. Could you elaborate what you are trying to do, please?

**Comment by navkumar2245** [comment]
I want to use a csrf token stored in http only cookie with the jwt token as non http only or local storage.

**Comment by waiting-for-dev** [comment]
You can store the token in the frontend as you like, in a cookie or in local storage. But you have to send it to the server in the http headers. If your server has access to the cookies, then you don't need devise-jwt at all and you can go with plain devise.

**Comment by waiting-for-dev** [comment]
@navkumar2245 I'm going to close it, but if you need more information please add more comments
