### ISSUE TITLE
Question: Sign up with ConfirmationsController

### ISSUE THREAD

**Issue by gioggi** [waiting-for-dev/devise-jwt#138]
`

    self.resource = resource_class.confirm_by_token(params[:confirmation_token])

    if resource.errors.empty?
      bypass_sign_in(self.resource)
      render json: "Bearer #{Warden::JWTAuth::UserEncoder.new.call(self.resource, :user, "JWT_AUD").first}"
    else
      render json: resource.errors, status: 403
    end

`
I need to confirm email, and it done correct but after don't authenticate user. I try to create a auth token  with Warden::JWTAuth::UserEncoder but nothing. I don't understand how authenticate user without sign_in.

Last version of devise-jwt

**Comment by waiting-for-dev** [comment]
Have you tried to add the route to `dispatch_requests` config option?

**Comment by gioggi** [comment]
i added
`jwt.dispatch_requests = [
      ['POST', %r{^/confirm-registration}],
      ['GET', %r{^/confirm-registration}],
    ]`

when i return the bearer token i save it in local storage browser and i add it local storage then i add it to `headers['Authorization']`  and i check with user_signed_in? method
correct?

**Comment by waiting-for-dev** [comment]
You use plain devise to tell which entry points must be authorized. This gem does not interfere with it.

**Comment by gioggi** [comment]
Thx i resolved with dispatch_requests!
`      ['POST', %r{/confirmation}],
      ['GET', %r{/confirmation}],`
