### ISSUE TITLE
No Authorization headers being returned

### ISSUE THREAD

**Issue by farverio** [waiting-for-dev/devise-jwt#140]
## Expected behavior
Warden to return JWT token in header

## Actual behavior
No token header is returned, but jti is accessible by returning user.jti in the body.

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

Version of `devise-jwt` in use: 
* devise-jwt (0.5.9)
* devise (~> 4.0)
* warden-jwt_auth (~> 0.3.6)
Version of `rails` in use
* rails (5.2.3)
Output of `Devise::JWT.config`
```
#<#<Class:0x0000557c306fdbd0>:0x0000557c306fd770 @config={:secret=>"{HIDDEN}", :expiration_time=>nil, :dispatch_requests=>[["POST", /^\/api\/v1\/users\/sign_in$/], ["GET", /^\/$/], ["POST", /^\/api\/v1\/users\/sign_in$/], ["POST", /^\/api\/v1\/users\/sign_in.json$/], ["POST", /^\/api\/v1\/users$/], ["POST", /^\/api\/v1\/users.json$/]], :revocation_requests=>[["DELETE", /^\/api\/v1\/users\/sign_out$/], ["DELETE", /^\/api\/v1\/users\/sign_out$/], ["DELETE", /^\/api\/v1\/users\/sign_out.json$/]], :aud_header=>nil, :request_formats=>{:user=>[nil, :json]}}, @lock=#<Thread::Mutex:0x0000557c306fd6d0>, @defined=true>
```
- Output of `Warden::JWTAuth.config`
```
#<#<Class:0x0000557c309100a8>:0x0000557c30903bf0 @config={:secret=>"{HIDDEN}", :expiration_time=>3600, :aud_header=>"JWT_AUD", :mappings=>{:user=>"User"}, :dispatch_requests=>[["POST", /^\/api\/v1\/users\/sign_in$/], ["GET", /^\/$/], ["POST", /^\/api\/v1\/users\/sign_in$/], ["POST", /^\/api\/v1\/users\/sign_in.json$/], ["POST", /^\/api\/v1\/users$/], ["POST", /^\/api\/v1\/users.json$/]], :revocation_requests=>[["DELETE", /^\/api\/v1\/users\/sign_out$/], ["DELETE", /^\/api\/v1\/users\/sign_out$/], ["DELETE", /^\/api\/v1\/users\/sign_out.json$/]], :revocation_strategies=>{:user=>"User"}}, @lock=#<Thread::Mutex:0x0000557c30903b28>, @defined=true>
```
- Output of `Devise.mappings`
```
{:user=>#<Devise::Mapping:0x0000557c313e9f60 @scoped_path="users", @singular=:user, @class_name="User", @klass=#<Devise::Getter:0x0000557c313e9c18 @name="User">, @path="users", @path_prefix="/api/v1", @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:sessions=>"api/v1/sessions", :registrations=>"api/v1/registrations", :passwords=>"devise/passwords", :confirmations=>"devise/confirmations", :invitations=>"devise/invitations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel", :confirmation=>"confirmation", :invitation=>"invitation", :accept=>"accept", :remove=>"remove"}, @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :confirmable, :trackable, :invitable, :jwt_authenticatable], @routes=[:session, :password, :registration, :confirmation, :invitation], @used_routes=[:session, :password, :registration, :confirmation, :invitation], @used_helpers=[:session, :password, :registration, :confirmation, :invitation]>}
```
Request Headers & Body:
* POST to localhost:3000/api/v1/users/sign_in
* Content-Type: application/JSON
* Authorization: Basic Og==
* Body:
```
{
	"user": {
		"email": EXISTING_EMAIL_IN_DB,
		"password": CORRECT_RAW_PASS_IN_DB
	}
}
```

Response Headers & Body:
* Content-Type →application/json; charset=utf-8
* ETag →W/"5842c8f60cd6807438b618035679b764"
* Cache-Control →max-age=0, private, must-revalidate
* X-Request-Id →3dcedaf5-527d-461a-ac89-f3843681a77a
* X-Runtime →3.073232
* Vary →Origin
* Transfer-Encoding →chunked
* Body:
```
{
    "email": EXISTING_EMAIL_IN_DB,
    "jti": ACTUAL_JTI
}
```

Sessions Controller
```
class Api::V1::SessionsController < Devise::SessionsController
    clear_respond_to

    def create
        @user = User.find_by(email: session_params[:email])

        if @user && @user.valid_password?(session_params[:password])
            # puts(current_user)
            render json: @user.as_json(only: [:email, :jti]), status: :created
        else
            render json: { message: 'Invalid email or password' }, status: :unauthorized
        end
    end

  private

    def session_params
        params.require(:user).permit(:email, :password)
    end
end
```

User Model
```
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable, :jwt_authenticatable, jwt_revocation_strategy: self
```

Routes
```
Rails.application.routes.draw do
  devise_for :users, defaults: {format: :json }, class_name: 'User', controllers: {
    sessions: 'api/v1/sessions',
    registrations: 'api/v1/registrations'
  },
  path_prefix: '/api/v1'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users
```

CORS
```
Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    # NOTE: Need to update this before deploying
    origins '*' 

    resource '*',
      headers: :any,
      methods: [:get, :post, :put, :patch, :delete, :options, :head],
      expose: %w(Authorization)
  end
end
```

Devise
```
  config.jwt do |jwt|
    jwt.secret = Settings.devise_jwt_secret

    jwt.request_formats = {
      user: [nil, :json],
    }

    jwt.dispatch_requests = [
      ['POST', %r{^/api/v1/users/sign_in$}],
      ['GET', %r{^/$}]
    ]
    
    jwt.revocation_requests = [
      ['DELETE', %r{^/api/v1/users/sign_out$}],
    ]
  end
```

Am I missing something or doing something incorrect with Devise? In other use cases, I've had to set the JWT in the headers manually but have stepped through the response code and it's going through Warden (so I presume hitting the hooks).

Any thoughts would mean a lot - been wracking my brain on this for a while now.

**Comment by waiting-for-dev** [comment]
Thanks for reporting @farverio 

You are overriding session's create action so much that you are not calling devise and warden HTTP layer, so devise-jwt has no way to operate.

At the very least you have to call `warden.authenticate!`, like [devise create action does](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/sessions_controller.rb#L19).  In this project wiki you have tips about [how to do the minimal override for a devise controller](https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs#overwriting-controllers).

**Comment by farverio** [comment]
Thanks for the reply. Making a bit more sense to me after getting some rest. It's even in the documentation in two places, but I didn't take much notice.

If possible, can we step back for a moment? I read your article saying why you built this compare compared to the three alternatives you found, but how does this differ from: simple_token_authentication?

My thought was that in using that gem, I'm not taking advantage of devise fields (like last ip, last login, login count, etc.), but that it at least helps because I'm building a Rails API. Would you say that's right or it's ok to use simple_token_authentication if it's just an api? Thoughts in general about using devise with apis?

Regarding the super, I understand I need to be using the Devise::SessionsController but have to overwrite since it's an API. Do you have any documentation on how I might overwrite in this case? I changed to the super logic but it's still getting a 401, so not sure if Devise can accept the request body format I posted above.

Glad to help reformat and offer suggestions on the gem readme based on my improved understanding and appreciate the continued help and support!

**Comment by waiting-for-dev** [comment]
> I read your article saying why you built this compare compared to the three alternatives you found, but how does this differ from: simple_token_authentication or devise_token_auth?

I can't tell exactly at this moment, because I have forgotten how that libraries work. But the reasons are those detailed in the article: I was looking for simplicity, zero monkey patching, ORM agnosticism,  revocation strategies, relying on JWT standard... In one way or another that libraries doesn't fulfill these needs.

> My thought was that in using that gem, I'm not taking advantage of devise fields (like last ip, last login, login count, etc.), but that it at least helps because I'm building a Rails API. Would you say that's right or it's ok to use one of the above two gems if it's just an api? Thoughts in general about using devise with apis?

You can use the gem you prefer. Those gems are also for devise in rest API applications, but I don't know the details. For me, everything comes down to the requirements I said before. `devise-jwt` is very simple, and I think it is very important for a security related library. You can use devise for apis, but it deserves some configuration as explained in the wiki.

> Regarding the super, I understand I need to be using the Devise::SessionsController but have to overwrite since it's an API. Do you have any documentation on how I might overwrite in this case? I changed to the super logic but it's still getting a 401, so not sure if Devise can accept the request body format I posted above.

You can perfectly respond with json. It is also in the wiki: https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs#responding-to-json

**Comment by waiting-for-dev** [comment]
> I read your article saying why you built this compare compared to the three alternatives you found, but how does this differ from: simple_token_authentication or devise_token_auth?

I can't tell exactly at this moment, because I have forgotten how that libraries work. But the reasons are those detailed in the article: I was looking for simplicity, zero monkey patching, ORM agnosticism,  revocation strategies, relying on JWT standard... In one way or another that libraries doesn't fulfill these needs.

> My thought was that in using that gem, I'm not taking advantage of devise fields (like last ip, last login, login count, etc.), but that it at least helps because I'm building a Rails API. Would you say that's right or it's ok to use one of the above two gems if it's just an api? Thoughts in general about using devise with apis?

You can use the gem you prefer. Those gems are also for devise in rest API applications, but I don't know the details. For me, everything comes down to the requirements I said before. `devise-jwt` is very simple, and I think it is very important for a security related library. You can use devise for apis, but it deserves some configuration as explained in the wiki.

> Regarding the super, I understand I need to be using the Devise::SessionsController but have to overwrite since it's an API. Do you have any documentation on how I might overwrite in this case? I changed to the super logic but it's still getting a 401, so not sure if Devise can accept the request body format I posted above.

You can perfectly respond with json. It is also in the wiki: https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs#responding-to-json

**Comment by waiting-for-dev** [comment]
I guess this can be closed, but feel free to add more comments if needed.

**Comment by hariharan888** [comment]
@waiting-for-dev Today I could reproduce the error and I was able to narrow it down to the place which causes the bug
```
    def create
        @user = User.find_by(email: session_params[:email])

        if @user && @user.valid_password?(session_params[:password])
            # puts(current_user)
            render json: @user.as_json(only: [:email, :jti]), status: :created
        else
            render json: { message: 'Invalid email or password' }, status: :unauthorized
        end
    end
```
Just commenting this `create` method in `sessions_controller.rb` resolves the bug. When we try to override the default `create` method of `devise`, the authentication header is not attached.

Can we do something about this?

**Comment by waiting-for-dev** [comment]
During devise dfault sign in process, it ends up [calling warden](https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/sign_in_out.rb#L53) in order to authenticate the user. Overriding the controller as you do, you are not using devise controller layer anymore, so neither warden http layer, which is the responsible of calling some hooks that will eventually set the JWT token in the response headers.

You must do the [minimal controller override](https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs#overwriting-controllers).

**Comment by hariharan888** [comment]
@waiting-for-dev yes you are right. Looking at older issues and found #76. 
That solution worked for me. 

It would be helpful if this info is available in the documentation.
