### ISSUE TITLE
Generating or capturing a token through manual devise sign_in method

### ISSUE THREAD

**Issue by balindenberg** [waiting-for-dev/devise-jwt#142]
Hello! 

First of all, thank you for this library - it's greatly appreciated. I'm sorry to open an issue but have been banging my head on this for 2 days now. I'm sure it's something simple that I'm doing wrong and hope I can close this shortly. 

I'm trying to manually create + sign in a user in the backend and return the authorization token to the front end, in this general flow:

1. User gets a social auth code on the frontend
2. POST that code to a backend controller, assemble user object based on that
3. Create + save user object with that information
4. Sign in the new user and return the authorization token to the front end

## Expected behavior

Calling `sign_in` on the user object should trigger a JWT dispatch request and create a new token for the user

## Actual behavior
No token is surfaced for the new user (at least that I can find)

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- Version of `devise-jwt` in use: **0.5.9**
- Version of `rails` in use **5.2.3**

- **Output of `Devise::JWT.config`**
`{
                 :secret => "redacted",
        :expiration_time => nil,
      :dispatch_requests => [
        [0] [
            [0] "POST",
            [1] /^\/api\/users\/sign_in$/
        ],
        [1] [
            [0] "POST",
            [1] /^\/api\/users\/signup\/fb*/
        ],
        [2] [
            [0] "POST",
            [1] /^\/api\/users\/sign_in.json$/
        ],
        [3] [
            [0] "POST",
            [1] /^\/api\/users.json$/
        ]
    ],
    :revocation_requests => nil,
             :aud_header => nil,
        :request_formats => {
        :user => [
            [0] :json
        ]
    }
}`
- **Output of `Warden::JWTAuth.config`**
`{
                   :secret => "redacted",
          :expiration_time => 3600,
               :aud_header => "JWT_AUD",
                 :mappings => {
        :user => "User"
    },
        :dispatch_requests => [
        [0] [
            [0] "POST",
            [1] /^\/api\/users\/sign_in$/
        ],
        [1] [
            [0] "POST",
            [1] /^\/api\/users\/signup\/fb*/
        ],
        [2] [
            [0] "POST",
            [1] /^\/api\/users\/sign_in.json$/
        ],
        [3] [
            [0] "POST",
            [1] /^\/api\/users.json$/
        ]
    ],
      :revocation_requests => [
        [0] [
            [0] "DELETE",
            [1] /^\/api\/users\/sign_out.json$/
        ]
    ],
    :revocation_strategies => {
        :user => "JwtBlacklist"
    }
}`

- **Output of `Devise.mappings`**
`:user => #<Devise::Mapping:0x00007f924279c760 @scoped_path="users", @singular=:user, @class_name="User", @klass=#<Devise::Getter:0x00007f924279c3c8 @name="User">, @path="users", @path_prefix="/api", @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:sessions=>"sessions", :passwords=>"devise/passwords", :registrations=>"devise/registrations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel"}, @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :jwt_authenticatable], @routes=[:session, :password, :registration], @used_routes=[:session, :password, :registration], @used_helpers=[:session, :password, :registration]>`

Any advice or pointers would be greatly appreciated. I can also supply any additional information needed.

**Comment by waiting-for-dev** [comment]
Hi @balindenberg ,

if you want to generate a token manually you can rely on `warden-jwt_auth`. Please, see #3

**Comment by balindenberg** [comment]
Thanks for the quick response @waiting-for-dev.  

I'm able to generate a token using Warden but am having trouble associating it back to the user when making a call from the front end. How do I check which user a token belongs to? 

I followed this [tutorial](https://medium.com/@fishpercolator/how-to-separate-frontend-backend-with-rails-api-nuxt-js-and-devise-jwt-cf7dd9da9d16) that calls sessions#show and returns the current user based on the token, but it's always blank for my generated tokens. 


Closing as this is debugging my use case rather than the library, but would appreciate a pointer if you have one :)

**Comment by waiting-for-dev** [comment]
> How do I check which user a token belongs to?

Take a loot at [`UserDecoder`](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/user_decoder.rb). With it you get the user back from the token. You need to provide the token, the warden scope (for exampe `:user` for a `User` model) and `aud` (which needs to be `nil` if you haven't configured any).

Feel free to ask any question. I also mantain GH issues for questions related specifically to this gem.

**Comment by balindenberg** [comment]
That worked and I'm off to the races. Thank you greatly for the help!
