### ISSUE TITLE
RS256 Support?

### ISSUE THREAD

**Issue by verenion** [waiting-for-dev/devise-jwt#143]
There is another issue for this here #80. It was closed and marked as wontfix. We are not using devise-jwt to generate our access token - we are using doorkeeper. Multiple services will be consuming these access tokens, therefore, asymmetric keys are important. Is there a way to get this working, or are we doing something wrong with generating our tokens?

**Comment by waiting-for-dev** [comment]
But then, what are you using `devise-jwt` for?

**Comment by verenion** [comment]
Because I assumed it would save having to do it manually, it seems all I really needed was a simple before_action to check if the key is valid
