### ISSUE TITLE
Getting nil user error for sign in after sign out in specs (RSpec).

### ISSUE THREAD

**Issue by chase1745** [waiting-for-dev/devise-jwt#144]
I have been working on this problem, and can't seem to find the issue. The issue is that `/login` returns a `401` status with: `{"error":"nil user"}` if run after `/logout`, it only happens in my RSpec acceptance specs, and only when the `/logout` spec is run before `/login`. If `/login` is run first, a `200` status is received correctly. Hitting these requests manually returns the correct `200` as well.

##  Expected behavior
Sign in should get 200 response, even after sign out.
## Actual behavior
Sign in gets 401 response with `{"error":"nil user"}`, only if test ran after sign out test.
## Steps to Reproduce the Problem
Using JTIMatcher revocation strategy.
Sending the following headers: `Content-Type: application/json, Accept: application/json`.
path: `DELETE /logout`
Pertinent tests:
```
resource 'Authentication' do
  let!(:user) {create(:user)}

  post '/login' do
    with_options scope: :user, with_example: true do
      parameter :email, 'Email', required: true
      parameter :password, 'Password', required: true
    end

    context '200' do
      let(:email) { user.email }
      let(:password) { user.password }

      example_request 'Successful Login' do
        expect(status).to eq(200)
        expect(response_body['jti']).to be_present
        expect(response_headers['Authorization']).to be_present
        decoded_token = JwtSpecHelper.decode(response_headers)
        expect(decoded_token.first['jti']).to be_present
      end
    end

  delete '/logout' do
    let(:auth_headers) { JwtSpecHelper.get_auth_headers(user) }

    context '204' do
      example 'Successful Logout' do
        header 'Authorization', auth_headers['Authorization']
        do_request
        expect(status).to eq(204)
      end
    end
  end
end
```
User Model: 
```
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher

  devise :database_authenticatable, :jwt_authenticatable,
         :registerable, :validatable,
         jwt_revocation_strategy: self # https://github.com/waiting-for-dev/devise-jwt#jtimatcher
end
```

Overridden SessionsController:
```
class SessionsController < Devise::SessionsController
  respond_to :json

  private

  def respond_with(resource, _opts = {})
    render json: resource
  end

  def respond_to_on_destroy
    head :no_content
  end
end
```

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- Version of `devise-jwt` in use
`0.5.8`
- Version of `rails` in use
`5.2.2`
- Output of `Devise::JWT.config`
```
{:secret=><MY_SECRET_KEY>, :expiration_time=>5184000, :dispatch_requests=>nil, :revocation_requests=>nil, :aud_header=>nil, :request_formats=>{}}
```
- Output of `Warden::JWTAuth.config`
```
{:secret=<MY_SECRET_KEY>, :expiration_time=>5184000, :aud_header=>"JWT_AUD", :mappings=>{:user=>"User"}, :dispatch_requests=>[["POST", /^\/login$/], ["POST", /^\/$/]], :revocation_requests=>[["DELETE", /^\/logout$/]], :revocation_strategies=>{:user=>"User"}},
```
- Output of `Devise.mappings`
```
{:user=>#<Devise::Mapping:0x00007fb03b30b6d0 @scoped_path="users", @singular=:user, @class_name="User", @klass=#<Devise::Getter:0x00007fb03b30b338 @name="User">, @path="", @path_prefix=nil, @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:sessions=>"sessions"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"login", :sign_out=>"logout"}, @modules=[:database_authenticatable, :registerable, :validatable, :jwt_authenticatable], @routes=[:session, :registration], @used_routes=[:session], @used_helpers=[:session, :registration]>}
```

**Comment by waiting-for-dev** [comment]
It looks like an error in your test suite configuration. `devise-jwt` is working as expected when you hit `login`. When you hit `logout` the only thing that `devise-jwt` will do (unless something has been overridden) is update the `jti` column in your user model.

It seems that when you `logout` your user is being deleted, so at next request it can't be found. Your tests should be idempotent.

-

**Comment by waiting-for-dev** [comment]
Closing it, feel free to add more comments if needed.
