### ISSUE TITLE
Logout not revoking the JTI column value.

### ISSUE THREAD

**Issue by aruprakshit** [waiting-for-dev/devise-jwt#145]
## Expected behavior
After Logout the jit should be revoked
## Actual behavior
After logout the jit still same as before.

## Steps to Reproduce the Problem

```sh
~$ curl -v -X POST http://localhost:5000/api/v1/auth/login -H 'Content-Type: application/json' -d '{
    "email": "api_user_02@example.com",
    "password": "password"
}
'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5000 (#0)
> POST /api/v1/auth/login HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 71
> 
* upload completely sent off: 71 out of 71 bytes
< HTTP/1.1 201 Created
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Referrer-Policy: strict-origin-when-cross-origin
< Location: /
< Content-Type: application/json; charset=utf-8
< ETag: W/"cff09680bf129a4767291b642c21bd63"
< Cache-Control: max-age=0, private, must-revalidate
< Set-Cookie: _timelord_session=YzF5Vm1MNGY3bHhqdGRaZzRFazRjMXJWUW5pZW02bTRpNm9zQ1lDcmxZMlVsQ1YrK0ZHalBxLy83OUxPV08vSzgzcnBUaWxwVFR6bUw4czJ3Ry9XaDVTTFBRN3NXRTkwQTdLc2dYOEFzUWN4T1YyOFlsTTdQdHJ2Y3dDUVRIOU1raUQwOENQSHlJTGZCUDlYOHVic3R3PT0tLXQ1Q1MydlovVDNjVXdwS2g4dkdnNXc9PQ%3D%3D--a050554366b8e8adf7b0c53c901f136de77fbd73; path=/; HttpOnly
< X-Request-Id: 9af3f5dc-8663-4b1a-a457-e4c391836b71
< X-Runtime: 0.231814
< Vary: Origin
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{"id":9,"email":"api_user_02@example.com","created_at":"2019-07-21T09:55:18.275Z","updated_at":"2019-07-21T12:09:25.758Z","first_name":null,"last_name":null,"street_address1":null,"street_address2":null,"city":null,"state":null,"country":null,"username":"api_user_02","company_name":null,"zip_code":null,"jti":"642fba98-2f18-4471-a05b-6d327906a3bc"}~$ 
~$  curl -v  -X DELETE http://localhost:5000/api/v1/auth/logout.json -H 'Authorization: Bearer 642fba98-2f18-4471-a05b-6d327906a3bc'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5000 (#0)
> DELETE /api/v1/auth/logout.json HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Bearer 642fba98-2f18-4471-a05b-6d327906a3bc
> 
< HTTP/1.1 204 No Content
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Referrer-Policy: strict-origin-when-cross-origin
< Cache-Control: no-cache
< Set-Cookie: _timelord_session=UUVGWE5PdlNSdGl6dFJQZzlJRkZ2RWVhbGhteFhtc1FLMDRGQnpVZ3RxMjVuR2lBUFJNcFJ6MCtxZzh4UGFOVjN4cU1OVlhRR3czcjZHZ0VkZklUdUE9PS0tK210NGRnRVUyKzRXb1lDR0h6UWxTUT09--f72f8140e045763d100dfe8c72294f18ec2ea142; path=/; HttpOnly
< X-Request-Id: 56dbdebb-24cf-4bdc-aaa0-c6622a901d0e
< X-Runtime: 0.004869
< Vary: Origin
< 
* Connection #0 to host localhost left intact
~$ curl -v -X POST http://localhost:5000/api/v1/auth/login -H 'Content-Type: application/json' -d '{
    "email": "api_user_02@example.com",
    "password": "password"
}
'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5000 (#0)
> POST /api/v1/auth/login HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 71
> 
* upload completely sent off: 71 out of 71 bytes
< HTTP/1.1 201 Created
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Referrer-Policy: strict-origin-when-cross-origin
< Location: /
< Content-Type: application/json; charset=utf-8
< ETag: W/"96503730c1bf2583e291dec8c444c812"
< Cache-Control: max-age=0, private, must-revalidate
< Set-Cookie: _timelord_session=WWNSeVdjZTF1cVprZjF1bHczT0hkZ2s1M0VXVEJwNytyZm1zUlFRWlJpTVRyclNpcklCK1Ywb2lGQjlsaytjSHpMQi8vdzcrNHBRcXZkdTRzNFNSYU5zbk5nUlE0YVpvUnQ5aURoR1paZVhKU2lqV1hISGFDaStRV0lhY0RBenUybGhiQUU0ZDAyalFRQy9xbndSeWZRPT0tLThNUUNOd1gvcG1zeS8zc011TU1KbXc9PQ%3D%3D--74f737ff2ec2ebfc754c66d78aa6fb8f41c1f0f2; path=/; HttpOnly
< X-Request-Id: 3d40ec2b-2896-4861-a230-9f653e8e6898
< X-Runtime: 0.130320
< Vary: Origin
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{"id":9,"email":"api_user_02@example.com","created_at":"2019-07-21T09:55:18.275Z","updated_at":"2019-07-21T12:09:36.965Z","first_name":null,"last_name":null,"street_address1":null,"street_address2":null,"city":null,"state":null,"country":null,"username":"api_user_02","company_name":null,"zip_code":null,"jti":"642fba98-2f18-4471-a05b-6d327906a3bc"}~$ 
```

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- Version of `devise-jwt` in use devise-jwt (0.5.9)
- Version of `rails` in use rails (5.2.1)

- Output of `Devise::JWT.config`
```sh
#<#<Class:0x00007f8db6289e48>:0x00007f8db6289a60 @config={:secret=>nil, :expiration_time=>nil, :dispatch_requests=>[["POST", /^\/api\/v1\/users\/login$/], ["POST", /^\/users\/sign_in$/], ["POST", /^\/users$/]], :revocation_requests=>[["DELETE", /^\/api\/v1\/auth\/logout$/], ["DELETE", /^\/users\/sign_out$/]], :aud_header=>nil, :request_formats=>{}}, @lock=#<Thread::Mutex:0x00007f8db6289a10>, @defined=true> 
```
- Output of `Warden::JWTAuth.config`
```sh
#<#<Class:0x00007f8db6229ae8>:0x00007f8db6229520 @config={:secret=>nil, :expiration_time=>3600, :aud_header=>"JWT_AUD", :mappings=>{:user=>"User"}, :dispatch_requests=>[["POST", /^\/api\/v1\/users\/login$/], ["POST", /^\/users\/sign_in$/], ["POST", /^\/users$/]], :revocation_requests=>[["DELETE", /^\/api\/v1\/auth\/logout$/], ["DELETE", /^\/users\/sign_out$/]], :revocation_strategies=>{:user=>"User"}}, @lock=#<Thread::Mutex:0x00007f8db6229458>, @defined=true>
```
- Output of `Devise.mappings`
```
{:admin_user=>#<Devise::Mapping:0x00007f8db442c1d0 @scoped_path="admin_users", @singular=:admin_user, @class_name="AdminUser", @klass=#<Devise::Getter:0x00007f8db4433c28 @name="AdminUser">, @path="admin", @path_prefix=nil, @sign_out_via=[:delete, :get], @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:sessions=>"active_admin/devise/sessions", :passwords=>"active_admin/devise/passwords", :unlocks=>"active_admin/devise/unlocks", :registrations=>"active_admin/devise/registrations", :confirmations=>"active_admin/devise/confirmations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"login", :sign_out=>"logout", :password=>"password"}, @modules=[:database_authenticatable, :rememberable, :recoverable, :validatable], @routes=[:session, :password], @used_routes=[:session, :password], @used_helpers=[:session, :password]>, :user=>#<Devise::Mapping:0x00007f8dbb82a938 @scoped_path="users", @singular=:user, @class_name="User", @klass=#<Devise::Getter:0x00007f8dbb82a5a0 @name="User">, @path="users", @path_prefix=nil, @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:sessions=>"users/sessions", :registrations=>"users/registrations", :passwords=>"devise/passwords"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel"}, @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :trackable, :jwt_authenticatable], @routes=[:session, :password, :registration], @used_routes=[:session, :password, :registration], @used_helpers=[:session, :password, :registration]>} 
```

I am writing APIs alongside a full blown Rails MVC web app. My routes for just the API part looks like:

```ruby
namespace :api, defaults: { format: :json } do
    namespace :v1 do
      as :user do
        post   'auth/register', to: 'users/registrations#create'
        post   'auth/login',    to: 'users/sessions#create'
        delete 'auth/logout',   to: 'users/sessions#destroy'
      end
    end
  end
```

My sessions controller looks like:

```ruby
# frozen_string_literal: true

module Api
  module V1
    module Users
      class SessionsController < Devise::SessionsController
        wrap_parameters :user

        respond_to :json

        skip_before_action :verify_signed_out_user, only: :destroy

        # POST /resource/sign_in
        # def create
        #   super
        # end

        # DELETE /resource/sign_out
        # def destroy
        #   super
        # end

        protected

        # If you have extra params to permit, append them to the sanitizer.
        # def configure_sign_in_params
        #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
        # end
      end
    end
  end
end
```

The cors looks like:

```ruby
Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    origins '*'

    resource '/api/*',
             headers: %w[Authorization],
             methods: :any,
             expose: %w[Authorization],
             max_age: 600
  end
end
```

My user model is:

```ruby
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: self
end
```

And devise.rb has following:

```ruby
config.jwt do |jwt|
    jwt.secret = ENV['DEVISE_JWT_SECRET_KEY']
    jwt.revocation_requests = [
      ['DELETE', %r{^/api/v1/auth/logout$}]
    ]
    jwt.dispatch_requests = [
      ['POST', %r{^/api/v1/users/login$}]
    ]
end
```

My problem is when I do a logout request, I don't see that `jit` column value is revoked/replaced with a new one. Also I never see the `Authorization` header in the response. You can what I am saying here in the above `curl` request too.

Please let me know if I am missing any details here to provide.

**Comment by aruprakshit** [comment]
I had some configuration wrong. Now it works, but I have a different issue regarding this https://github.com/waiting-for-dev/devise-jwt#session-storage-caveat . I may open new issue for that. I am closing it now.

**Comment by brentkearney** [comment]
I would love to know what you changed to make it work. I am having the same issue.

If I knew how to get the username from the auth token, I could override SessionsController#destroy to change the User.jti myself.

**Comment by aruprakshit** [comment]
@brentkearney What is the url looks like for log out?

**Comment by brentkearney** [comment]
Logout path for JSON requests is: `/api/logout.json`.

I found how to decode the JTI token. It seems like a hack, but logouts are working now:

```
def destroy
    super if params['Authorization'].blank?
    user = ApiUser.find_by_jti(decode_token)
    super if user.blank?
    revoke_token(user)
    sign_out(user)
    render status: 200, json: { message: "Signed out." }
  end

  private

 def decode_token
    token = params['Authorization'].split('Bearer ').last
    secret = ENV['DEVISE_JWT_SECRET_KEY']
    JWT.decode(token, secret, true, algorithm: 'HS256',
      verify_jti: true)[0]['jti']
  end
```

However, I seem to have broken `:authorize_user!` for html requests, in the process.

**Comment by aruprakshit** [comment]
When you have custom url like you have above, you probably need to use 

```
jwt.revocation_requests = [
      ['DELETE', %r{^/api/logout$}]
    ]
```

also request_formats, check the doc. I didn't do any overriding to the devise code. This gem has lot of moving parts. :)

**Comment by brentkearney** [comment]
My jwt config is:

```
config.jwt do |jwt|
    jwt.secret = ENV['DEVISE_JWT_SECRET_KEY']
    jwt.dispatch_requests = [ ['POST', %r{^/api/login$}], ['POST', %r{^/api/login.json$}] ]
    jwt.revocation_requests = [ ['DELETE', %r{^/api/logout$}], ['DELETE', %r{^/api/logout.json$}] ]
    jwt.expiration_time = 1.day.to_i
    jwt.request_formats = { user: [:html], api_user: [nil, :json] }
end
```

If I remove my custom `destroy` method, then I get a redirect to the sign-in page, as if I were logged out. However, the ApiUser.jti field is unchanged, so I can still send requests with the token in the header, and gain access protected resources. It is not _actually_ logged out until the User.jti field gets updated, so I need to keep my override in place.

My new issue is with HTML logins. Authentication at the sign-in works, but then `:authorize_user!` fails and produces a `401 Unauthorized`, redirecting user to sign-in. Oddly, I have discovered that if I change the user password, then I get logged in and everything works. As soon as I log out that user, :authorize_user! goes back to failing.

**Comment by brentkearney** [comment]
I found the issue. In `config/initializers/devise.rb`, devise-jwt works properly (except for logouts) if  have:
```
  config.skip_session_storage = [:http_auth, :params_auth]
```

However, that breaks html logins by non-api (json) users. If I remove `:params_auth`, then html logins work, and so does json functionality. Although, I found some problems with my override and changed it to:

```
  def destroy
    super and return if params['Authorization'].blank?
    user = ApiUser.find_by_jti(decode_token)
    super and return if user.blank?
    revoke_token(user)
    super
  end
```

**Comment by aruprakshit** [comment]
> I found the issue. In `config/initializers/devise.rb`, devise-jwt works properly (except for logouts) if have:
> 
> ```
>   config.skip_session_storage = [:http_auth, :params_auth]
> ```

Yes this is a problem, I am not sure how to fix this. But if the request comes from native mobile, then you don't need to add `params_auth`. But I am not sure how to handle this part best yet.

When you have `api_user: [nil, :json]`, then why mentioning `['DELETE', %r{^/api/logout$}]` in the `jwt.revocation_requests`?  same question goes for `jwt.dispatch_requests` requests.

**Comment by brentkearney** [comment]
> When you have api_user: [nil, :json], then why mentioning ['DELETE', %r{^/api/logout$}] in the jwt.revocation_requests? same question goes for jwt.dispatch_requests requests.

`jwt.request_formats` specifies the type of request, html, json, or unspecified (nil). The revocation and dispatch settings specify the routes for logout and login, respectively.

**Comment by aruprakshit** [comment]
So it means `/api/logout` and `/api/logout.json` in both cases you want to do revocation?  then why again need to mention `api_user: [nil, :json]`? I am confused @brentkearney

**Comment by brentkearney** [comment]
This:
```
    jwt.request_formats = { user: [:html], api_user: [nil, :json] }
```

Means that when a request comes in for api_user in nil (unspecified) or JSON format, then accept it. But not for html. On second thoughts, I should remove the `user: [:html]` part, since I don't need JWT for "user"s or html requests.

**Comment by coleyb** [comment]
For anyone else running into this issue, what fixed it for me was to also pass the token as part of the `/logout` request. I assumed devise-jwt would be able to find and blacklist the appropriate jwt but that was not the case, unless I explicitly provided the token.

**Comment by krnjn** [comment]
@coleyb would you mind expanding on your comment a bit? In particular, I'm curious about the shape / params you submitted as part of the request. Usually DELETE requests don't have any body and we are already including the token as part of the `Bearer TOKEN` in the `Authorization` header, so not sure I'm following quite the difference of what you had done that enabled the auto-deletion of the jwt via the gem.

@waiting-for-dev I've found that I also had to implement a solution to manually delete the AllowlistedJTI directly from the table rather than having the gem handle that part (though the gem does seem to gracefully handle the creation / insertion of those components in the table). I suspected that it had something to do with the `before_action` on `verify_signed_out_user`, but even skipping that does not mean that the token gets deleted out of the table automatically by the gem.

**Comment by waiting-for-dev** [comment]
> @waiting-for-dev I've found that I also had to implement a solution to manually delete the AllowlistedJTI directly from the table rather than having the gem handle that part (though the gem does seem to gracefully handle the creation / insertion of those components in the table). I suspected that it had something to do with the before_action on verify_signed_out_user, but even skipping that does not mean that the token gets deleted out of the table automatically by the gem.

This should be handled in this method:

https://github.com/waiting-for-dev/devise-jwt/blob/af1c35074f69abe15c847eb3b41814114ea875f8/lib/devise/jwt/revocation_strategies/allowlist.rb#L34-L37

This can help you debugging. If you find some problem, please, open an issue with all the information. Cheers.

**Comment by krnjn** [comment]
@waiting-for-dev -- we had an issue on our end with the implementation where some of the requests being sent for the specified revocation route were not including the `Bearer ` prefix for the request so the gem was not able to find / destroy the jwt in the database as a result. Just a heads up in case anyone is making requests and forgetting to prefix their `Authorization` header with `Bearer `.

Thanks for the quick response!
