### ISSUE TITLE
ActionController::RoutingError (undefined method authenticate_user!)

### ISSUE THREAD

**Issue by mcollie1** [waiting-for-dev/devise-jwt#146]
## Expected behavior 
Expect to send request to registrations controller, or another controller, with `before_action: authenticate_user!` set and the user be either authenticated or unauthorized

## Actual behavior
Rails returns

ActionController::RoutingError (undefined method `authenticate_api_v1_user!' for Api::V1::CompaniesController:Class):

## Steps to Reproduce the Problem

My setup is such

**routes.rb**
```
Rails.application.routes.draw do

  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'signup'
    },
    controllers: {
      sessions: 'sessions',
      registrations: 'registrations'
    }
  namespace :api do
    namespace :v1 do
```
**registrations controller**

```
class RegistrationsController < Devise::RegistrationsController
  before_action authenticate_user!
  respond_to :json

  def create
    puts "!!!!!!!!! current user -----> #{current_user}"
    raise
    build_resource(sign_up_params)

    resource.save
    render_resource(resource)
  end

  def sign_up_params
    puts "!!!!!!!! params ------> #{params}"
    params.require(:user).permit(:first_name, :last_name, :role, :email, :customer_id, :password, :password_confirmation)
  end
end
```

where render_resource is a custom action. However, the `puts` nor `custom method` gets called because it fails at `authenticate_user!`

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- Version of `devise-jwt` in use `0.5.9`
- Version of `rails` in use `5.2.3`

Has any one else encountered this issue and knows how to resolve it?

## Context
**Rails API (only) application**

**Comment by waiting-for-dev** [comment]
devise-jwt does not introduce anything in the rails controller layer, so your issue is not related with it (you can try to deactivate devise-jwt to confirm it).

As a clue, it seems you are mixing `user` with `api_v1_user` in the naming of the devise scope, so maybe it has some relation.

**Comment by mcollie1** [comment]
I'm not sure if I'm following. There isn't a separate users controller, nor nested routing inside of the namespace. And the registrations controller exists outside of the controllers/api directory. 

As a test, earlier, I nested `devise_for :users` under `namespace :v1 do` and then called `before_action authenticate_api_v1_user!`. But there error was the same

**Comment by mcollie1** [comment]
So I took the route of overriding authenticate_user and authenticate_user! by defining it in the application controller

Similar to this example. 

https://thinkster.io/tutorials/rails-json-api/setting-up-users-and-authentication-for-our-api

However, what I noticed is that `authenticate_user!` was still `undefined`, despite other controllers inheriting from ApplicationController (note, I sent a GET Request to a controller that inherits from ApplicationController). 

And the application controller class is so `class ApplicationController < ActionController::Base`

Hmmm. From there, I decided to call authenticate_user! directly inside of the action (`#index`) and the method executed.

Not sure why, but calling it with `before_action` seems to be the issue.

**Comment by waiting-for-dev** [comment]
What is strange in your issue report is that you are calling `authenticate_user!`, but you say you are getting the following error:

```ruby
ActionController::RoutingError (undefined method `authenticate_api_v1_user!' for Api::V1::CompaniesController:Class):
```

Maybe you have some stalled code somewhere but, anyway, it is not a devise-jwt issue. I'm sorry, but from what I see I can't help you. Please, if you can reproduce the problem with an isolated application and you can confirm it disappears when you deactivate devise-jwt, I'll look happily into it. For now, I can recommend you to ask in stackoverflow, because it seems a devise (without jwt) problem.

**Comment by mcollie1** [comment]
Also, is `current_user` be called?

**Comment by waiting-for-dev** [comment]
You can use all regular devise controller methods, mainly because devise-jwt is doing nothing in the controller layer. devise-jwt is just a warden (the underlying library below devise) hook adding a token to the response and validating it in a request.
