### ISSUE TITLE
how save unique device id in `whitelisted_jwts` table?

### ISSUE THREAD

**Issue by serg2801** [waiting-for-dev/devise-jwt#147]
Hi Guys. 
I'm using this gem for api and I need to send push notifications to mobile app. I can't find any way for store unique device id in `whitelisted_jwts` table. 
gem does not support it?
Thanks.

**Comment by waiting-for-dev** [comment]
It [stores the token `aud` claim](https://github.com/waiting-for-dev/devise-jwt/blob/master/lib/devise/jwt/revocation_strategies/whitelist.rb#L43) which is set through the [`aud_header`](https://github.com/waiting-for-dev/devise-jwt#aud_header), so you can configure it and send the device id along with it.

**Comment by serg2801** [comment]
@waiting-for-dev yes it works. thanks a lot.
