### ISSUE TITLE
Question: How to have an API Controller and a normal Controller in the same rails app

### ISSUE THREAD

**Issue by Subomi** [waiting-for-dev/devise-jwt#149]
Hi there, I have question. 

I have a rails app, that needs both the conventional rails controller as well as an API. I'm using this gem for the jwt authentication for the API. So here's what I'm doing I created two base controllers 

For the API Controller: 

    class API::V1::ApiController < ActionController::API
    end

For the conventional controller: 

    class ApplicationController < ActionController::Base
    end

Now, what I want to ensure is that the two controllers request specifically for a different auth mechanism. Not the try all mechanism warden uses. 

My naive solution is 

    class API::V1::ApiController < ActionController::API

       def authenticate_user!
          render status: 401 if warden.authenticate?(:jwt)
          super
       end

However, this is going to be making redundant API calls. How will you suggest I go about this?

**Comment by Subomi** [comment]
Update, apparently, warden.authenticate?(:jwt) does not also work.

**Comment by waiting-for-dev** [comment]
This question is not related to devise-jwt, but anyway warden only understands about scopes, so a scope authentication will go through the cascade of strategies no matter in which request you are.

I see no reason to complicate things without a good reason, but you can create your own strategies and use [`#valid?`](https://github.com/wardencommunity/warden/wiki/Strategies#valid) to check something in `#env` that you add only in certain requests, for example. Or maybe you can do something through [warden callbacks](https://github.com/wardencommunity/warden/wiki/Callbacks).

**Comment by Subomi** [comment]
I actually figured it wasn't necessary to do what I wanted with this gem, so I went the manual route. Meaning decoding & encoding jwt's myself etc. 

Thanks for your help.
