### ISSUE TITLE
I have error "NameError: uninitialized constant User (call 'User.connection' to establish a connection)::Whitelist"

### ISSUE THREAD

**Issue by dbachinin** [waiting-for-dev/devise-jwt#152]
Hi!
I try create test application with JWT-autorization. 

I add devise-jwt into Gemfile, then initialise Devise and generate User.
And after I add this line to User model 
```  devise :database_authenticatable, :jwt_authenticatable, jwt_revocation_strategy: Whitelist```
And I cant't apply migration now. Because an error appears `NameError: uninitialized constant User (call 'User.connection' to establish a connection)::Whitelist`
I have same error if have `Blacklist` instead `Whitelist`.
What I did wrong?

**Comment by waiting-for-dev** [comment]
For whitelist `self` is the revocation strategy. Please, refer to the README:

https://github.com/waiting-for-dev/devise-jwt#whitelist
