### ISSUE TITLE
Don't generate JWT on sign-in

### ISSUE THREAD

**Issue by pivotal-pmital** [waiting-for-dev/devise-jwt#155]
I am trying to give users more control over when jwts are created and destroyed.

I saw the configuration for `config.jwt.dispatch_requests` where I can dispatch jwt requests on custom routes. However, I was wondering if there is a way to disable dispatch requests on sign-in because I don't want the jwt to invalidated/overwritten due to a new sign-in. 

At the same time, I was wondering if there is way to prevent revoking the JWT when the user logs out of the app.

**Comment by waiting-for-dev** [comment]
`devise-jwt` [pushes sign-in/sign-out routes](https://github.com/waiting-for-dev/devise-jwt/blob/master/lib/devise/jwt/railtie.rb#L12) in an `after_initialize` block. If I'm not wrong, you can override it using your own `after_initialize`. For example, to have no configured routes:

```ruby
config.after_initialize do
  config.dispatch_requests = []
  config.revocation_requests = []
end
```

**Comment by pivotal-pmital** [comment]
Ooo that's nice! That worked nicely. Thanks a lot! :D

**Comment by waiting-for-dev** [comment]
Happy that it works :smile:
