### ISSUE TITLE
Expiration time not setting up properly

### ISSUE THREAD

**Issue by jean182** [waiting-for-dev/devise-jwt#158]
Hi I'm using Blacklist revocation and I noticed on the FE that my jwt token is not returning the exp value that I'm setting in the devise.rb initializer

## Expected behavior

Use the actual `jwt.expiration_time`

## Actual behavior

Uses this expiration time: 1580188973

## Steps to Reproduce the Problem

1. Send a post request to `sessions#create` route
2. Check the authorization header
3. Test the value after bearer here https://jwt.io/

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- Version of `devise-jwt` in use
 `devise-jwt (0.6.0)`
- Version of `rails` in use
 `"rails", "~> 5.2.3"`
- Output of `Devise::JWT.config`
 ```js
#<#<Class:0x00007fbaf92065a0>:0x00007fbaf92062a8 @config={:secret=>"SECRET", :expiration_time=>nil, :dispatch_requests=>[["POST", /^api\/v1\/sign_in$/], ["POST", /^\/api\/v1\/users\/sign_in$/], ["POST", /^\/api\/v1\/users$/]], :revocation_requests=>[["DELETE", /^api\/v1\/sign_out$/], ["DELETE", /^\/api\/v1\/users\/sign_out$/]], :aud_header=>nil, :request_formats=>{}}, @lock=#<Thread::Mutex:0x00007fbaf9206258>, @defined=true> 
```
- Output of `Warden::JWTAuth.config`
```
#<#<Class:0x00007fbaf91be250>:0x00007fbaf91be070 @config={:secret=>"SECRET", :algorithm=>"HS256", :expiration_time=>3600, :aud_header=>"JWT_AUD", :mappings=>{:user=>"User"}, :dispatch_requests=>[["POST", /^api\/v1\/sign_in$/], ["POST", /^\/api\/v1\/users\/sign_in$/], ["POST", /^\/api\/v1\/users$/]], :revocation_requests=>[["DELETE", /^api\/v1\/sign_out$/], ["DELETE", /^\/api\/v1\/users\/sign_out$/]], :revocation_strategies=>{:user=>"JwtBlacklist"}}, @lock=#<Thread::Mutex:0x00007fbaf91be020>, @defined=true>
```
- Output of `Devise.mappings`
```ruby
{:user=>#<Devise::Mapping:0x00007fbaf8419578 @scoped_path="users", @singular=:user, @class_name="User", @klass=#<Devise::Getter:0x00007fbaf8418f60 @name="User">, @path="api/v1/users", @path_prefix=nil, @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:sessions=>"api/v1/sessions", :registrations=>"api/v1/registrations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :sign_up=>"sign_up", :cancel=>"cancel"}, @modules=[:database_authenticatable, :rememberable, :registerable, :validatable, :timeoutable, :jwt_authenticatable], @routes=[:session, :registration], @used_routes=[:session, :registration], @used_helpers=[:session, :registration]>} 
```

Not sure if relevant but here's the repo:
https://github.com/jean182/pokemon-api

**Comment by waiting-for-dev** [comment]
I think everything is correct. You configure the number of seconds from the issuing time you want your token to be valid. The token `exp` claim returns the time in UNIX epoch time when the token will expire. In you example, you are configuring 3600 seconds, that's an hour, and it's going to expire on 1580188973 unix seconds, which is today at 5:22 AM. You can check it yourself at https://www.unixtimestamp.com/.

**Comment by jean182** [comment]
Yes I tried to set up to 20 seconds in the expiration time like this ` jwt.expiration_time = 20.seconds.to_i` to test my frontend and I was wondering if I need to clear cache or do something else to see the changes reflected.

**Comment by waiting-for-dev** [comment]
You don't need to do anything else.

> Uses this expiration time: 1580188973

So it seems it's working, isn't it?

**Comment by waiting-for-dev** [comment]
Closing because the lack of feedback. Feel free to add more comments if needed.
