### ISSUE TITLE
Changing jwt payload

### ISSUE THREAD

**Issue by NickyHeuperman** [waiting-for-dev/devise-jwt#16]
Is there a way to change the payload in the controller instead of the model? I'm currently using devise with rolify and devise-jwt and I'd like to add my roles to the payload.

As the current_user object doesn't exist in the model as it shouldn't I can't inject the roles in the jwt_payload method in my User model.

Thanks in advance

**Comment by waiting-for-dev** [comment]
Is it not possible to access associated roles from a user instance?

Anyway, I wouldn't add role information in the payload. I [wrote about it](http://waiting-for-dev.github.io/blog/2017/01/25/jwt_secure_usage/):

> Don’t add information that may change for a user. For instance, a lot of times people recommend adding role information so that a database query can be saved. For example, in your JWT payload you would add that alice user has 3 as id and she has admin role. What happens if admin privilege is revoked for alice? If the token that states the opposite is still valid she could still ‘look’ like an admin.

**Comment by NickyHeuperman** [comment]
While I get your point, my use case is for internal SSO, with an expiration of tokens within an hour and a valid revocation strategy in place these security concerns are quite diminished. On to the point of this thread however; Yes associated roles are accesible in any user instance and I guess I just sort of had a brain fart. Thank you for your reply though :)

**Comment by waiting-for-dev** [comment]
No worries :)
