### ISSUE TITLE
JTI Claim is different from user.jti column (use JTIMatcher)

### ISSUE THREAD

**Issue by alainkp** [waiting-for-dev/devise-jwt#167]
Hello,

I'm not sure if I understand the JTIMatcher revocation strategy, but the README state the following :

> * At the same time that a token is dispatched for a user, the jti claim is persisted to the jti column.
> * At every authenticated action, the incoming token jti claim is matched against the jti column for that user. The authentication only succeeds if they are the same.
> * When the user requests to sign out its jti column changes, so that provided token won't be valid anymore.

The 1st point seems to not work properly in my project. The 2nd and 3rd points are OK.
Every time I fire a login request a new JTI claim is generated in the dispatched JWT, but it is not saved on the user model on the jti column. So when I use the received JWT, devise and devise JWT cannot login the user because the jti claim in the JWT does not exist in the database.

When I logout, `user.jti` is properly updated in the DB.

## Expected behavior
* On login, generated jti claim contained in the JWT should be persisted in`user.jti`. 
* On several call on /login for the same user:
  * jti claim should be different
  * `user.jti` should be set with this new jti claim

## Actual behavior
* On login, generated jti claim contained in the JWT is not persisted in`user.jti`. 
* On several call on /login for the same user:
  * jti claim is always different as expexted
  * `user.jti` is not set with the new jti claim

## Steps to Reproduce the Problem

1. POST /login 
body :
```json
{
  "user": {
    "email": "alain@a.com",
    "password": "123456"
  }
}
```
2. Receive response 200 ok
Response 
```json
{
    "id": 1,
    "email": "alain@a.com",
    "created_at": "2020-03-20T23:26:45.644Z",
    "updated_at": "2020-03-23T16:39:41.454Z",
    "jti": "425a6d7b-261c-414b-a8ac-63d4286d8d46"
}
```
JTI in the response match with the one in the DB

Headers:
```
Authorization : Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsYWluQGEuY29tIiwic3ViIjoiMSIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTU4NTA0ODEwOSwiZXhwIjoxNTg1MTM0NTA5LCJqdGkiOiIxNjRkMmY2MS0zZmIyLTQyZmYtYjQ3YS0wNTQxNGM4NTFmYzEifQ.KYC47U-AI-ynyQQ0-dh2_pbtlSKuxtbO5VK152GzdXU
```
[Debug JWT token with https://jwt.io/#debugger-io](https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsYWluQGEuY29tIiwic3ViIjoiMSIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTU4NTA0ODEwOSwiZXhwIjoxNTg1MTM0NTA5LCJqdGkiOiIxNjRkMmY2MS0zZmIyLTQyZmYtYjQ3YS0wNTQxNGM4NTFmYzEifQ.KYC47U-AI-ynyQQ0-dh2_pbtlSKuxtbO5VK152GzdXU) show the jti claim different from the server response : 
```
"jti": "164d2f61-3fb2-42ff-b47a-05414c851fc1"
```
3. Fire the same login request and get another JTI claim in the JWT but `user.jti` never change.

## Debugging information

- Version of `devise-jwt` : (0.6.0)
- Version of `rails` in use : (6.0.2.1)
- Output of `Devise::JWT.config`: 
```ruby
#<#<Class:0x00007fa8597c4850>:0x00007fa8597c4648
 @config=
  {:secret=>"devisejwtsecret",
   :expiration_time=>86400,
   :dispatch_requests=>[["POST", /^\/login$/], ["POST", /^\/login$/], ["POST", /^\/signup$/]],
   :revocation_requests=>[["DELETE", /^\/logout$/], ["DELETE", /^\/logout$/]],
   :aud_header=>nil,
   :request_formats=>{}},
 @defined=true,
 @lock=#<Thread::Mutex:0x00007fa8597c45d0>>
```
- Output of `Warden::JWTAuth.config`:
```ruby
#<#<Class:0x00007fa85e003530>:0x00007fa85e0031c0
 @config=
  {:secret=>"devisejwtsecret",
   :algorithm=>"HS256",
   :expiration_time=>86400,
   :aud_header=>"JWT_AUD",
   :mappings=>{:user=>"User"},
   :dispatch_requests=>[["POST", /^\/login$/], ["POST", /^\/login$/], ["POST", /^\/signup$/]],
   :revocation_requests=>[["DELETE", /^\/logout$/], ["DELETE", /^\/logout$/]],
   :revocation_strategies=>{:user=>"User"}},
 @defined=true,
 @lock=#<Thread::Mutex:0x00007fa85e0030f8>>
```
- Output of `Devise.mappings`:
```ruby
 #<Devise::Mapping:0x00007fa8604a4628
   @class_name="User",
   @controllers={:sessions=>"sessions", :registrations=>"registrations"},
   @failure_app=Devise::FailureApp,
   @format=nil,
   @klass=#<Devise::Getter:0x00007fa8604a4290 @name="User">,
   @modules=[:database_authenticatable, :registerable, :jwt_authenticatable],
   @path="",
   @path_names=
    {:registration=>"signup",
     :new=>"new",
     :edit=>"edit",
     :sign_in=>"login",
     :sign_out=>"logout",
     :sign_up=>"sign_up",
     :cancel=>"cancel"},
   @path_prefix=nil,
   @router_name=nil,
   @routes=[:session, :registration],
   @scoped_path="users",
   @sign_out_via=:delete,
   @singular=:user,
   @used_helpers=[:session, :registration],
   @used_routes=[:session, :registration]>}
```

Sessions Controller
```ruby
class SessionsController < Devise::SessionsController
  respond_to :json
  private

  def respond_with(resource, _opts = {})
    render json: resource
  end

  def respond_to_on_destroy
    head :no_content
  end
end
```

User Model
```ruby
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :database_authenticatable,
         :registerable,
         :jwt_authenticatable,
         jwt_revocation_strategy: self

  def jwt_payload
    super
    { email: email }
  end
end
```

Routes
```ruby
devise_for :users,
               path: '',
               path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 registration: 'signup'
               },
               controllers: {
                 sessions: 'sessions',
                 registrations: 'registrations'
               }
```

CORS
```ruby
config.middleware.insert_before 0, Rack::Cors do
      allow do
        origins '*'
        resource(
          '*',
          headers: :any,
          expose: ["Authorization"],
          methods: [:get, :patch, :put, :delete, :post, :options, :show]
        )
      end
    end
```

Devise
```ruby
config.jwt do |jwt|
    jwt.secret = Rails.application.credentials.devise_jwt_secret_key
    jwt.dispatch_requests = [
      ['POST', %r{^/login$}]
    ]
    jwt.revocation_requests = [
      ['DELETE', %r{^/logout$}]
    ]
    jwt.expiration_time = 1.day.to_i
  end
```

**Comment by waiting-for-dev** [comment]
Thanks for your detailed report @alainkp 

I think the problem is that you're overwriting `#jwt_payload` method in the user model. You are just calling super (which returns a hash with the `jti` claim from the revocation strategy), but you're not merging its content in. Try with:

```ruby
  def jwt_payload
    super.merge email: email
  end
```

**Comment by alainkp** [comment]
Marc, Thanks you for you quick answer. Your solution work as expected! Awesome gem :)

Just to be sure to understand the JTIMatcher revocation strategy, the workflow seems to be a little bit different than the one described in the README:

* On token dispatch, jti claim is filled with `user.jti` from the DB and it is not generated on token creation, thus `user.jti` is not persisted on login.
* So when I try to log several time with the same user, I get the same jti claim (the one from the DB).
* On logout `user.jti` is updated on the DB so the token is revoked, on the next login token is created with the `user.jti` from the DB.

Can you confirm the workflow ?

**Comment by waiting-for-dev** [comment]
> On token dispatch, jti claim is filled with user.jti from the DB and it is not generated on token creation, thus user.jti is not persisted on login.

Yeah, `jti` is taken from the model on token creation/dispatch and added to the payload

> - So when I try to log several time with the same user, I get the same jti claim (the one from the DB).
> - On logout user.jti is updated on the DB so the token is revoked, on the next login token is created with the user.jti from the DB (the one from the logout action).

Right

You're right, the README was not clear enough. I fixed it.

**Comment by alainkp** [comment]
Great thank you for the confirmation :) I close the issue.
