### ISSUE TITLE
Error `You need to sign in or sign up before continuing` on user sign_in from the browser

### ISSUE THREAD

**Issue by paulgaumer** [waiting-for-dev/devise-jwt#168]
## Expected behavior

I am building an app with a Rails 6 API and a NextJS front-end.
I want to retrieve the user Bearer token on user sign_in from the client (NextJS)

## Actual behavior

I get the error message `error: You need to sign in or sign up before continuing` on user sign_in or sign_up from the client (NextJS)

## Steps to Reproduce the Problem

I actually followed this tutorial (without the Docker setup): https://medium.com/@fishpercolator/how-to-separate-frontend-backend-with-rails-api-nuxt-js-and-devise-jwt-cf7dd9da9d16

Everything works great using Postman: I can sign_in, retrieve the Bearer Token and use to it to get the user info.

However when trying to do it from the browser (NextJS), I get the error `You need to sign in or sign up before continuing`. Same when I try the sign_up a user (works fine in Postman).

I found [a ticket with a similar error](https://github.com/waiting-for-dev/devise-jwt/issues/98) but I believe the object I send in the body is correct

My call is done as follows from Next
```js
const login = async () => {
    const res = await fetch('http://localhost:3000/api/users/sign_in', {
      method: 'POST',
      header: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        user: { email: 'bob@test.com', password: 'password' }
      })
    });
    const data = await res.json();
  };
```

Here is my client repo: https://github.com/paulgaumer/Next_Rails_API
And my Rails API repo: https://github.com/paulgaumer/Rails_API_Next

I am stuck. What am I doing wrong?
Thank you!

**Comment by waiting-for-dev** [comment]
Probably you need to configure your application to [respond to json](https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs#responding-to-json).

**Comment by paulgaumer** [comment]
Thanks Marc. It should already be the case 

Here is my application_controller.rb
```rb
class ApplicationController < ActionController::API
  include ActionController::MimeResponds
  respond_to :json
end
```

**Comment by waiting-for-dev** [comment]
By default devise controllers inherit from `ApplicationController`, but you can change it with `parent_controller` configuration option.

**Comment by waiting-for-dev** [comment]
https://github.com/heartcombo/devise/blob/master/lib/devise.rb#L234

**Comment by paulgaumer** [comment]
So I tried changing my devise.rb with this
```rb
config.parent_controller = 'DeviseController'
```
But then I get a `ActionController::RoutingError (uninitialized constant DeviseController)` error

The thing is that I do also have a sessions_controller.rb as follows. And without modifying anything in devise.rb, the API gives me good responses in Postman.
```rb
class SessionsController < Devise::SessionsController
  def create
    super { @token = current_token }
  end

  def show
  end

  private

  def current_token
    request.env['warden-jwt_auth.token']
  end
end
```

Not sure why Postman works but not the browser.

**Comment by waiting-for-dev** [comment]
> So I tried changing my devise.rb with this

You should set `ActionController::API`, if I'm not wrong

> Not sure why Postman works but not the browser.

Are you setting `Accept` header to `application/json` in your browser?

**Comment by tashi-179** [comment]
Are you able to solve this issue? 

I have also encountered similar problem  and has to struggle to get the solution. 
The solution is very simple, when you `sign_in` or `sign_out` avoid sending `Authorization` header.

**Comment by tashi-179** [comment]
> Are you able to solve this issue?
> :
> I have also encountered similar problem and has to struggle to get the solution.
> The solution is very simple, when you `sign_in` or `sign_out` avoid sending `Authorization` header.

You can reproduce similar problem if you send `Authorization` header when you `sign_in` in postman.

**Comment by paulgaumer** [comment]
Thanks @waiting-for-dev and @tashi-179 , I was able to fix it. 
It was a mix of bad syntax in my request headers and CORS issues on the Rails side. Thanks for the support and the gem 🙏
