### ISSUE TITLE
Of the 10 Devise Modules, which are supported with the `devise-jwt` gem?

### ISSUE THREAD

**Issue by redline-gh** [waiting-for-dev/devise-jwt#173]
Of the 10 Devise Modules:

- Database Authenticatable
- Omniauthable
- Recoverable
- Registerable
- Rememberable
- Trackable
- Timeoutable
- Validatable
- Lockable

Which are supported with the `devise-jwt` gem? For example, can a jwt token be rememberable? ie: If the user checks a "remember me" box, the token will be persisted for longer than if it was unchecked.

**Comment by waiting-for-dev** [comment]
This library just provides with another authorization strategy (see [Warden strategies](https://github.com/wardencommunity/warden/wiki/Strategies), devise is build on top of it), so it will play well with other strategies only when it makes sense. About "remember me", it works through a cookie. If you are using cookies there's no need to use jwt tokens for authorization. As I said, `devise-jwt` doesn't mess with other plugins, so it won't extend automagically tokens expiration time.
