### ISSUE TITLE
Refreshing token on every request to a given route

### ISSUE THREAD

**Issue by leesus** [waiting-for-dev/devise-jwt#174]
I am looking to refresh a token on every request to a given route. It looks like this should be supported as per your response in https://github.com/waiting-for-dev/devise-jwt/issues/88. However, the token revocation is happening and then logging out my user, rather than just resetting the token. Is some further manual setup required besides the following?
```
jwt.dispatch_requests = [
  ['POST', %r{^/my/endpoint}]
]
jwt.revocation_requests = [
   ['POST', %r{^/my/endpoint}]
]
``` 
Thanks

**Comment by waiting-for-dev** [comment]
You have to get the new token from the response headers.

**Comment by leesus** [comment]
I am passing the new token I receive in the response headers, but on the next request the user is logged out. When decoding the new JWT manually, I can see that the JTI doesn't match that of the user in the database. Is the encoding of the JWT happening before the revocation of the JTI?

For completeness, this is what is happening:
1. POST /users/sign_in returns Token A
2. POST /graphql with Token A returns Token B
3. POST /graphql with Token B responds with 401 - here Token B JTI doesn't match User JTI

**Comment by leesus** [comment]
It turns out this works if we don't include the endpoint in the revocation requests, only the dispatch requests.
