### ISSUE TITLE
Conditional Sign Out Request

### ISSUE THREAD

**Issue by trevorrjohn** [waiting-for-dev/devise-jwt#175]
I have a feature where I want to conditionally lock an account and sign out a user. I am wondering what the best way to conditionally set the response authorization token or even for that matter conditionally sign out the user. 

This is what I have so far, it works, but it doesn't feel right. Curious what your thoughts are.

```ruby
# in config
# jwt.dispatch_requests = [['POST', /^lock$/]]

# controller.rb

def create
  if created? # some logic
    current_user.update(jti: SecureRandom.uuid)
    request.env.delete['warden-jwt_auth.token']
    head :created
  else
    render json: :error
  end
end
```

It just feels strange that the token is set and then I have to unset it, but I am not sure where I can hook into the revocation? Should this be in a Revocation strategy? The issue there is this is the only request that should be conditional, `DELETE /sign_out` should always sign out obviously.

Thanks!

**Comment by waiting-for-dev** [comment]
You can create a [custom revocation strategy](https://github.com/waiting-for-dev/devise-jwt#custom-strategies). Then, in `#revoke_jwt` you can just do nothing when you don't want to revoke the user.

**Comment by trevorrjohn** [comment]
Hmm ok I will have to take a look. My issue there is that my user lock is a separate database record, so now every time this method is called I have to make another request to the DB. Where if it was somehow linked to the controller, I have the full context there.

**Comment by waiting-for-dev** [comment]
Maybe you can add something in the token payload and take advantage of it to avoid some database call later, but keep in mind information can be staled if it changes but a dispatched token keeps being valid. Otherwise you can manually work with the [token revoker](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/token_revoker.rb) from your controller.

**Comment by waiting-for-dev** [comment]
Closing but feel free to add more questions if needed.

**Comment by mkhoa1412** [comment]
> Maybe you can add something in the token payload and take advantage of it to avoid some database call later, but keep in mind information can be staled if it changes but a dispatched token keeps being valid. Otherwise you can manually work with the [token revoker](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/token_revoker.rb) from your controller.

Hi @waiting-for-dev how i call TokenRevoker.call() in controller. 
I use Denylist and want to revoke a token when deactive a user

**Comment by waiting-for-dev** [comment]
Are you storing the `jti` for the user you want to deactivate? Otherwise, I think you're out of luck with this strategy. `JtiMatcher` would work better for you.

**Comment by mkhoa1412** [comment]
Unfortunately, I'm using Denylist strategy

**Comment by waiting-for-dev** [comment]
You still could:

- Change secret to log out all users.
- Begin storing the token (which you can find at `request.env['warden-jwt_auth.token']`) and associate it with the user.
- Add the token to the deny list when admin deactivates a user.

**Comment by mkhoa1412** [comment]
> You still could:
> 
> * Change secret to log out all users.
> * Begin storing the token (which you can find at `request.env['warden-jwt_auth.token'])` and associate it with the user.
> * Add the token to the deny list when admin deactivates a user.
Thanks for your quick reply.
Begin storing the token .and associate it with the user -> do you think should i change to Whitelist strategy ?

**Comment by waiting-for-dev** [comment]
Probably it would simplify your workflow as `jti` is tracked out of the box. Same for `JTIMatcher`.
