### ISSUE TITLE
checking Authorization header when request signin with email and password.

### ISSUE THREAD

**Issue by fatpig0416** [waiting-for-dev/devise-jwt#179]
First of all, I'd like to thank you for this package.
My current issue is that I cannot signin with devise.
This works perfectly first time, but after I added namespace Api::V1, it stopped working.
When I was trying to signin[POST], I got following response:
`"error": "You need to sign in or sign up before continuing."`
I think it checks the `Authorization` header even for signin request.
P.S.
I updated `initializers/devise.rb` like following
`
from: 

jwt.dispatch_requests = [
        ['POST', %r{^/signin$}]
]
to:

jwt.dispatch_requests = [
        ['POST', %r{^/api/v1/signin$}]
    ]
`

routes.rb

`
Rails.application.routes.draw do

  namespace :api do

    namespace :v1 do

        devise_for :users, defaults: {format: :json},

                 path: '',

                 path_names: {

                     sign_in: 'signin',

                     sign_out: 'signout',

                 },

                 controllers: {

                     sessions: 'api/v1/user/sessions',

                     confirmations: 'devise/confirmations',

                     passwords: 'devise/passwords',

                 }

    end

  end

end
`

## Expected behavior
I should be able to sign in with email/password without checking `token`.
## Actual behavior
It appears to check JWT token.
As a result, I got `"error": "You need to sign in or sign up before continuing."`.

## Debugging information

- Version of `devise-jwt` in use: `6.0.0
- Version of `rails` in use: `6.0.3
- Output of `Devise::JWT.config`
`@config={:secret=>"9415a505423c0b509e433c6da68535e1bf579de32a36d3f2dc9a0383d4610327fd83521668d36a1948939ae3c9334bfd63d1c372084ebd0663539a04394f9423", :expiration_time=>30000, :dispatch_requests=>[["POST", /^\/api\/v1\/signin$/], ["POST", /^\/api\/v1\/admin_user\/sign_in$/], ["POST", /^\/api\/v1\/admin_user$/], ["POST", /^\/api\/v1\/agency_user\/sign_in$/], ["POST", /^\/api\/v1\/agency_user$/], ["POST", /^\/api\/v1\/brand_user\/sign_in$/], ["POST", /^\/api\/v1\/brand_user$/], ["POST", /^\/api\/v1\/influencer_user\/sign_in$/], ["POST", /^\/api\/v1\/influencer_user$/], ["POST", /^\/api\/v1\/signin$/], ["POST", /^\/api\/v1$/]], :revocation_requests=>[["DELETE", /^\/api\/v1\/signout$/], ["DELETE", /^\/api\/v1\/admin_user\/sign_out$/], ["DELETE", /^\/api\/v1\/agency_user\/sign_out$/], ["DELETE", /^\/api\/v1\/brand_user\/sign_out$/], ["DELETE", /^\/api\/v1\/influencer_user\/sign_out$/], ["DELETE", /^\/api\/v1\/signout$/]], :aud_header=>nil, :request_formats=>{}}, @lock=#<Thread::Mutex:0x000055bd72d9ab18>, @defined=true
`
- Output of `Warden::JWTAuth.config`
`
@config={:secret=>"9415a505423c0b509e433c6da68535e1bf579de32a36d3f2dc9a0383d4610327fd83521668d36a1948939ae3c9334bfd63d1c372084ebd0663539a04394f9423", :algorithm=>"HS256", :expiration_time=>30000, :aud_header=>"JWT_AUD", :mappings=>{:api_v1_admin_user=>"AdminUser", :api_v1_agency_user=>"AgencyUser", :api_v1_brand_user=>"BrandUser", :api_v1_influencer_user=>"InfluencerUser", :api_v1_user=>"User"}, :dispatch_requests=>[["POST", /^\/api\/v1\/signin$/], ["POST", /^\/api\/v1\/admin_user\/sign_in$/], ["POST", /^\/api\/v1\/admin_user$/], ["POST", /^\/api\/v1\/agency_user\/sign_in$/], ["POST", /^\/api\/v1\/agency_user$/], ["POST", /^\/api\/v1\/brand_user\/sign_in$/], ["POST", /^\/api\/v1\/brand_user$/], ["POST", /^\/api\/v1\/influencer_user\/sign_in$/], ["POST", /^\/api\/v1\/influencer_user$/], ["POST", /^\/api\/v1\/signin$/], ["POST", /^\/api\/v1$/]], :revocation_requests=>[["DELETE", /^\/api\/v1\/signout$/], ["DELETE", /^\/api\/v1\/admin_user\/sign_out$/], ["DELETE", /^\/api\/v1\/agency_user\/sign_out$/], ["DELETE", /^\/api\/v1\/brand_user\/sign_out$/], ["DELETE", /^\/api\/v1\/influencer_user\/sign_out$/], ["DELETE", /^\/api\/v1\/signout$/]], :revocation_strategies=>{:api_v1_admin_user=>"JwtBlacklist", :api_v1_agency_user=>"JwtBlacklist", :api_v1_brand_user=>"JwtBlacklist", :api_v1_influencer_user=>"JwtBlacklist", :api_v1_user=>"JwtBlacklist"}}, @lock=#<Thread::Mutex:0x000055bd72ae7f10>, @defined=true
`
- Output of `Devise.mappings`
`
{:api_v1_admin_user=>#<Devise::Mapping:0x000055bd75829af0 @scoped_path="api_v1/admin_users", @singular=:api_v1_admin_user, @class_name="AdminUser", @klass=#<Devise::Getter:0x000055bd75829578 @name="AdminUser">, @path="admin_user", @path_prefix="/api/v1", @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:registrations=>"api/v1/admin/devise/registrations", :sessions=>"api/v1/sessions", :passwords=>"api/v1/passwords", :confirmations=>"api/v1/confirmations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel", :confirmation=>"confirmation"}, @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :confirmable, :jwt_authenticatable], @routes=[:session, :password, :registration, :confirmation], @used_routes=[:session, :password, :registration, :confirmation], @used_helpers=[:session, :password, :registration, :confirmation]>, :api_v1_agency_user=>#<Devise::Mapping:0x000055bd758663d8 @scoped_path="api_v1/agency_users", @singular=:api_v1_agency_user, @class_name="AgencyUser", @klass=#<Devise::Getter:0x000055bd75865e60 @name="AgencyUser">, @path="agency_user", @path_prefix="/api/v1", @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:registrations=>"api/v1/agency/devise/registrations", :sessions=>"api/v1/sessions", :passwords=>"api/v1/passwords", :confirmations=>"api/v1/confirmations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel", :confirmation=>"confirmation"}, @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :confirmable, :jwt_authenticatable], @routes=[:session, :password, :registration, :confirmation], @used_routes=[:session, :password, :registration, :confirmation], @used_helpers=[:session, :password, :registration, :confirmation]>, :api_v1_brand_user=>#<Devise::Mapping:0x000055bd758a2cc0 @scoped_path="api_v1/brand_users", @singular=:api_v1_brand_user, @class_name="BrandUser", @klass=#<Devise::Getter:0x000055bd758a2748 @name="BrandUser">, @path="brand_user", @path_prefix="/api/v1", @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:registrations=>"api/v1/brand/devise/registrations", :sessions=>"api/v1/sessions", :passwords=>"api/v1/passwords", :confirmations=>"api/v1/confirmations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel", :confirmation=>"confirmation"}, @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :confirmable, :jwt_authenticatable], @routes=[:session, :password, :registration, :confirmation], @used_routes=[:session, :password, :registration, :confirmation], @used_helpers=[:session, :password, :registration, :confirmation]>, :api_v1_influencer_user=>#<Devise::Mapping:0x000055bd758e7578 @scoped_path="api_v1/influencer_users", @singular=:api_v1_influencer_user, @class_name="InfluencerUser", @klass=#<Devise::Getter:0x000055bd758e7000 @name="InfluencerUser">, @path="influencer_user", @path_prefix="/api/v1", @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:registrations=>"api/v1/influencer/devise/registrations", :sessions=>"api/v1/sessions", :passwords=>"api/v1/passwords", :confirmations=>"api/v1/confirmations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel", :confirmation=>"confirmation"}, @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :confirmable, :jwt_authenticatable], @routes=[:session, :password, :registration, :confirmation], @used_routes=[:session, :password, :registration, :confirmation], @used_helpers=[:session, :password, :registration, :confirmation]>, :api_v1_user=>#<Devise::Mapping:0x000055bd759339a0 @scoped_path="api_v1/users", @singular=:api_v1_user, @class_name="User", @klass=#<Devise::Getter:0x000055bd759335e0 @name="User">, @path="", @path_prefix="/api/v1", @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:sessions=>"api/v1/user/sessions", :confirmations=>"devise/confirmations", :passwords=>"devise/passwords", :registrations=>"api/v1/registrations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"signin", :sign_out=>"signout", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel", :confirmation=>"confirmation"}, @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :confirmable, :jwt_authenticatable], @routes=[:session, :password, :registration, :confirmation], @used_routes=[:session, :password, :registration, :confirmation], @used_helpers=[:session, :password, :registration, :confirmation]>}
`
- If your issue is related with not getting a JWT from the server:
  - Involved request path, method and request headers
  - Response headers for that request
- If your issue is related with not being able to revoke a JWT:
  - Involved request path, method and request headers

**Comment by waiting-for-dev** [comment]
Hey @fatpig0416 , the way warden (the engine under devise) works is by trying to authenticate a user through a cascade of strategies. When one of them succeeds the user is authenticated, and a single strategy can't deny a user by itself if another strategy is granting access. In a sign in, when a token is not sent, devise-jwt will deny access, but devise's own `:database_authenticatable` strategy should be opening the doors. That means that your problem is not with devise-jwt, but with devise itself.  Maybe you are sending email/password with an invalid params format.

**Comment by waiting-for-dev** [comment]
Closing because the lack of feedback. Feel free to add more comments if needed.

**Comment by Bdoom** [comment]
This is basically the same issue I'm having, but I don't want to be using a token lol
