### ISSUE TITLE
Adding validation removes Authorization from Header

### ISSUE THREAD

**Issue by rakvium** [waiting-for-dev/devise-jwt#18]
Authorization is being removed from header when I add a validation to the User model:

Target version: `0.3.0`

JWT and Devise config for User model:
```
  include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :database_authenticatable,
         :recoverable,
         :registerable,
         :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: self

  def jwt_payload
    super
  end
```

Header before I add validation:
```
{"Location"=>"/", "Content-Type"=>"text/plain; charset=utf-8", "Authorization"=>"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJiZTRkNzNlNy0xMjc3LTQyNjUtYWY2MC00ODNjMTBhMDBhYzQiLCJzdWIiOiIxMjAiLCJzY3AiOiJ1c2VyIiwiaWF0IjoxNDk3OTYzNTcwLCJleHAiOjE1MDA1NTU1NzB9.myZ5gDGqFn6AbpDVbIBd5ZQqLPTL4AxqdC5KsYcRQMg", "ETag"=>"W/\"36a9e7f1c95b82ffb99743e0c5c4ce95\"", "Cache-Control"=>"max-age=0, private, must-revalidate", "X-Request-Id"=>"d2f4dc7d-cf30-403a-8a6c-353daeab64c3", "X-Runtime"=>"0.015489", "Vary"=>"Origin", "Content-Length"=>"1"}
```

Validation (the only change I do):
```
  validates_presence_of :first_name
```

Header after I add the validation:
```
{"Content-Type"=>"text/plain; charset=utf-8", "ETag"=>"W/\"36a9e7f1c95b82ffb99743e0c5c4ce95\"", "Cache-Control"=>"max-age=0, private, must-revalidate", "X-Request-Id"=>"860747c0-0529-4492-855c-778698972599", "X-Runtime"=>"0.015620", "Vary"=>"Origin", "Content-Length"=>"1"}
```

P.S.: Setting up `request_formats` or `dispatch_requests` doesn't help. Existing validation on email doesn't affect it though.

**Comment by waiting-for-dev** [comment]
Hey @rakvium ,  the token is only dispatched on a valid sign in or a valid sign up, once a user is identified/created and, therefore, an associated token can be created. It makes no sense to dispatch a token without a user.

**Comment by rakvium** [comment]
@waiting-for-dev, you're right. I've looked into the code of the gem, then into my code and database, and then realized that I forgot to uncomment those lines in registrations controller:
```
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
```
I realized that the user wasn't being saved, and returned back to close this issue.
Please mark this issue as `invalid`, and thank you for your response :)

**Comment by waiting-for-dev** [comment]
No worries :+1:
