### ISSUE TITLE
current_user.is_a?(User) returning false

### ISSUE THREAD

**Issue by rhiroshi** [waiting-for-dev/devise-jwt#183]
## Expected behavior

 current_user.is_a?(User) returning true when using jwt or session

## Actual behavior

 current_user.is_a?(User) returns false when using jwt but true on session

## Steps to Reproduce the Problem

 same as #182 
 - Log in.
Any requests will return true on current_user.is_a?(User) for now 
 - Change code and save
All requests will return false on current_user.is_a?(User) from now on.

## Debugging information

Using 
  devise-jwt 0.8.0
  devise 4.7.2

It seems like devise-jwt caches the User class. 
when i login and get current_user.ancestors[1] it returns #<Module:0x0000000006a42738> and so does User.ancestors[1]
when i update my code, current_user.ancestors[1] is still #<Module:0x0000000006a42738> but User.ancestors[1] has changed.

I dont think it's devise because when i use normal sessions, both current_user.ancestors[1] and User.ancestors[1] changes on code change.

**Comment by rhiroshi** [comment]
Debugging the code, i suspect the culprit is in warden-jwt gem [warden-jwt_auth/lib/warden/jwt_auth.rb#L59](https://github.com/waiting-for-dev/warden-jwt_auth/blob/d973de893009b5138d0ebbdebda288420787fb51/lib/warden/jwt_auth.rb#L59)
`setting(:mappings, {}) do |value|
      constantize_values(symbolize_keys(value))
    end`
It creates another object from Devise.mappings when combined with this gem ( at [devise-jwt/lib/devise/jwt/mapping_inspector.rb#L11](https://github.com/waiting-for-dev/devise-jwt/blob/master/lib/devise/jwt/mapping_inspector.rb#L11) )

So, it seems to be an [autoloading](https://guides.rubyonrails.org/v5.2/autoloading_and_reloading_constants.html#autoloading-and-initializers) problem and the Dry::Configurable initializer in [/devise-jwt/blob/master/lib/devise/jwt/railtie.rb#L12](https://github.com/waiting-for-dev/devise-jwt/blob/master/lib/devise/jwt/railtie.rb#L12)

**Comment by waiting-for-dev** [comment]
Hi @rhiroshi , thanks for your help on this.

I'd like to be able to reproduce it in the test suite so that we can nail down the problem and also avoid regressions.

I tried with this commit but I had no success. Please, take a look. I added you as a collaborator so that you can update `autorelaoding` branch.

https://github.com/waiting-for-dev/devise-jwt/commit/1baa06853c00e1a37bba1089d9ecea23f9ddb0e5

**Comment by rhiroshi** [comment]
Sorry for the delay. 
I've noticed that the JwtWithJtiMatcherUser class was missing the <Module> instance which seemed to be the main issue in my case. 
It is appended to the instanced object ancestors because of a has and belong to many association, so i added it to the JwtWithJtiMatcherUser class to be able to reproduce the problem. Now, when instancing it, it will append a <Module> instance as the first class ancestor. 

The ActiveSupport::Reloader.reload! method wasn't reloading the class on rspec maybe because the code wasn't changed after it was loaded. 
When using reload! method on rails c(which is an short for Rails.application.reloader.reload!) it would reload the class, but it would also reload the entire application and clear the sqlite database, so i remove the JwtWithJtiMatcherUser and reloaded the class file manually so it would force reload this class only.

I've also added some printing of the ancestors so you could see the root of the problem when running rspec. 
![devise_jwt_issue](https://user-images.githubusercontent.com/15388320/90421252-7c628d00-e08f-11ea-8b03-c2e9b8cb768f.png)
As you can see on the image, the instance ancestors[1] is the same as before code reloading, but the class ancestors[1] changed after code reloading.

**Comment by waiting-for-dev** [comment]
Closing in favor of #186
