### ISSUE TITLE
Getting Expected a different algorithm while login

### ISSUE THREAD

**Issue by krishnakumar03** [waiting-for-dev/devise-jwt#184]
## Expected behavior
Login success 

## Actual behavior
Getting 401 Unauthorized with error message 'Expected a different algorithm' 

## Steps to Reproduce the Problem

1. install devise and devise-jwt 
2. mount jwt_authenticatable, jwt_revocation_strategy: JwtBlacklist

Note: If I remove `jwt_authenticatable, jwt_revocation_strategy: JwtBlacklist` then devise `database_authenticatable` is working correctly

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.
Using
devise-jwt - 0.5.9
rails - 6.0.3.2
devise 4.7.2
warden-jwt_auth - 0.3.6

**Devise::JWT.config**
#<#<Class:0x00007fb57880ec08>:0x00007fb57880e820 @config={:secret=>"342ae02050a0bcad6b8dffb7c027a3eaa1800a1d2bae5374855ff7c6bc8d87a54c67c186dbef942fcf733638de599a505d98ba94cad9e4b856ec19b2f30bebf5", :expiration_time=>nil, :dispatch_requests=>[["POST", /^\/api\/v1\/user\/login$/], ["GET", /^\/$/], ["POST", /^\/api\/v1\/user\/login$/], ["POST", /^\/api\/v1\/user\/login.json$/], ["POST", /^\/api\/v1\/user\/signup$/], ["POST", /^\/api\/v1\/user\/signup.json$/]], :revocation_requests=>[["DELETE", /^\/api\/v1\/user\/sign_out$/], ["DELETE", /^\/api\/v1\/user\/logout$/], ["DELETE", /^\/api\/v1\/user\/logout.json$/]], :aud_header=>nil, :request_formats=>{:user=>[nil, :json]}}, @lock=#<Thread::Mutex:0x00007fb57880e7d0>, @defined=true>

**Warden::JWTAuth.config**
#<#<Class:0x00007fb57438d7c8>:0x00007fb57438d5c0 @config={:secret=>"342ae02050a0bcad6b8dffb7c027a3eaa1800a1d2bae5374855ff7c6bc8d87a54c67c186dbef942fcf733638de599a505d98ba94cad9e4b856ec19b2f30bebf5", :expiration_time=>3600, :aud_header=>"JWT_AUD", :mappings=>{:user=>"User"}, :dispatch_requests=>[["POST", /^\/api\/v1\/user\/login$/], ["GET", /^\/$/], ["POST", /^\/api\/v1\/user\/login$/], ["POST", /^\/api\/v1\/user\/login.json$/], ["POST", /^\/api\/v1\/user\/signup$/], ["POST", /^\/api\/v1\/user\/signup.json$/]], :revocation_requests=>[["DELETE", /^\/api\/v1\/user\/sign_out$/], ["DELETE", /^\/api\/v1\/user\/logout$/], ["DELETE", /^\/api\/v1\/user\/logout.json$/]], :revocation_strategies=>{:user=>"JwtBlacklist"}}, @lock=#<Thread::Mutex:0x00007fb57438d570>, @defined=true>

**Devise.mappings** 
{:user=>#<Devise::Mapping:0x00007fb57447dfc0 @scoped_path="users", @singular=:user, @class_name="User", @klass=#<Devise::Getter:0x00007fb57447dbb0 @name="User">, @path="/api/v1/user", @path_prefix=nil, @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:sessions=>"sessions", :registrations=>"registrations", :passwords=>"devise/passwords", :confirmations=>"devise/confirmations"}, @path_names={:registration=>"signup", :new=>"new", :edit=>"edit", :sign_in=>"login", :sign_out=>"logout", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel", :confirmation=>"confirmation"}, @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :confirmable, :jwt_authenticatable], @routes=[:session, :password, :registration, :confirmation], @used_routes=[:session, :password, :registration, :confirmation], @used_helpers=[:session, :password, :registration, :confirmation]>}

**Comment by waiting-for-dev** [comment]
Sorry for the late response. Can you provide what you are sending as `Authorization` header?

**Comment by krishnakumar03** [comment]
This is happening on login API, so I am not sending any authorization header

**Comment by krishnakumar03** [comment]
Hey, Actually not sure, just sat and reinitialized everything now it works fine. Anyway thanks :)
