### ISSUE TITLE
aud getting set to null always and token header doesn't include token type(typ: "JWT")

### ISSUE THREAD

**Issue by vabburi86** [waiting-for-dev/devise-jwt#187]
## Expected behavior
Token payload should have valid "aud" value (non null) or exclude it from payload.
Optional though, it would be good if "typ": "JWT" set in token header.

## Actual behavior
with Revocation strategy Null which is not recommended though, "aud" getting set to null which make invalid JSON format.
## Steps to Reproduce the Problem

1. device-jwt config

2. jwt_revocation_strategy: Devise::JWT::RevocationStrategies::Null
3. generate JWT and decode, 

## Debugging information

Provide the following information. Please, format pasted output as code. Feel free to remove the secret key value.

- 0.8.0 of `devise-jwt` in use
- 6.0 of `rails` in use
- 0.5.0 of `warden-jwt_auth` in use

**Comment by waiting-for-dev** [comment]
`aud` is populated via your requests. Please, see https://github.com/waiting-for-dev/devise-jwt#aud_header

What you get is a ruby hash, which can be converted to a valid `json`.

About `typ`, are you talking about the header or the payload?

**Comment by waiting-for-dev** [comment]
Closing, feel free to add more comments if needed

**Comment by i-Captain** [comment]
I had some "aud": null troubles today ;)

The solution: Nginx needs an extra entry (if you use for example 'JWT_AUD') else nginx is not forwarding header with an underscore.
https://stackoverflow.com/questions/19751313/forward-request-headers-from-nginx-proxy-server

`underscores_in_headers on;`

@waiting-for-dev  thanks for your

**Comment by spencerbart** [comment]
I'm getting `"aud": null`. This should never be able to happen. It's an invalid jwt and it shouldn't be issued.

https://www.rfc-editor.org/rfc/rfc7519#section-4.1.3
