### ISSUE TITLE
JTI issued at registration but not revoked at logout & no new token issued at login

### ISSUE THREAD

**Issue by mcr431** [waiting-for-dev/devise-jwt#19]
As title says, when I register an account it issues a JTI, but it doesn't revoke it upon logout and doesn't issue a new one upon login. I don't really have any idea what could be going wrong or how to debug it.

User Model --
```ruby
class User < ApplicationRecord
    include Devise::JWT::RevocationStrategies::JTIMatcher
    devise :database_authenticatable, :registerable, :omniauthable,
         :confirmable, :recoverable, :trackable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: self
end
```
Devise Initializer --
```ruby
config.jwt do |jwt|
    jwt.secret = Rails.application.secrets.devise_jwt_secret_key
    jwt.expiration_time = 3600
    jwt.revocation_requests = [
        ['DELETE', %r{^/user/sign_out$}],
        ['GET', %r{^/user/sign_out$}],

    ]
    jwt.dispatch_requests = [
        ['POST', %r{^/users/sign_in$}],
    ]
end
```

And when I inspect my network requests, there is no Authorization header, but there are session cookies.

Any help would be appreciated.

**Comment by waiting-for-dev** [comment]
Hi @mcr431 .

Have you followed closely the README instructions? Usually, there is no need to manually configure `dispatch_requests` and `revocation_requests`, as they are automatically detected. At first sight, I think you have some misconfiguration, because in `dispatch_requests` you use the plural resource name (`users`), while in `revocation_requests` you use the singular form (`user`).

Also, you talk about `jti` but you should be concerned about whole `JWT` token. `jti`is just a claim of it, and what you have to provide in the request `Authorization` header is the `JWT`, in form `Bearer #{here_the_token}`.

Please, provide also your `devise_for` configuration in `routes.rb` and detail what workflow you are following to sign in, sign out and authorize (endpoints and request headers, mainly).

**Comment by mcr431** [comment]
Hi @waiting-for-dev, 

Thanks for the response. I did follow the README instructions but I'm a little confused on what this gem does and what it leaves me to do? Do I need to add the token headers myself via some method or should that happen automatically via the Devise set up and Dispatch/Revoke paths in the config settings?

Right now everything is being handled by Devise and I haven't done any custom login/signout logic yet.

Here are my routes:
```ruby
Rails.application.routes.draw do
  devise_for :users

  authenticated do
    devise_scope :user do
      root :to => 'map#index'

      get '/users/sign_out', to: 'devise/sessions#destroy'

      get '/map', to: 'map#index', as: 'map'

      get '/users', to: 'users#index', as: 'users'
      get '/users/:id', to: 'users#show', as: 'user'

      get '/locations/', to: 'locations#index', as: 'locations'
      get '/locations/:id', to: 'locations#show', as: 'location'

      get '/legends', to: 'halloffame#index', as: 'legends'
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: 'devise/registrations#new', :as => 'unauthenticated'
    end
  end
end
```

**Comment by waiting-for-dev** [comment]
> Thanks for the response. I did follow the README instructions but I'm a little confused on what this gem does and what it leaves me to do? Do I need to add the token headers myself via some method or should that happen automatically via the Devise set up and Dispatch/Revoke paths in the config settings?

You have to see at this gem as implementing all the server stuff: dispatching tokens to the client on sign in and revoking them on sign out. The client (usually a rich client javascript application) is responsible on providing the token in the `Authorization` request header. If both your frontend and backend are the same rails application, I don't see the point of using this gem. I guess you would be better off using pure devise and its cookies session.

**Comment by mcr431** [comment]
@waiting-for-dev Okay thanks. Sorry to waste your time

**Comment by waiting-for-dev** [comment]
No problem @mcr431 . Feel free to reopen if you have more doubts.
