### ISSUE TITLE
Request Authenticate in Routes for Constrained Routes

### ISSUE THREAD

**Issue by rmammina** [waiting-for-dev/devise-jwt#191]
## Expected behavior
A route can be constrained via the constraint lambda block. By preventing certain mounted engines like the Resque server from being accessed to by users not logged in or without sufficient access, this is an ideal way to prevent access.

Should be able to access /admin/resque route when logged in and have sufficient permissions. 

## Actual behavior
When running the constraint block, warden doesn't authenticate the user and thus the route /admin/resque isn't accessible even if the user has the JWT payload and the right permissions.

## Steps to Reproduce the Problem
```
# routes.rb

resque_constraint = lambda do |request|
  request.env['warden'].authenticate? and request.env['warden'].user.super_user?
end

constraints resque_constraint do
  mount Resque::Server, :at => "/admin/resque"
end
```

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- Version of `devise-jwt` in use 0.7.0
- Version of `rails` in use 5.2.3
- Version of `warden-jwt_auth` in use 0.4.0

**Comment by waiting-for-dev** [comment]
I haven't used constraints bus as far as I can see all the authentication happens in this line:

```ruby
  request.env['warden'].authenticate? and request.env['warden'].user.super_user?
```
So here you're not dealing at all with devise-jwt nor warden-jwt_auth at all. Probably what you need is to let devise be aware of this route:

https://github.com/heartcombo/devise/wiki/How-To:-Protect-Resque-Web-with-Devise

**Comment by rmammina** [comment]
Hmm, nothing in that article helped out. I tried wrapping the route in the authenticate block:

```
authenticate :user do
  mount Resque::Server.new, :at => "/admin/resque"
end
```

but when stepping through that logic, that calls similar code that I pointed to of trying to authenticate the user.

So you are saying there's no way to run the warden jwt authenticate chain in the routes.rb file? I'm surprised that it's not able to be called by default. 

Please let me know if this isn't possible as I would need to completely remove the devise-jwt gem as this functionality is needed. Thanks for looking into this.

**Comment by waiting-for-dev** [comment]
Sorry not to be able to help further here... devise-jwt just hooks into devise. If devise is supposed to work in a mounted engine thanks to `authenticate` method in the routes file, then devise-jwt will definitely also work. In fact, if you just want to apply the exact same authentication that you use elsewhere, then you don't need a route constraint at all

**Comment by rmammina** [comment]
I have this same functionality working with another project that uses devise with a traditional rails frontend, ie no jwt. The constrained route works properly and devise will authenticate in the routes.rb file. For some reason with the devise-jwt gem it fails to authenticate with warden in routes.rb

I will look into debugging more in depth why this is the case.

**Comment by waiting-for-dev** [comment]
Closing for now, feel free to add more comments if needed
