### ISSUE TITLE
When using cURL, I can see the Authorization header, but using Axios there is no header.

### ISSUE THREAD

**Issue by brlafreniere** [waiting-for-dev/devise-jwt#194]
If I make a raw cURL request to `/users/sign_in`, I get a 302 response with an Authorization header.

If I do the same request with a library like axios from within my react app, it seems to follow the redirect, and the status is 200, and there is no Authorization header.

I've added the "Authorization" header to the list of exposed headers in my CORS config.

My mind is simply boggled as to what the problem could be.

Do I need to disable redirects on successful sign in somehow?

**Comment by waiting-for-dev** [comment]
Hi @brlafreniere ,

changing the client doesn't affect in any way devise-jwt behavior. If your client is following a redirect, then logically the original headers are no longer present. Probably you need to accordingly [configure devise for an API](https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs) to avoid that redirect in the first place.

**Comment by waiting-for-dev** [comment]
Closing for now, feel free to add more comments if needed
