### ISSUE TITLE
Make a request unauthorized from sessions controller in devise-jwt

### ISSUE THREAD

**Issue by flyingboy007** [waiting-for-dev/devise-jwt#195]
I integrated this `devise-jwt` with devise & it's working great. But now I added `2FA` and the response is having issues when `OTP` verification fails. 
I followed this [guide][1] for adding 2FA & tweaked the sessions controller create action like this. 
Here is the sessions controller
The params I receive are email, password & OTP
```
# frozen_string_literal: true

class Api::Customers::V1::Auth::SessionsController < Devise::SessionsController
  def create
    self.resource = warden.authenticate!(auth_options)
    if resource
      if params[:customer][:otp_code_token].size > 0
        if resource.authenticate_otp(params[:customer][:otp_code_token], drift: 60)
          continue_sign_in(resource, resource_name)
          super { @token = current_token } #for token in body as expected by front-end
        else
         # How to throw unauthorized here (devise-jwt)???????????????????????????
          sign_out resource
        end
      end
    end
  end

 
  private

  def current_token
    request.env['warden-jwt_auth.token']
  end

  def continue_sign_in(resource, resource_name)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end


end
```

Above code is working as expected if correct `email`, `password` & `otp` is passed in. But if incorrect `otp` passed in the response the error I get is `200(:ok)` instead of `:unauthorized`. How can we send back unauthorized with custom message(like `otp invalid. Please try again.`)

I know its not a bug. But how to make the response `:unauthorised`??

  [1]: https://www.youtube.com/watch?v=QioeIEkbDrg

**Comment by waiting-for-dev** [comment]
This problem is not related to devise-jwt. Anyway, in your `else` block you're not unauthorizing but just signing out, so probably you need to change there (for instance `head :unauthorized` should work if I'm not wrong).

**Comment by flyingboy007** [comment]
Thank you for your support. Yes, setting head to `: unauthorized ` works for status. But it's still setting the authorization token to the response because the username & password is correct even if the 2FA is incorrect. I know the `devise-jwt `gem is working as expected by setting the token in the authorization header when the devise/warden request succeeds. But as now I added OTP validation How can I make it fail like a wrong password response? I tried setting `response.headers["Authorization"]=nil` but not working and still receiving the bearer token. Sorry for being a complete noob.

**Comment by waiting-for-dev** [comment]
When you do `warden.authenticate!` you are effectively setting the token in the headers. Probably you need to refactor your code so that you only really authenticate when everything is fine, instead of authenticating and later signing out. I think there're some devise 2FA libraries out there that may help you integrate everything.

**Comment by flyingboy007** [comment]
None of the gems on `2FA` are properly maintained. I think writing from scratch is better here than using devise. Anyway, Thank you for trying to help.
