### ISSUE TITLE
Patterns for altering payload

### ISSUE THREAD

**Issue by james-caresnap** [waiting-for-dev/devise-jwt#197]
Is there a recommended pattern for altering the JWT claims payload from rails? `jwt_payload` and `on_jwt_dispatch` appear to be called before the request gets to rails, so it's not possible to make any payload changes there.

It looks like all the token encoding happens in the `after_set_user` hook and none of that machinery looks it has a straightforward public API to call from up in the rails layer.

Just wondering if there's an established pattern here for adding/removing payload claims from up in the rails controller?

**Comment by james-caresnap** [comment]
For some context, I'm trying to add an `amr` claim to indicate whether the user has two-factor-authed or not. I can imagine doing the two-factor check and set in a `prepend_after_set_user` hook so the `jwt_payload` can be prepared before the `devise-jwt` `after_set_user` hook is called, but I'm curious about a more generalized workflow where I want to add arbitrary bits of data to the JWT (outside of an auth flow).

**Comment by waiting-for-dev** [comment]
For now, there's no devise-jwt way to add data from the request (racks's `env`) to the payload. For that you should define a warden hook or a rack's middleware.

`jwt_payload` is used to add information from the user record. For instance, if you are storing whether a user has 2FA enabled in a boolean `has_2fa` field, you could do:

```
class User < ApplicationModel
  def jwt_payload
    { 'arm' => has_2fa }
  end
end
```
