### ISSUE TITLE
White list strategy

### ISSUE THREAD

**Issue by stiig** [waiting-for-dev/devise-jwt#2]
Hello, how about implement whitelist strategy? Where User generate many tokens(I propose jtis) and can authorize only with this tokens

**Comment by waiting-for-dev** [comment]
Hi @stiig . Which is your use case? Why do you need more than one valid token for user? Several devices connected?

**Comment by stiig** [comment]
Yes, several devices, and I think it can improve by add every token several properties. I did it https://gist.github.com/stiig/ab9a0cbeabfad7d633952d55ae9f9dd5 without jwt, but with jwt I think it looks more cool :-)

**Comment by waiting-for-dev** [comment]
I guess that, in order to implement it properly, we would need to add to generated tokens an `aud` claim to identify to which device they belong. In order to do that, I guess request headers should be involved somehow. I'll give it a thought. In the meantime, you can easily implement a custom strategy that serves your specific needs.

**Comment by stiig** [comment]
Okay, thanks!

**Comment by jgonzalezd** [comment]
I think one way that would be easy to implement in postgres would be to use HStore data type for the jti, what do you think?

**Comment by waiting-for-dev** [comment]
I think it's ok @jgonzalezd . Anyway the idea is to provide it out of the box in some way without depending on concrete data store backends.

**Comment by waiting-for-dev** [comment]
Sorry for coming back so late to this thread...

After thinking about this, and for the same reasons stated in https://github.com/waiting-for-dev/devise-jwt/issues/31#issuecomment-321167655, I think it is better not to support it out of the box. The odds are that if we are using this gem with multiple devices we would be better off using a solution with refresh tokens. And, anyway, it is very easy to create a custom revocation strategy to support that in very special cases.

**Comment by waiting-for-dev** [comment]
Finally, it has been implemented in #58. Look at [whitelist strategy](https://github.com/waiting-for-dev/devise-jwt#whitelist)
