### ISSUE TITLE
"tokens are also dispatched on a successful sign up" ?

### ISSUE THREAD

**Issue by toomanyjoes** [waiting-for-dev/devise-jwt#202]
The README mentions briefly "tokens are also dispatched on a successful sign up", I think a little more clarification would be helpful. Does that mean I should expect an Authorization header with Bearer {JWT} in the response to the RegistrationsController create method? I can't think of what else a sign up would mean and if this is the case then this is not the behavior I am seeing in my tests. #confused

Thanks!

**Comment by waiting-for-dev** [comment]
That's exactly what you should expect. If not, please, open a proper issue with all the required debugging information. Cheers.
