### ISSUE TITLE
Using Rspec to test that Authorization header is set on a sign up

### ISSUE THREAD

**Issue by toomanyjoes** [waiting-for-dev/devise-jwt#205]
I am currently unable to get a JWT token in the response headers of a rspec test after a successful **sign_up**.

devise (4.7.3)
devise-jwt (0.8.0)
warden (1.2.9)
warden-jwt_auth (0.5.0)

I think my problem might be that I'm using a controller test in order to validate this. Is it even possible to test that an Authorization header is set on an rspec controller type test? The controller test needs to use the action `#create` instead of the url path. Does this cause jwt dispatcher not to recognize that a jwt should be added to the header on this request?

on the other hand if I use a `type: :request` I no longer have access to the request object to set `request.env['devise.mapping'] = Devise.mappings[:api_v1_user]`

What would be the recommended method for testing this? This is what my test looks like:

```
RSpec.describe Api::V1::RegistrationsController, type: :controller do
  before :each do
    request.env['devise.mapping'] = Devise.mappings[:api_v1_user]
  end
  describe '#create' do
    let!(:valid_attributes) {
      {
        api_v1_user: {
          first_name: 'Natalia',
          last_name: 'Stanton',
          email: 'natalia.stanton@gmail.com',
          password: 'bogus1',
          password_confirmation: 'bogus1'
        }
      }
    }

    it 'should create a new user' do
      expect {
        post :create, format: 'json', params: valid_attributes
      }.to change(User, :count).by(1)

      expect(response.headers).to include('Authorization')
    end
end
```

routes.rb
```
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      devise_for :users, defaults: { format: :json }
    end
  end
end
```

devise.rb:
```
Devise.setup do |config|
.
.
.
  config.jwt do |jwt|
    jwt.secret = ENV.fetch('DEVISE_JWT_SECRET_KEY')
    jwt.dispatch_requests = [
      ['POST', %r{api/v1/users}],
      ['POST', %r{api/v1/registrations}],
    ]
    jwt.request_formats = {
      user: [:json],
    }
  end
end
```

**Expected**
   Authorization {JWT} header in response in rspec test

**Actual**
   No authorization header is set

**Comment by waiting-for-dev** [comment]
The [token is added in a rack middleware](https://github.com/waiting-for-dev/warden-jwt_auth/blob/612f6120573eb43b7d34141e603f6386948b2b0c/lib/warden/jwt_auth/hooks.rb#L62). Controller tests don't go through them so, basically, you have no way. Acknowledging that everything is opinionated, I think it makes no sense to test in your application something that is already tested on `warden-jwt_auth` & `devise-jwt`. What I'd do is to add an integration test with your... well... integration, to check that all pieces are correctly glued.

**Comment by waiting-for-dev** [comment]
Closing for now but feel free to add more comments if needed.
