### ISSUE TITLE
expiration_time: set to never expire

### ISSUE THREAD

**Issue by samuel-loupen** [waiting-for-dev/devise-jwt#206]
If I'm using Null Strategy, how can I set expiration_time to actually not expire?
Tried to set nil, but it does not worked.
As workaround, I'm setting 10 years, but it does not seems right!

**Comment by waiting-for-dev** [comment]
Hi @samuel-loupen , from the README:

> This gem is just a replacement for cookies when these can't be used. As cookies, a token expired with devise-jwt will mandatorily have an expiration time. If you need that your users never sign out, you will be better off with a solution using refresh tokens, like some implementation of OAuth2.

So, I'm sorry to say that's not possible. Cheers.
