### ISSUE TITLE
Devise all_signed_out? returning true every time

### ISSUE THREAD

**Issue by bfsgr** [waiting-for-dev/devise-jwt#208]
Basically when trying to logout from a session with the Authorization header included or not the server rendered me a status 500. Debugging the issue I've found that devise was calling `respond_to` in the wrong context, digging deeper it appears that `all_signed_out?` was returning true when it should be false. The relevant code in the [devise code base](https://github.com/heartcombo/devise/blob/master/app/controllers/devise/sessions_controller.rb):

```ruby
# app/controllers/devise/sessions_controller.rb
  def verify_signed_out_user
    if all_signed_out?
      set_flash_message! :notice, :already_signed_out

      respond_to_on_destroy
    end
  end
```
Anyway, I've managed to workaround the issue overriding `respond_to_on_destroy` to not use respond_to anymore:
```ruby
  def respond_to_on_destroy
    head :no_content
  end
```
After that everything works as expected, tokens get revoked and everything. 

I don't exactly know if the problem is in devise or devise-jwt code base. that's why I opened this issue here too, since there's also an open issue in [their repos](https://github.com/heartcombo/devise/issues/5267)

## Expected behavior
/sign_out to work out-of-the-box with devise-jwt
## Actual behavior
Error 500 due to devise calling respond_to

## Steps to Reproduce the Problem

1. Generate a token with sign_in path
2. Try to destroy the session in sign_out path
3. You should get an internal server error

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- Version of `devise-jwt` in use `0.8.1`
- Version of `rails` in use `6.1.3`
- Version of `warden-jwt_auth` in use `0.5.0`
- Output of `Devise::JWT.config`
```ruby
#<Dry::Configurable::Config values={:secret=>"[REDACTED]", :expiration_time=>86400, :dispatch_requests=>[["POST", /^\/api\/user\/sign_in$/], ["POST", /^\/api\/user$/]], :revocation_requests=>[["DELETE", /^\/api\/user\/sign_out$/]], :aud_header=>"JWT_AUD", :request_formats=>{}}>
```
- Output of `Warden::JWTAuth.config`
```ruby
#<Dry::Configurable::Config values={:secret=>"[REDACTED]", :algorithm=>"HS256", :expiration_time=>86400, :aud_header=>"JWT_AUD", :mappings=>{:user=>User (call 'User.connection' to establish a connection)}, :dispatch_requests=>[["POST", /^\/api\/user\/sign_in$/], ["POST", /^\/api\/user$/]], :revocation_requests=>[["DELETE", /^\/api\/user\/sign_out$/]], :revocation_strategies=>{:user=>User (call 'User.connection' to establish a connection)}}> 
```
- Output of `Devise.mappings` 
```ruby
{:user=>#<Devise::Mapping:0x0000000004742878 @scoped_path="users", @singular=:user, @class_name="User", @klass=#<Devise::Getter:0x0000000004741f18 @name="User">, @path="user", @path_prefix="/api", @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:sessions=>"users/sessions", :registrations=>"devise/registrations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :sign_up=>"sign_up", :cancel=>"cancel"}, @modules=[:database_authenticatable, :registerable, :validatable, :jwt_authenticatable], @routes=[:session, :registration], @used_routes=[:session, :registration], @used_helpers=[:session, :registration]>}
```

**Comment by waiting-for-dev** [comment]
Hey, thanks for sharing all the information. However, it isn't a `devise-jwt` issue, as it only hooks into devise behavior but it doesn't mess with its internals at all. Probably your issue is related to having the wrong configuration of a Devise for an API. Maybe you can find some help looking at our [wiki page on configuring Devide for APIs](https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs). Good luck!
