### ISSUE TITLE
Not able to setup secret

### ISSUE THREAD

**Issue by Bdoom** [waiting-for-dev/devise-jwt#213]
![image](https://user-images.githubusercontent.com/1284431/119886472-03874000-bf01-11eb-9b8a-7d2b62e03bf2.png)

When I setup the system in devise.rb initializer like you wrote, I get this error:
![image](https://user-images.githubusercontent.com/1284431/119886544-16017980-bf01-11eb-9245-cf2ba6e35520.png)

![image](https://user-images.githubusercontent.com/1284431/119886590-1ef24b00-bf01-11eb-86f5-73ca5d9ed387.png)

**Comment by Bdoom** [comment]
Please ignore this, I'm stupid lol

**Comment by Bdoom** [comment]
This does not work...

```
config.jwt do |jwt|
    jwt.secret = ''
end```

**Comment by waiting-for-dev** [comment]
Hi @Bdoom . Please, if you're experiencing any issue open a new issue filling it the bug report template. It will make it much easier to provide help. Thanks.
