### ISSUE TITLE
No AUD Header?

### ISSUE THREAD

**Issue by Bdoom** [waiting-for-dev/devise-jwt#215]
![image](https://user-images.githubusercontent.com/1284431/119996619-ed2ec200-bf9c-11eb-80d2-e71b5f04d1ee.png)

Why is there no AUD header?

**Comment by waiting-for-dev** [comment]
Hi @Bdoom . Please, if you're experiencing any issue open a new issue filling it the bug report template. It will make it much easier to provide help. Thanks.
