### ISSUE TITLE
The token is not being stored in the Denylist?

### ISSUE THREAD

**Issue by Bdoom** [waiting-for-dev/devise-jwt#216]
![image](https://user-images.githubusercontent.com/1284431/120007030-7d720480-bfa7-11eb-87ac-f38c17489d2c.png)
The token is not being stored in the Denylist?

**Comment by waiting-for-dev** [comment]
Hi @Bdoom . Please, if you're experiencing any issue open a new issue filling it the bug report template. It will make it much easier to provide help. Thanks.
