### ISSUE TITLE
dispatch requests not working for me

### ISSUE THREAD

**Issue by adnanmirza1** [waiting-for-dev/devise-jwt#217]
In my devise.rb config, i have added dispatch request like this: 
 
 jwt.dispatch_requests = [
      ['POST', %r{^/api/v1/users/sign_in$}],
   
    ]
    
    still i'm not receiving token on this request.

**Comment by waiting-for-dev** [comment]
Please, open a new issue filling the bug template report that is rendered with all the debugging information. Thanks.
