### ISSUE TITLE
Dispatch request not sending me token when i login from api

### ISSUE THREAD

**Issue by adnanmirza1** [waiting-for-dev/devise-jwt#218]
When i login with simple login, I'm receiving the token but i have made another login for API
when i login through it, i'm able to login  but i'm not receiving jwt token with it.
In my dispatch request in devise config, i have added the path as well. still i'm not receiving the token.
Here's the screenshot of devise config:
![image](https://user-images.githubusercontent.com/58806552/121489355-71e1fd00-c9ed-11eb-800b-060db4ba455a.png)

And here's the screenshot of my routes for user

![image](https://user-images.githubusercontent.com/58806552/121489553-9fc74180-c9ed-11eb-9100-e6133d8eecf4.png)

**Comment by tashi-179** [comment]
No need to give a full start and end URL for the dispatch request. Just try with below code and you are good to go.
```ruby
jwt.dispatch_requests = [
    ['POST', /sign_in/]
]
```

**Comment by adnanmirza1** [comment]
I tried it but still i'm not receiving the token

**Comment by tashi-179** [comment]
And also make sure to have following code inside your `user` model.

```ruby 
devise(
    :jwt_authenticatable,
    :database_authenticatable,
    jwt_revocation_strategy: self
)
```

**Comment by adnanmirza1** [comment]
devise(
    :jwt_authenticatable,
    :database_authenticatable,
    jwt_revocation_strategy: JwtDenyList
)


Instead of self i have JwtDenyList

**Comment by tashi-179** [comment]
That's fine. It should work. For me, I didn't have any relations for `deny_list` so using the same `user` table.

**Comment by adnanmirza1** [comment]
I tried both none is working

**Comment by waiting-for-dev** [comment]
Hi @adnanmirza1 , I need the debugging information that is requested on the bug report template to be able to help you.

**Comment by adnanmirza1** [comment]
These are my routes:

![image](https://user-images.githubusercontent.com/58806552/121531375-c69a6d80-ca17-11eb-9ec9-91f0d52129cc.png)


i think problem is here somewhere
it's giving me proper response with token in my
users/sign_in
but not giving it to me in
api/v1/users/sign_in

**Comment by adnanmirza1** [comment]
Adding routes like that gives me following error:
![image](https://user-images.githubusercontent.com/58806552/121639892-a239a200-caa6-11eb-9653-b49ba32b7415.png)

**Comment by tashi-179** [comment]
Ah yes. You have already defined `devise_for`. We cannot define twice. What you can do is, now you have to use `as` keyword like below.

```ruby
scope 'api/v1' do
    devise_scope :user do
        get 'users/sign_in' => 'sessions#new', as: :new_user_session
        post 'users/sign_in' => 'sessions#create', as: :user_session
        delete 'users/sign_out' => 'sessions#destroy', as: :destroy_user_session
    end
end
```

**Comment by adnanmirza1** [comment]
It still gives me this error that new_user_session is already in used
![image](https://user-images.githubusercontent.com/58806552/121641289-6ef81280-caa8-11eb-8f28-d0a70babb6c6.png)

**Comment by adnanmirza1** [comment]
@waiting-for-dev what else do you need from my side to help me?

**Comment by tashi-179** [comment]
Please share your route file.

**Comment by adnanmirza1** [comment]
These are my complete routes related to this:
![image](https://user-images.githubusercontent.com/58806552/121662069-5692f280-cabe-11eb-9198-5ef6b36fee7d.png)

**Comment by adnanmirza1** [comment]
Just copied your routes and pasted in mine and now it's working.
Thank You so much for all the help. <3

**Comment by puneetpandey** [comment]
This can also be added to README for the cases where devise is configured for both Web and API in a single application
