### ISSUE TITLE
ActiveRecord::SubclassNotFound (Invalid single-table inheritance type) after file change

### ISSUE THREAD

**Issue by alfie-max** [waiting-for-dev/devise-jwt#22]
Ref : https://github.com/rails/rails/issues/29542

I'm creating this issue as response from the rails team and further investigating the issue seems that the model is not reloaded and hence the error. 

This is detailed in the issue i have created in the rails repo.

**Comment by waiting-for-dev** [comment]
Hi @alfie-max . What makes you think that the root of your issue is in `devise-jwt`?

**Comment by alfie-max** [comment]
Firstly, using just devise doesn't cause this issue. (web authentications)

Then there is this : https://github.com/waiting-for-dev/devise-jwt/blob/master/lib/devise/jwt/models/jwt_authenticatable.rb#L19

Here the `self` object is not getting updated after a code change.

**Comment by waiting-for-dev** [comment]
I still don't understand which is the issue. Could you please elaborate it more and, if you know it, point to the solution? 

> Here the self object is not getting updated after a code change.

What do you mean by this? There `self` refers to the `ActiveRecord::Base` subclass, not to any instance.

Also, I don't see `devise-jwt` in the backtrace you pasted in the rails issue.

**Comment by alfie-max** [comment]
This method `find_for_jwt_authentication` seems to be called on every request whenever `authenticate_Trader!` is called, but this binding only happens the first time the app is loaded, and hence the self.object_id is different, 
and hence the `self == subclass` equality fails here :
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/inheritance.rb#L201

I'm trying to find a fix, but i have no clue on where to get started with

**Comment by alfie-max** [comment]
@waiting-for-dev do you see what i see?

**Comment by waiting-for-dev** [comment]
Rails autoloading is quite famous to be the source of a lot of issues, particularly with STI.

Maybe you can solve your issue following their recommendation:

http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-sti

**Comment by alfie-max** [comment]
Hi, wasn't able to get back to this till now. So i checked out the link you shared. But it's not that the class is not available during that time. Its that what this gem has already loaded is not getting reloaded along with when rails reloads the classes when a code change is detected.

**Comment by redtachyons** [comment]
I tried to find the cause of this issue, Here we are storing model mappings in ```JWT.config.mappings``` this configuration is not auto loaded and will remain the same for entire lifespan of the app. But the actual model will reload and will have new class with same name but with different object_id.

Eg

model `Trader` is loaded is object id 1
`JWT.config.mappings` will be `{:trader => Trader()}`
Now once the app is reloaded in file change, `Trader` will get reloaded and get new id 2.

But devise jwt will be still using old model which is cached inside mappings hash. So the equality comparison fails

I am not sure about which gem is to be fixed

- If it is devise-jwt gem, then we have to make config hash compatible with autoload
- If it is active record, then we have to change comparison logic, from object_id to model name

**Comment by alfie-max** [comment]
Got an advice from @matthewd that instead of storing the mapping as a class instance why don't we store the class name. So that when required we can call the class instance from there?

**Comment by waiting-for-dev** [comment]
Hey @alfie-max & @redtachyons ,

do you have in mind following with PR https://github.com/waiting-for-dev/warden-jwt_auth/pull/5 & https://github.com/waiting-for-dev/devise-jwt/pull/24 ? I'm waiting for some feedback in the first one from @alfie-max . If not, please tell me so I can assign them to myself and work on them when I find the time.

Thanks

**Comment by alfie-max** [comment]
It would be good if you could take a look, but i'm still looking into this and wish to get this fixed, but recently haven't been able to find the time for it.

**Comment by waiting-for-dev** [comment]
Fixed in `0.4.4`
