### ISSUE TITLE
Error When trying to create app using template

### ISSUE THREAD

**Issue by chrisgeek** [waiting-for-dev/devise-jwt#231]
When I run `rails new app_name -m path/to/template.rb`, I get this error when trying to run `rails generate devise:install`
```<module:Devise>' [dry-configurable] passing a constructor as a block is deprecated and will be removed in the next major version
Provide a `constructor:` keyword argument instead
```
I think it is coming from your version of devise-jwt 0.7.0 which had a major change after it. 

Rails:  6.0
Ruby: 2.6.3

**Comment by chrisgeek** [comment]
Wrong repo

**Comment by waiting-for-dev** [comment]
It was an issue with dry-configurable. Please, update to devise-jwt 0.9.0.

**Comment by chrisgeek** [comment]
@maysam, It wasn't a devise issue.
