### ISSUE TITLE
Auto removal of expired jwt token from AllowList table

### ISSUE THREAD

**Issue by hafsabatool7** [waiting-for-dev/devise-jwt#238]
## Expected behavior
When a token is expired on the basis of expiry time configured, it should be also be removed from AllowList table. Maybe a functionality of the sort that when a revoked token is identified in `jwt_revoked?`, it removes the expired token.

## Actual behavior
Upon accessing a revoked token (expired), the invalid token is not removed from the AllowList table.

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- `devise-jwt` 0.8.1
-`rails` 6.0.3.2
- `warden-jwt_auth` 0.5.0

**Comment by waiting-for-dev** [comment]
Hey, that's something that makes sense, but it's out of the scope of this library. Users should create their cleaning tasks, which can vary a lot depending on their preferences.
