### ISSUE TITLE
Devise Resource not Authenticated 

### ISSUE THREAD

**Issue by ror-vs** [waiting-for-dev/devise-jwt#242]
I am using devise-jwt gem for token-based authentication for multiple resources. The problem that I am facing is that, even without providing the emails and password for the resource, the resource is logged  in without authenticating.

Expected behavior

the resource should be authenticated before login

 Actual behavior

the resource is logged in without authentication

In devise.rb initializer I have
![image](https://user-images.githubusercontent.com/92923983/163110183-03c27ff3-c448-43e2-bc46-e52903d3d839.png)

in my routes i have 

![image](https://user-images.githubusercontent.com/92923983/163110536-08959e50-852e-4b00-98c8-4b7e252aabe4.png)
![image](https://user-images.githubusercontent.com/92923983/163110582-4be83ffe-036d-4f70-8434-10f75f733a2f.png)
![image](https://user-images.githubusercontent.com/92923983/163110635-d34ca69b-3aa4-4d77-85da-f7d97547c83a.png)

My session controllers for the resources are as follows: 

![image](https://user-images.githubusercontent.com/92923983/163110763-830c78ef-ea18-4b6c-9396-8de44f183377.png)
![image](https://user-images.githubusercontent.com/92923983/163110840-2e1aa5cc-f608-4dcf-8a9d-9009293885c6.png)

Here is a snap from the login api where password is not provided but it has logged in th client

![image](https://user-images.githubusercontent.com/92923983/163111053-8ae545d1-d453-4fc1-86c8-308d64c39ef6.png)

**Comment by waiting-for-dev** [comment]
Probably related to https://github.com/waiting-for-dev/devise-jwt#session-storage-caveat

**Comment by ror-vs** [comment]
> Probably related to https://github.com/waiting-for-dev/devise-jwt#session-storage-caveat

it worked. Thanks

**Comment by ror-vs** [comment]
is there a way we can create the custom token for the resources which are not being created from devise?
my test case is I am decoding the info from google token and then saving it backend. is it possible to create a token for it?

**Comment by waiting-for-dev** [comment]
No, this is an extension for Devise. Probably you'll need to manually do something with https://github.com/jwt/ruby-jwt
