### ISSUE TITLE
[Question] Does the login function add jti value on existing database ?

### ISSUE THREAD

**Issue by pribadi1st** [waiting-for-dev/devise-jwt#247]
Hi i already have a database with rails API, and want try to implement devise jwt.
my question is, if i already have a database with null value on jti column, does devise-jwt automatically update and fill the jti column if its null ? because on sign up function, the jti column is filled with the expected result

## Expected behavior
JTI column is updated when user log in using existing data before devise-jwt is implemented

## Actual behavior
<img width="604" alt="image" src="https://user-images.githubusercontent.com/26956664/175784266-e4c813ac-2f59-4392-a0e7-56ba0390b596.png">

- first row is user when login, jti column is still null 
- second row is when user register, jti column is not null (correct)

my devise configuration
<img width="600" alt="image" src="https://user-images.githubusercontent.com/26956664/175784601-c6f488aa-40e8-4970-840e-1f9406ea45b6.png">

Thank you

**Comment by waiting-for-dev** [comment]
Yes, it should also be updated in login. Are you sure you are requesting against `/login`?

**Comment by pribadi1st** [comment]
yes, i do receive the token on the header,

i read on https://www.rubydoc.info/gems/devise-jwt/0.4.0 documentation, that if we already have our own database records, we have to create a migration to update the data first, so it wont be a null value.

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/26956664/175809095-84bbe1e2-6937-4eed-8727-78077f42c7a6.png">

so should it be done like this ?

**Comment by waiting-for-dev** [comment]
We recommend setting an initial random `jti` value in the column so that you can add a `NOT NULL` index in the database. But that's not required for the logic at the application layer.

It'd be great if you could paste all the debugging information we ask when you open an issue. It'll be easier to help you.

**Comment by pribadi1st** [comment]
sure i'd love to, but i'm not sure which one should i debug.

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/26956664/175832245-0d6d158c-d8f4-4066-88e5-e9c8bc716824.png">
- this one above is when user hit the /login end point

- Version of `devise-jwt` in use: 0.9.0
- Version of `rails` in use: rails 7.0.0
- Version of `warden-jwt_auth` in use: Devise::JWT.config
- output of Devise::JWT.config
<img width="1414" alt="Bildschirmfoto 2022-06-26 um 22 21 28" src="https://user-images.githubusercontent.com/26956664/175832467-ccc48be7-9936-4304-8370-abb0b6021de3.png">
- Output of `Warden::JWTAuth.config`
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26956664/175832572-7595ee07-ddec-4fd7-b815-4029e94d166d.png">

**Comment by waiting-for-dev** [comment]
Thanks. Looks legit. Could you paste your user model code (at least the relevant part for `devise-jwt`?

**Comment by pribadi1st** [comment]
here is my user model
<img width="631" alt="image" src="https://user-images.githubusercontent.com/26956664/175877475-d522c6ef-14d3-416d-aa8f-838518cfbe0a.png">

hope it helps

**Comment by waiting-for-dev** [comment]
Yeah, it looks ok. I'm out of suggestions at this point. If you can create a repository reproducing the issue with a minimal setup, I'll happily look into it.
