### ISSUE TITLE
Wouldn't blacklist table just keep growing?

### ISSUE THREAD

**Issue by jcavalieri** [waiting-for-dev/devise-jwt#25]
Question about blacklist revocation strategy. From the readme it looks like that would be a table that would grow and would need occasional deleting. To assist cleaning out that table would it be useful to add the token's expiration along with the JTI?

I know I can have a custom strategy, just thought I would pose the question to see if that might be an enhancement to consider.

Thanks,
John

**Comment by waiting-for-dev** [comment]
Hi @jcavalieri .

Yeah, the blacklist table would keep growing until some clean-up is done. The idea I had for this, which [I wrote in an article linked in the README](http://waiting-for-dev.github.io/blog/2017/01/24/jwt_revocation_strategies/), was to, from time to time, empty the blacklist table at the same time that the signature key (`jwt.secret`) is changed. Of course, that would sign out every user in the system, but it is something usually we can afford as it doesn't need to happen very often.

But, as you say, adding the expiration time to the table would be a better solution as it would allow us to only clean all expired tokens and let all active users still signed in.

So yes, I would be happy to add this enhancement. I will start with it as soon as I have the time, or if you prefer not to wait you can submit a pull request.

Thanks!

**Comment by jcavalieri** [comment]
@waiting-for-dev, I take a stab at a PR. I'll try to have something in the next day or two.

**Comment by jcavalieri** [comment]
I totally blanked on this. This is back on my TODO list.

**Comment by waiting-for-dev** [comment]
Ok @jcavalieri :) Let me know if you need some help

**Comment by jcavalieri** [comment]
Just submitted a PR: https://github.com/waiting-for-dev/devise-jwt/pull/28

Let me know what you think.

**Comment by waiting-for-dev** [comment]
Closed via PR #28

**Comment by jcavalieri** [comment]
Thanks @waiting-for-dev. All the best. :-)
