### ISSUE TITLE
No content while trying to validate reset_password_token to recover password

### ISSUE THREAD

**Issue by Vicapelli** [waiting-for-dev/devise-jwt#258]
When i click to get password reset instructions i receive an email  with the link that has the token to reset. This link is a get request to #edit endpoint in passwords_controller but it returns me "204 no content" and when i try directly to #update endpoint passing the token in params with the password and password_confirmations i am able to reset my password with status 200.

**To Reproduce**

request that has been made: http://localhost:3000/users/password/edit?reset_password_token=v7Xi4Jo7vz6KJefTysGK

response: Processing by Devise::PasswordsController#edit as JSON
                  Parameters: {"reset_password_token"=>"[FILTERED]"}
                Completed 204 No Content in 32ms (ActiveRecord: 3.8ms | Allocations: 36023)

Should i make a first request to #edit or i can simply make a request #put with the new password parameters?

**Comment by waiting-for-dev** [comment]
Sorry, but this issue is with Devise itself, not with this extension. Please, feel free to open a new report if you have something pointing here.
