### ISSUE TITLE
There is an issue with the handling of the `Authorization`

### ISSUE THREAD

**Issue by amanullahtanweer** [waiting-for-dev/devise-jwt#269]
There is an issue with the handling of the `Authorization` header in the `devise-jwt` gem. The gem currently expects the header to be `authorization` (with a lowercase "a"), which is incorrect. According to the HTTP specification, headers are case-insensitive, but the standard convention is to use `Authorization` with a capital "A".

**Comment by waiting-for-dev** [comment]
Can you create a bare minimum repository reproducing the issue?

**Comment by waiting-for-dev** [comment]
Closing for now. Please, provide the repository reproductin the issue if it's still a problem.
