### ISSUE TITLE
version 0.12.0 does not properly add support for issuer and token_header

### ISSUE THREAD

**Issue by chaadow** [waiting-for-dev/devise-jwt#272]
@waiting-for-dev  Hi, in this commit: https://github.com/waiting-for-dev/devise-jwt/commit/1c4de3d28eaf286a0d13c6d85695b56ebedcc856

you updated the dependency but you still need to add code like this:
```ruby
    setting(:issuer,
            default: Warden::JWTAuth.config.issuer,
            constructor: ->(value) { forward_to_warden(:issuer, value) })
```

in the same vein as this open PR: https://github.com/waiting-for-dev/devise-jwt/pull/271

**Comment by waiting-for-dev** [comment]
Thanks!! I forgot how my own gem works 🙂 Fixed in v0.12.1
