### ISSUE TITLE
Feature Request: Optional Configuration to Exclude JWT from Authorization Header

### ISSUE THREAD

**Issue by Eknopp** [waiting-for-dev/devise-jwt#277]
Hi,

I’m currently using cookies to store the JWT token instead of relying on local/session storage. This approach enhances security by mitigating the risk of XSS attacks since the token isn’t exposed to JavaScript.

However, I noticed that the JWT token is still included in the Authorization header of successful responses by default. Since I’m not using the token from the header, I’d like to remove it to avoid redundant data transmission and ensure the response is as minimal as possible.

I couldn’t find an option in the documentation to disable the inclusion of the token in the Authorization header. If this functionality already exists, I’d greatly appreciate guidance on how to configure it.

If not, I’d like to suggest adding an optional configuration that allows users to exclude the JWT from the Authorization header. This flexibility would benefit developers who are using alternative storage mechanisms like cookies while maintaining compatibility with Devise-jwt.

Thank you for considering this feature request,

Note: The feature request link sent me to a page which I am not sure is the correct place regarding devise-jwt, therefore I sent this request here. If it's the wrong place, I would be glad to be redirected to where this discussion should be.

Best regards,
Eitan

**Comment by waiting-for-dev** [comment]
Hey @Eknopp, I think in that case you can [leverage `waden-jwt_auth`](https://github.com/waiting-for-dev/warden-jwt_auth) better than `devise-jwt`. Let me know if that works.

**Comment by Eknopp** [comment]
Hi @waiting-for-dev, thanks for the quick reply.

I already made adjustments to saving a JWT into an httpOnly cookie which fits well with devise-jwt.
Since removing the JWT token from the headers is not one of my primary goals at the moment, I will probably not be trying to readjust my configuration to a different library.
If I do at some point, I will let you know how it went.

Thanks anyway for the advice,
Eitan

**Comment by waiting-for-dev** [comment]
Hey @Eknopp , `warden-jwt_auth` is the underlying library under `devise-jwt` (your project is already using it). There you have functions like [encoding a user into a token](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/user_encoder.rb) or [deconding from it](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/user_decoder.rb) that are helpful for more tailored flows. Hope that helps you at some point :) I'll close this one as `devise-jwt` is all about streamlining for devise
