### ISSUE TITLE
Generate token manually

### ISSUE THREAD

**Issue by hudadiaz** [waiting-for-dev/devise-jwt#3]
Can I generate token manually to pass it to users?

**Comment by waiting-for-dev** [comment]
For this, you have to rely on the underlying library [warden-jwt_auth](https://github.com/waiting-for-dev/warden-jwt_auth):

```ruby
Warden::JWTAuth::User.encoder.call(user, scope)
```

**Comment by hudadiaz** [comment]
There's no Class `User` found. However, I could find `UserEncoder`, but trying to invoke `call` gives `undefined method 'call' for Warden::JWTAuth::UserEncoder:Class Did you mean? caller`.

**Comment by hudadiaz** [comment]
`Warden::JWTAuth::UserEncoder.new.call(user, scope)` doing this returns the token.

**Comment by waiting-for-dev** [comment]
Yep, sorry, I made a typo in the example. If everything is clear, I'm going to close this issue. Feel free to reopen if you have any other doubt.

**Comment by waiting-for-dev** [comment]
It is documented in the README:

https://github.com/waiting-for-dev/devise-jwt#aud_header

**Comment by jackpope** [comment]
I am trying to use this solution to create a token refresh endpoint. If users tokens are near expiration, this endpoint will automatically be hit in order to keep them signed in. I am successfully getting back a new token, but when I put that in the Authorization header for the next request it doesn't authenticate.

Endpoint code:

```ruby
def create
    if user_signed_in?
      json_response({
        token: Warden::JWTAuth::UserEncoder
          .new
          .call(current_user, :users, nil)
          .first
      })
    else
      json_response({
        message: '401 - Unauthorized'
      }, :Unauthorized)
    end
  end
```

How is a User record associated with a token?

**Comment by waiting-for-dev** [comment]
Second argument of `#call` is devise scope. Probably it's `:user`. But keep in mind that this library is not intended to provide refresh tokens and that probably you'd be better off with something like OAuth2.
