### ISSUE TITLE
Omniauth Support? 

### ISSUE THREAD

**Issue by brianlaw033** [waiting-for-dev/devise-jwt#32]
Does this support Omniauth at the moment? Or is this planned?

**Comment by waiting-for-dev** [comment]
No, it doesn't support Omniauth and it is beyond its scope. This gem tries to be a simple but secure cookies replacement where they can't be used, for example for a web application with a single client which is a web frontend in another domain. You can use [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) for OmniAuth.
