### ISSUE TITLE
Authorization header is not being returned

### ISSUE THREAD

**Issue by yhchun1992** [waiting-for-dev/devise-jwt#34]
I have set up devise and devise-jwt on a new rails project just to test this out.
When I POST to /users/sign_in
the response headers does not include an Authorization header, but the post request succeeds

The result I get shown in postman:
![screen shot 2017-08-24 at 2 50 39 pm](https://user-images.githubusercontent.com/2120676/29647427-41648422-88dd-11e7-9381-935189f399b8.png)

I am using the null revocation strategy
models/user.rb
![screen shot 2017-08-24 at 3 05 10 pm](https://user-images.githubusercontent.com/2120676/29647523-a6c8b6d0-88dd-11e7-8973-f4713858bb5e.png)

devise.rb
![screen shot 2017-08-24 at 3 07 23 pm](https://user-images.githubusercontent.com/2120676/29647583-f8336ef2-88dd-11e7-9c35-c3505f57a22c.png)

application.rb
![screen shot 2017-08-24 at 3 11 23 pm](https://user-images.githubusercontent.com/2120676/29647676-84beb048-88de-11e7-825b-97687828a4ae.png)

**Comment by waiting-for-dev** [comment]
If you have `:json` in `request_formats`, then the token will be dispatched if you request `/users/sign_in.json`. If you want to use `/users/sign_in` just remove `request_formats`.
