### ISSUE TITLE
Authorization header is not being returned

### ISSUE THREAD

**Issue by russellvaughan** [waiting-for-dev/devise-jwt#37]
I'm scratching my head with this one and have seen people have had similar issues. I wondering if these doesn't work if you have Devise custom controllers.  Here is my code (I've omitted some details for brevity) 

config/initializers/devise.rb
```  
config.jwt do |jwt|
  jwt.secret = 'c6977142e3d968eb45a955b89b095f55cc8e2640e159682d6a49bfe3c0c2a937a6f4420a181e962dd0cb64233b93756ad34fd6dc8a311d2045b5c06bcbc828e6'
  jwt.request_formats = {
                        landlord: [:json],
                      }
  jwt.dispatch_requests = [
                          ['POST', %r{^/api/lanlords/sign_in.json$}]
                        ]
  end
```
config/routes.rb
```
devise_for :landlords, defaults: { format: :json }, :controllers => {:sessions => "landlords/sessions"},
:path => '/api/landlords'
```

config/application.rb
```
class Application < Rails::Application
      config.middleware.insert_before 0, Rack::Cors do
       allow do
    origins "localhost:3000", "127.0.0.1:3000", "*"
    resource "*",
      :headers => :any,
      :expose  => [
        "X-Requested-With",
        "Content-Type",
        "Authorization",
        "Accept",
        "Client-Security-Token",
        "Accept-Encoding",
        "iat",
        "exp",
        "jti"
      ],
      :methods => [:get, :post, :options, :delete, :put, :head]
  end

```

gemfile

```
gem 'devise'
gem 'devise-jwt', '~> 0.3.0'
```

request 

<img width="671" alt="screen shot 2017-08-31 at 07 23 10" src="https://user-images.githubusercontent.com/16154072/29909376-71390d7c-8e1d-11e7-935d-93be52d17a6c.png">

**Comment by waiting-for-dev** [comment]
If you configure `dispatch_requests` regexp to end with `.json`and, at the same time, configure `request_formats` as `:json`, it means that the matched URL will be `*.json.json`. Just remove `dispatch_requests` configuration, as it is automatically configured for a regular sign in, and it should work.

**Comment by russellvaughan** [comment]
I have tried with either. Just dispatch_requests and just with request_formats. 
I really liked your blog posts and the logic you used to approach building this gem. It's exactly what I'm after but I just can't seem to get it working!

Definitely nothing wrong with the using the path "api/landlords/sign_in.json' rather than just "/landlords/sign_in.json"

 ```jwt.dispatch_requests = [
                          ['POST', %r{^/api/lanlords/sign_in.json$}]
                        ]```

**Comment by waiting-for-dev** [comment]
Please, try with just:

```ruby
config.jwt do |jwt|
  jwt.secret = 'c6977142e3d968eb45a955b89b095f55cc8e2640e159682d6a49bfe3c0c2a937a6f4420a181e962dd0cb64233b93756ad34fd6dc8a311d2045b5c06bcbc828e6'
  jwt.request_formats = {
                        landlord: [:json],
                      }
  end
```

```ruby
devise_for :landlords, defaults: { format: :json }, :controllers => {:sessions => "landlords/sessions"}, :path => '/api/landlords'
```

Then, request `sign_in.json` and copy here the response headers.

Then, also copy the output of:

```ruby
Warden::JWTAuth.config
Devise::JWT.config
Devise.mappings
```

**Comment by russellvaughan** [comment]
Have tried the above. Still the same result.

Headers:

>>>Access-Control-Allow-Credentials →true
Access-Control-Allow-Methods →GET, POST, OPTIONS, DELETE, PUT, HEAD
Access-Control-Allow-Origin →file://
Access-Control-Expose-Headers →X-Requested-With, Content-Type, Authorization, Accept, Client-Security-Token, Accept-Encoding, iat, exp, jti
Access-Control-Max-Age →1728000
Cache-Control →max-age=0, private, must-revalidate
Content-Type →application/json; charset=utf-8
ETag →W/"c955e57777ec0d73639dca6748560d00"
Transfer-Encoding →chunked
Vary →Origin
X-Content-Type-Options →nosniff
X-Frame-Options →SAMEORIGIN
X-Request-Id →94268d85-e14e-477e-99d0-4901ebf7265e
X-Runtime →0.486319
X-XSS-Protection →1; mode=block

```2.2.2 :001 > Warden::JWTAuth.config
 => #<#<Class:0x007fa8a8ed9538>:0x007fa8a8ed8d40 @config={:secret=>"c6977142e3d968eb45a955b89b095f55cc8e2640e159682d6a49bfe3c0c2a937a6f4420a181e962dd0cb64233b93756ad34fd6dc8a311d2045b5c06bcbc828e6", :expiration_time=>3600, :mappings=>{:landlord=>Landlord (call 'Landlord.connection' to establish a connection)}, :dispatch_requests=>[["POST", /^\/\/api\/landlords\/sign_in.json$/], ["POST", /^\/\/api\/landlords.json$/]], :revocation_requests=>[["DELETE", /^\/\/api\/landlords\/sign_out.json$/]], :revocation_strategies=>{:landlord=>Devise::JWT::RevocationStrategies::Null}}>```


```2.2.2 :002 > Devise::JWT.config
 => #<#<Class:0x007fa8a8a20488>:0x007fa8a8a1b4d8 @config={:secret=>"c6977142e3d968eb45a955b89b095f55cc8e2640e159682d6a49bfe3c0c2a937a6f4420a181e962dd0cb64233b93756ad34fd6dc8a311d2045b5c06bcbc828e6", :expiration_time=>nil, :dispatch_requests=>nil, :revocation_requests=>nil, :request_formats=>{:landlord=>[:json]}}>```

```2.2.2 :003 > Devise.mappings
 => {:landlord=>#<Devise::Mapping:0x007fa8a7b33f38 @scoped_path="landlords", @singular=:landlord, @class_name="Landlord", @klass=#<Devise::Getter:0x007fa8a7b339e8 @name="Landlord">, @path="/api/landlords", @path_prefix=nil, @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:sessions=>"landlords/sessions", :passwords=>"devise/passwords", :registrations=>"devise/registrations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel"}, @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :trackable, :jwt_authenticatable], @routes=[:session, :password, :registration], @used_routes=[:session, :password, :registration], @used_helpers=[:session, :password, :registration]>}```

**Comment by waiting-for-dev** [comment]
Try removing the trailing `/` in your `path` option in `devise_for`. So, change `:path => '/api/landlords'` for `:path => 'api/landlords'`

**Comment by russellvaughan** [comment]
no luck unfortunately ;(

**Comment by waiting-for-dev** [comment]
Sorry to ask, but... did you restarted the server? :)

**Comment by waiting-for-dev** [comment]
Also, you should be requesting one of the following endpoints:

- `POST /api/landlords/sign_in.json`
- `POST /api/landlords.json`

And the response has to be a successful sign in (so the user information should be in the response body). If there is an error in the password or something the JWT won't be dispatched.

**Comment by russellvaughan** [comment]
Haha. Yes definitely restarting (but always worth checking!) I am getting a successful sign in (so 200s with user info in the body)

I'm not too sure where to go with this one!

Does everything look correct in my details? Any other logging I can do?

**Comment by waiting-for-dev** [comment]
Yes, except the double slash, everything seems ok. Just to double check it, could you try with the version I just pushed to [issue-37 branch](https://github.com/waiting-for-dev/devise-jwt/tree/issue-37)?

So, in your Gemfile:

```ruby
gem "devise-jwt", github: "waiting-for-dev/devise-jwt", branch: "issue-37"
```

**Comment by russellvaughan** [comment]
:( no luck unfortunately. A really frustrating one as I'd love to use this
but will probably have to look for another solution. Your support has been
great though. Last question, I'm not missing something obvious am I? Do i
need to manually need to include the token in the header within my
controller at all?

**Comment by waiting-for-dev** [comment]
No, the token is added automatically to the response headers. Maybe you can double check your CORS configuration and debug with curl giving different origin values...

Double check also that `Warden::JWTAuth::Middleware::TokenDispatcher` is in your list of rack middlewares, even I can't see how it could not be.

This core functionality, of course, is known to work, so I guess it has to be with something in your configuration... If you can isolate the bug and prepare an example application repository reproducing it I will happily look into it.

**Comment by russellvaughan** [comment]
In rack middleware I just have:

Warden::JWTAuth::Middleware

opposed to:

Warden::JWTAuth::Middleware::TokenDispatcher

but assume it's included in the first. 

I've been trying to double check CORS but with out any specific errors, I feel like I'm just trying things. 

If anyone has similar issues, I'd be keen to hear how they resolved them.

**Comment by waiting-for-dev** [comment]
> In rack middleware I just have:

> Warden::JWTAuth::Middleware

> opposed to:

> Warden::JWTAuth::Middleware::TokenDispatcher

> but assume it's included in the first.

Yes, it is included...

**Comment by waiting-for-dev** [comment]
Sorry, but run out of ideas to help with you configuration. Going to close it now, but, please, feel free to add more comments if you come with more clues or you can prepare an isolated application reproducing the problem.

**Comment by timscott** [comment]
I'm experiencing this problem. Here's the relevant code:

```ruby
config.jwt do |jwt|
  jwt.secret = ENV['DEVISE_JWT_SECRET_KEY']
  jwt.expiration_time = 30.days
  jwt.dispatch_requests = [
    ['POST', %r{^/auth/facebook$}]
  ]
end
```
This request is returned with no Authorization header in the response.

```bash
Started POST "/auth/facebook" for 127.0.0.1 at 2017-10-22 15:12:44 -0500
```

**Comment by vvv22** [comment]
hey @russellvaughan  i had the same problem, it worked when i changed the route to devise_for :users

**Comment by kristw** [comment]
@russellvaughan Mine worked after I set `dispatch_requests` and `revocation_requests` in `config/initializers/devise.rb`

```rb
  config.jwt do |jwt|
    jwt.secret = ENV['DEVISE_JWT_SECRET_KEY']
    jwt.request_formats = {
      landlord: [nil, :json]
    }
    jwt.dispatch_requests = [
      ['POST', %r{^/api/v2/login([.]json)?$}]
    ]
    jwt.revocation_requests = [
      ['POST', %r{^/api/v2/logout([.]json)?$}]
    ]
    jwt.expiration_time = 1.day.to_i
  end

```

**Comment by yangez** [comment]
Might not be related with original problem, but when this happened to me I realized I forgot the `sign_in` method in my custom login action. I got the Authorization header when I added it back in.

**Comment by SKEPDIMI** [comment]
Has this issue not been successfully resolved? I'm also experiencing it.

**Comment by farverio** [comment]
@waiting-for-dev Had same issue here with no solution after a couple hours trying to debug. Have to move onto another solution, but think it would have been perfect for what I was looking for.

Might recommend including an example code base so individuals can compare their code against or an actual walkthrough when setting up. I felt there were lots of small bits of code, but not in a logical order to get things up and running. 

I, for instance, don't need anything related to jwt_payload, just want a safe and working revocation strategy, and don't believe the installation actually stops after installation/setup ends after 'gem install devise-jwt'.

Thanks again for your hard work and hope this helps improve the repo even more moving forward!

**Comment by waiting-for-dev** [comment]
@farverio I'm afraid covering each individual workflow a user could follow when installing it is impossible. The README tries to follow a complete workflow where, of course, you may have to ignore something (like `jwt_payload` in your case). You have a lot more information about revocation strategies further down the file. Docs are far from stopping setup instructions in `gem install` line. Of course, as always, PR's improving anything, also the documentation, are more than welcome.

**Comment by KenneyE** [comment]
I was running into a similar issue upon user registration. I wasn't using any custom paths or controllers or anything. The issue ended up being that I wasn't actually signing the user in after registration since they were `confirmable`. Pretty dumb on my part, but adding `config.allow_unconfirmed_access_for = 1.hour` in `devise.rb` resolved that issue. 

That may or may not be helpful to anyone else, but figured I'd add where I went wrong.

**Comment by nasirshamshad** [comment]
> @russellvaughan Mine worked after I set `dispatch_requests` and `revocation_requests` in `config/initializers/devise.rb`
> 
> ```ruby
>   config.jwt do |jwt|
>     jwt.secret = ENV['DEVISE_JWT_SECRET_KEY']
>     jwt.request_formats = {
>       landlord: [nil, :json]
>     }
>     jwt.dispatch_requests = [
>       ['POST', %r{^/api/v1/login([.]json)?$}]
>     ]
>     jwt.revocation_requests = [
>       ['POST', %r{^/api/v1/logout([.]json)?$}]
>     ]
>   end
> ```

This also worked for me after 2 days of head bangs

**Comment by HussainNiazi120** [comment]
> I was running into a similar issue upon user registration. I wasn't using any custom paths or controllers or anything. The issue ended up being that I wasn't actually signing the user in after registration since they were `confirmable`. Pretty dumb on my part, but adding `config.allow_unconfirmed_access_for = 1.hour` in `devise.rb` resolved that issue.
> 
> That may or may not be helpful to anyone else, but figured I'd add where I went wrong.

Saved my day

**Comment by KidA001** [comment]
Mine also worked after setting  `dispatch_requests` and `revocation_requests` in config/initializers/devise.rb - Don't fully understand why this is necessary. I'm on Rails 7.0.2.2

**Comment by selcuktoklucu** [comment]
I was trying to figure out the issue for a while, read this entire thread, and found out I was sending a `GET` request, instead of a `POST`...  I know it is not a solution but some may be doing the same dummy thing I did :)
