### ISSUE TITLE
Testing Login with CURL

### ISSUE THREAD

**Issue by LL0rd** [waiting-for-dev/devise-jwt#38]
Hi,

I installed the devise-jwt gem as mentioned in the readme document, but currently I have some problems testing the setup. For a test, I created a user. If I use the device web interface, the user can log in. But if I use the json Interface, this does not work for me. I tried the following CURL requests:

`curl -i -X POST http://localhost:3000/users/sign_in.json -d "email=guy@gmail.com&password=111111"`

But it does not work for me. 

`HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 6649996c-33ab-439c-87d3-f7b529f08857
X-Runtime: 0.024306
Vary: Origin
Transfer-Encoding: chunked`

and on the server

`Started POST "/users/sign_in.json" for 127.0.0.1 at 2017-09-05 03:14:44 +0200
Processing by Devise::SessionsController#create as JSON
  Parameters: {"email"=>"guy@gmail.com", "password"=>"[FILTERED]"}
Completed 401 Unauthorized in 5ms (ActiveRecord: 0.0ms)`

Can some one help me?

**Comment by waiting-for-dev** [comment]
Hi,

this is not a `devise-jwt` issue: it doesn't process the log in through password, it just adds a token to the response if it is successful. Try giving content-type headers and check your API and devise configuration.
