### ISSUE TITLE
Change default sub

### ISSUE THREAD

**Issue by hudadiaz** [waiting-for-dev/devise-jwt#4]
How to change value for `sub`? By default, it is using `id`. I would like to use other `uuid` instead. How can I do so? I tried doing

```
def jwt_payload
  super.merge(sub: self.uuid)
end
```

**Comment by waiting-for-dev** [comment]
I recommend not to move aside from defaults without a strong reason.

However, if you really need to change it, you should reimplement `warden-jwt_auth` [expected interfaces](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/interfaces.rb) for the `UserRepository` and `User`.

In ActiveRecord, the model class is the `UserRepository` while the model instance is the `User`, so you would need something like:

```ruby
class User < ApplicationRecord
  # ...
  def self.find_for_jwt_authentication(sub)
    find_by!(uuid: sub)
  end

  def jwt_subject
    uuid
  end
end
```

**Comment by hudadiaz** [comment]
Thanks.
