### ISSUE TITLE
Question: I find the documentation unclear about request formats and regex.

### ISSUE THREAD

**Issue by rastogiachyut** [waiting-for-dev/devise-jwt#41]
If I have the following in my config:
```
jwt.request_formats = {
      user: [:json],
      admin: [:json]
}
jwt.dispatch_requests = [
      ['POST', %r{^/sign-in/api$}],
      ['POST', %r{^/sign-in/api.json$}]
]
```
Do I need to specify .json in my path regex?

**Comment by waiting-for-dev** [comment]
Sorry, I forgot to respond to this issue.

`request_formats` is appended to what is configured in  `dispatch_requests`, so you don't have to add `.json` there. Anyway, usually there is no need to manually configure `dispatch_requests`. If you need to dispatch token only in the `json` format of the usual sign in and sign up requests, just configure `request_formats` with `:json` and do not configure `dispatch_requests`
