### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by RanaProgrammer** [waiting-for-dev/devise-jwt#42]
```
def sign_hmac(algorithm, msg, key)
    OpenSSL::HMAC.digest(OpenSSL::Digest.new(algorithm.sub('HS', 'sha')), key, msg)
  end

  def base64url_encode(str)

TypeError in Devise::SessionsController#create
```

i got this issue after integrating devise jwt in my application. i am using JTIMatcher Strategy. i am able to create users successfully with unique jti IDs but unable to sign in. can anybody help me?
Plus i am using confirmable in user model. is that creating an issue or what?

My user model is as below:

class User < ApplicationRecord
 ```
 include Devise::JWT::RevocationStrategies::JTIMatcher
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable,
         :jwt_authenticatable, jwt_revocation_strategy: self
end 
```

plus i am using 

> postgres

 database. 
my recent migration is:
```
class AddJtiToUsers < ActiveRecord::Migration[5.1]
  def change
    add_column :users, :jti, :string, null: false
    add_index :users, :jti, unique: true
  end
end
```

**Comment by RanaProgrammer** [comment]
i wasn't passing the secret token to jwt secret.
i think you should update documentation a little bit. explaining secret key and how to make it available in ENV variable.
i googled and found figaro gem, which did the trick for me.
i am new to rails sorry for inconvenience.

**Comment by waiting-for-dev** [comment]
Hey @RanaProgrammer ,

it is [already documented in the README](https://github.com/waiting-for-dev/devise-jwt#secret-key-configuration).

But a more explicit error would be more user friendly. I'll change it when I have the time.
