### ISSUE TITLE
Using devise-jwt with custom sessions controller

### ISSUE THREAD

**Issue by jvalenciag** [waiting-for-dev/devise-jwt#45]
Hi,
I am trying to use this gem with a custom sessions controller based on Devise but a can't get the token after login.
using this code
```ruby
class V1::SessionsController < ApplicationController

    def create
      user = User.where(username: params[:user][:username]).first
      if user&.valid_password?(params[:user][:password])
        render json: user.as_json, status: :created
      else
        head(:unauthorized)
      end
    end
end
```
with this options
```ruby
  jwt.dispatch_requests = [['POST', %r{^/v1/users/sign_in$}]]
  jwt.request_formats = { user: [:json] }
```
and this routes
```ruby
Rails.application.routes.draw do
  namespace :v1, defaults: { format: :json } do
    devise_for :users
  end
end
```
I did get this working when using the next routes, which calls the devise sessions controller
```ruby
Rails.application.routes.draw do
  scope :v1, defaults: { format: :json } do
    devise_for :users
  end
end
```

**Comment by waiting-for-dev** [comment]
Hi @jvalenciag ,

your controller action totally overpasses devise logic. It doesn't call the uderlying `warden.authenticate!` method, so it won't work. Basically, you are not using devise nor warden to create sessions, so this gem won't work this way.

I would try not to monkey patch devise behaviour, but if you really need to, then just add the revelant modifications.
