### ISSUE TITLE
Application with API & GUI: Session cookie is set, so clients can use this to authenticate insteaded of JWT

### ISSUE THREAD

**Issue by ttrmw** [waiting-for-dev/devise-jwt#46]
Hey,

In my application I have `ActionController::API` controllers and standard `ActionController::Base` subclasses. I want my API users to only be able to authenticate via JWT, however (I guess) since the middleware is still loaded in the API controller context, the initial session creation still sets the cookie on the client. 

In practice, this means that the API user can use the cookie to authenticate instead of the JWT. I would prefer this not to be the case, and it's not entirely clear how best to disable session management in this context.

Appreciate this is possibly more of a rails/devise question than a `devise-jwt` question, but hoping you might have some pointers for my use case?

**Comment by waiting-for-dev** [comment]
Hi @ttrmw ,

I guess [this thread in devise](https://github.com/plataformatec/devise/issues/285) can help you.

But maybe a cleaner way could be to prepare your HTML and JSON applications as [rails engines](http://api.rubyonrails.org/classes/Rails/Engine.html), with their custom middleware stack:

> As an engine can now be a Rack endpoint, it can also have a middleware stack. The usage is exactly the same as in Application:
> ```ruby
> module MyEngine
>   class Engine < Rails::Engine
>    middleware.use SomeMiddleware
>   end
>end

**Comment by ttrmw** [comment]
Thanks!

I've done that before and find it pretty distasteful - if your API engine shares domain logic with the parent, you end up with a lot of duplication in order to adequately test the engine.

**Comment by waiting-for-dev** [comment]
Never had this use case before, but maybe you could keep the model and the domain logic in your host application while having the engines manage the HTTP interface (controller and views).

**Comment by waiting-for-dev** [comment]
Closing because it is not an issue, but please feel free to add more comments.
