### ISSUE TITLE
 JWT::VerificationError - Signature verification raised

### ISSUE THREAD

**Issue by elisoncampos** [waiting-for-dev/devise-jwt#47]
Hi! I'm setting up an API that used devise and devise-jwt for authentication and I followed up all the steps in order to make it work. However, whenever I tried to sign in within my BackEnd i' receive a 401 response.

So I dug up on the code and found that within `warden.authenticate!` was raising an error and being rescued by:
```ruby
      def authenticate!
        user = UserDecoder.new.call(token, scope)
        success!(user)
      rescue JWT::DecodeError
        fail!
      end
```
Following that lead, I found that the error being raised was a **JWT::VerificationError - Signature verification raised**, however I created my secret key using `rails secret`as proposed in the configuration guide. Here's the line in my `config/initializers/devise.rb`

```ruby
  config.jwt do |jwt|
    jwt.expiration_time = 3.hours
    jwt.secret = ENV.fetch('DEVISE_JWT_SECRET_KEY') { 'db70e50ec08feabaa1f05c65dadfc8057fb774052ff8fe7bc90b6d4001bfb681bbd6c26fbf06b77f39078270093948a5fd9ea09fac495fc9f7aab43241836dcf' }
  end
```
I even tried running it with the ENV variable forced and just plain value in the config just to test if it was something wrong with fetch method from ENV but it still doesn't work, any help?

**Comment by waiting-for-dev** [comment]
Hi there,

what does the folowing return?

```ruby
Warden::JWTAuth.config
Devise::JWT.config
```

**Comment by elisoncampos** [comment]
Hi, thanks for your reply, there the results:

```ruby
Warden::JWTAuth.config

#<#<Class:0x007fe6d41244f0>:0x007fe6d411e1b8
 @config=
  {:secret=>
    "db70e50ec08feabaa1f05c65dadfc8057fb774052ff8fe7bc90b6d4001bfb681bbd6c26fbf06b77f39078270093948a5fd9ea09fac495fc9f7aab43241836dcf",
   :expiration_time=>3 hours,
   :mappings=>{:manager_api_v1_user=>User (call 'User.connection' to establish a connection)},
   :dispatch_requests=>[["POST", /^\/manager\/api\/v1\/auth\/sign_in$/]],
   :revocation_requests=>[["DELETE", /^\/manager\/api\/v1\/auth\/sign_out$/]],
   :revocation_strategies=>{:manager_api_v1_user=>JWTBlacklist (call 'JWTBlacklist.connection' to establish a connection)}}>
```

```ruby
Devise::JWT.config
#<#<Class:0x007fe6d58a0340>:0x007fe6d589b9d0
 @config=
  {:secret=>
    "db70e50ec08feabaa1f05c65dadfc8057fb774052ff8fe7bc90b6d4001bfb681bbd6c26fbf06b77f39078270093948a5fd9ea09fac495fc9f7aab43241836dcf",
   :expiration_time=>3 hours,
   :dispatch_requests=>nil,
   :revocation_requests=>nil,
   :request_formats=>{}}>
```

Should de dispatch and revocation requests on Devise::JWT.config inherit from Warden config or nothing strange there?

**Comment by waiting-for-dev** [comment]
> Should de dispatch and revocation requests on Devise::JWT.config inherit from Warden config or nothing strange there?

No, nothing strange there...

Your error comes from [ruby-jwt library](https://github.com/jwt/ruby-jwt), specifically from [this method](https://github.com/jwt/ruby-jwt/blob/f943b9d056348f90cbc796824b34a6dec0628cb9/lib/jwt/signature.rb#L38). 

In order to try to isolate the error, try to run the following with a token generated during a sign in:

```ruby
Warden::JWTAuth::TokenDecoder.new.call(token)
```

**Comment by elisoncampos** [comment]
So I might be doing something wrong with my sign_in flow and maybe my error doesn't have anything to do with jwt? Because im sending a POST to `sign_in`passing e-mail and password in order to retrieve the token which then I'll use for requesting routes protected by authentication but that's where im getting the 401 error.

**Comment by waiting-for-dev** [comment]
> Because im sending a POST to sign_inpassing e-mail and password in order to retrieve the token which then I'll use for requesting routes protected by authentication but that's where im getting the 401 error.

How do you provide the token to the requests protected by authentication?

**Comment by elisoncampos** [comment]
The first thing an user does is send a request to `sign_in`providing e-mail and password, at that point, the request is sent without an Authorization Header. I was expecting devise to return me a JWT token which I'd store within my front-end application (react redux in this case).

After that, every request to my API would have an Authorization Header `Bearer <token>`

**Comment by waiting-for-dev** [comment]
Yes, that's the expected workflow.

**Comment by elisoncampos** [comment]
So how can i try to generate a token if the error is happening during sign_in?

**Comment by waiting-for-dev** [comment]
I don't understand your issue. In you first comment you say that you get the error in `UserDecoder.new.call`, but that's not called during sign in.

What's exactly the problem? Are you getting a token after the sign in (in the response headers)? If not, to which URL are you requesting it?

**Comment by elisoncampos** [comment]
I'm sorry, maybe i didn't find where the error was being really raised, I just removed the rescue that led to a 401 response to see the real error being raised.

Here's a postman request:

![image](https://user-images.githubusercontent.com/5031917/32546862-917712c0-c467-11e7-98c0-698c09040841.png)

That request, with valid credentials leads to a 401 error, traceback from server:

```
Started POST "/manager/api/v1/auth/sign_in" for 127.0.0.1 at 2017-11-08 09:25:23 -0200
   (0.6ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
   (0.5ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
Processing by Api::V1::SessionsController#create as */*
  Parameters: {"user"=>{"email"=>"elison.campos@gmail.com", "password"=>"[FILTERED]"}, "formats"=>:json, "session"=>{"user"=>{"email"=>"elison.campos@gmail.com", "password"=>"[FILTERED]"}}}
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)
```

Here's how my routes are set up:

```ruby
Rails.application.routes.draw do
  prefix = Rails.env == 'staging' ? :manager_staging : :manager

  namespace prefix, module: nil do
    get '/ping', to: 'application#pong'

    namespace :api, defaults: { formats: :json } do
      namespace :v1 do
        devise_for :users, path: :auth
      end
    end
  end
end
```

Don't mind the namespace with null module, it's just that we ran dockerized applications that have the same base entrypoint.

My Controller, which inherits from devise due to the API namespacing:

```ruby
module Api
  module V1
    class SessionsController < ::Devise::SessionsController
    end
  end
end
```

And last, rails routes returns me:

```
                             Prefix Verb   URI Pattern                             Controller#Action
                       manager_ping GET    /manager/ping(.:format)                 application#pong
    new_manager_api_v1_user_session GET    /manager/api/v1/auth/sign_in(.:format)  api/v1/sessions#new {:formats=>:json}
        manager_api_v1_user_session POST   /manager/api/v1/auth/sign_in(.:format)  api/v1/sessions#create {:formats=>:json}
destroy_manager_api_v1_user_session DELETE /manager/api/v1/auth/sign_out(.:format) api/v1/sessions#destroy {:formats=>:json}
```

**Comment by waiting-for-dev** [comment]
The only thing that `devise-jwt` does to the sign in request is adding an `Authorization` response header if the result is 200. But it can't change the response status to 401. When email/password are provided, the strategy doing the authorization is devise's own [DatabaseAuthenticatable](https://github.com/plataformatec/devise/blob/master/lib/devise/strategies/database_authenticatable.rb). I would recommend trying to debug there.

**Comment by waiting-for-dev** [comment]
Maybe you forgot to add `database_authenticatable` module to your user model? If so, then it could be possible that the unauthorization comes from `devise-jwt`, which is not able to sign in the user because there is no token to decode. In such case, just add `database_authenticatable` to your user model.

**Comment by elisoncampos** [comment]
```ruby
class User < ApplicationRecord
  devise :database_authenticatable, :jwt_authenticatable, jwt_revocation_strategy: JWTBlacklist
end
```
Yeah, i thought the same but no... I did find something strange tho...in `Devise::SessionsController` the method create:

```ruby
# POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end
```
`warden.authenticate!(auth_options)` is what causes an error which leads to the 401 response, but he's calling `Warden::Proxy.authenticate!`. Following that, i found that when warden executes `_run_strategies_for`  the instance variable `@winning_strategies` is empty, so it can't determine which strategy to use.

Is that a configuration error perhaps?

**Comment by elisoncampos** [comment]
Ok, so in order to test things I moved my sign_in route to a main entry point:
```ruby
Rails.application.routes.draw do
  prefix = Rails.env == 'staging' ? :manager_staging : :manager
  namespace prefix, module: nil do
    get '/ping', to: 'application#pong'

    namespace :api, defaults: { formats: :json } do
      namespace :v1 do
      end
    end
  end
  devise_for :users
end
```

And a request to `http://localhost:3000/users/sign_in` completed with 200 (then it got redirected to the rails welcome controller) but in the stack there was nothing being executed by jwt (the response headers didn't have a token) but i think thats because the redirection.

So I think it's not an issue within devise-jwt, maybe with device not working properly on namespaced routes?

**Comment by waiting-for-dev** [comment]
Yes, it seems an issue with devise configuration. Inspect `Devise.mappings`. Maybe you are using a wrong scope name (`user` in your params).

**Comment by elisoncampos** [comment]
Now iI think I found at least a workaround by only configuring paths for devise:

`routes.rb`:
```
Rails.application.routes.draw do
  prefix = Rails.env == 'staging' ? :manager_staging : :manager

  namespace prefix, module: nil do
    get '/ping', to: 'application#pong'

    namespace :api, defaults: { formats: :json } do
      namespace :v1 do
      end
    end
  end

  devise_for :users, path: "#{prefix}/api/v1/auth"
end
```

But when i send a POST to the sign_in URL I'm not getting a token in response headers, and SessionsController is redirecting me (warden flow for jwt not triggering anything). I Think I'm missing some set up step to make devise-jwt work properly and i can't find on the readme. Is there any app sample I could look at? Do I need a custom SessionsController?

**Comment by waiting-for-dev** [comment]
You need to configure devise for json, so it doesn't redirect on success (step when you loose the token).

You can look at the [fixture app](https://github.com/waiting-for-dev/devise-jwt/tree/master/spec/fixtures/rails_app) used in tests.

**Comment by waiting-for-dev** [comment]
If I remember well, you need to add `respond_to :json` to your controller, and configure devise to use `json` as default route format (in the router). You don't need a custom `SessionsController`.

**Comment by elisoncampos** [comment]
I managed to make it work, I'm assuming its a problem with devise and namespaces leading do some wrong argument provided when warden executes its strategies for authentication. Sorry for giving you trouble man and thanks for all the support!

**Comment by waiting-for-dev** [comment]
I guess that you had a wrong `user` param. I don't remember now how devise uses namespaces and so in order to name scopes, but maybe it should have been something like `staging_user`.

You are welcome. Happy this works for you not. Closing the issue, then.

**Comment by marlonmantilla** [comment]
If someone else happens to have this issue again, in my case it was because i already had `Authorization` bearer token saved in my local storage from a different app (i was developing a react app on the same port) so it was trying to sign in setting an invalid token. So it was fixed by clearing out the local storage.

**Comment by Mei152** [comment]
Hello,

I am trying to set up this gem for two models, `user`, and `api_user`. User will use regular Devise authentication, and api_user will use use jwt with the whitelist strategy.  I have the log in for api_user working, and it returns a jwt in the auth header, and creates a record in the whitelisted_jwts table. When api_user logs out, the whitelisted jwt is not deleted. The other bigger issue is that a get request for another resource results in an `"error": "Signature verification raised"` error. I do submit the issued token in the auth header with the get request.

Judging from previous posts in this thread, I am guessing you would want the following info:

```
irb(main):002:0> Warden::JWTAuth.config
=> #<#<Class:0x0000562b9d392ff0>:0x0000562b9d392e10 
@config={
  :secret=>"86630d90134bb9b5f105409635f61962761f59f2c9f3595c414cbca6ee1a4f47388c728b9fb61a12abe003b8e83cd0c57dd924f92162a005c001dd38480e8dd4",
  :expiration_time=>3600,
  :aud_header=>"JWT_AUD",
  :mappings=>{:api_user=>"ApiUser"},
  :dispatch_requests=>[
    ["POST", /^\/api_users\/sign_in.json$/],
    ["POST", /^\/api_users.json$/]
  ],
  :revocation_requests=>[["DELETE", /^\/api_users\/sign_out.json$/]],
  :revocation_strategies=>{:api_user=>"ApiUser"}
}


irb(main):005:0> Devise::JWT.config
=> #<#<Class:0x0000562b9d3f9c28>:0x0000562b9d3f9a48
@config={
  :secret=>"86630d90134bb9b5f105409635f61962761f59f2c9f3595c414cbca6ee1a4f47388c728b9fb61a12abe003b8e83cd0c57dd924f92162a005c001dd38480e8dd4",
  :expiration_time=>3600,
  :dispatch_requests=>nil,
  :revocation_requests=>nil,
  :aud_header=>nil,
  :request_formats=>{:api_user=>[:json]
```

Running `Warden::JWTAuth::TokenDecoder.new.call(token)` with the Devise issued token does fail

If anyone can help point me in the right direction, that would be great.  I have done a lot of searching for a working example of this type of implementation, but have not found anything that sheds light on my issue. I am in a bit over my head.

**Comment by niuage** [comment]
The comment from waiting-for-dev is what helped me after all. Turns out, when devise_for is in a `scope`, devise needs a namespace for the user param:

```
scope :api do
    devise_for :users, as: :api, defaults: { format: :json }
  end
```

will expect `{"api_user": {"email": "email@gmail.com", "password": "password"}}`
