### ISSUE TITLE
rubygems?

### ISSUE THREAD

**Issue by jcavalieri** [waiting-for-dev/devise-jwt#49]
Hi @waiting-for-dev,

It looks like the rubygems for this project is behind. Do you plan on updating rubygems? Or should we I just put in a github ref in my Gemfile?

Thanks,
John

**Comment by waiting-for-dev** [comment]
Hi @jcavalieri ,

well, the only [difference](https://github.com/waiting-for-dev/devise-jwt/compare/0.4.1...master) between `0.4.1` release and master is an update to the version specified in the README instructions. I'm waiting to have something fore substantial before pushing a new release :smile:

**Comment by waiting-for-dev** [comment]
Closing this, but feel free to add more comments if needed.

**Comment by jcavalieri** [comment]
Oh my bad, I clicked the first one that came up on a google search and it was an older version on ruby gems. Sorry for the confusion.

**Comment by waiting-for-dev** [comment]
No worries :)
