### ISSUE TITLE
Authorization header is missing after sign up

### ISSUE THREAD

**Issue by Darkside73** [waiting-for-dev/devise-jwt#5]
There is no ```Authorization``` header after successful sign up. Is it by design?

**Comment by waiting-for-dev** [comment]
Which version are you using? It was added in 0.2.0

**Comment by Darkside73** [comment]
devise-jwt-0.1.1
Thanks. Will try 0.2 instead

**Comment by waiting-for-dev** [comment]
Ok, I'll close it, then. Reopen if you have any trouble.
