### ISSUE TITLE
Can the README include instructions on creating session requests as an API?

### ISSUE THREAD

**Issue by JCDJulian** [waiting-for-dev/devise-jwt#50]
First, this gem is awesome, so thank you for your work on it! :+1: 

One thing that would be very helpful would be if you could expand on this point in the docs:

> A user authenticates through devise create session request (for example, using the standard :database_authenticatable module).

Devise doesn't seem to respond to JSON requests out-of-the-box, and most of the links and tutorials on doing so revolve around old versions of Devise or Rails. When I try and authenticate at /sign_in via JSON, I get hit with:

`ActionController::UnknownFormat at /clients/sign_in`

Reviewing your example, I saw that adding

`  respond_to :json
`
to my application_controller.json allows me to solve the problem, but this isn't a great workaround because actions like /sign_out/ then return blank when you hit them with accept: json. I'm confused why there isn't a gem or agreed upon way to overwrite the devise controllers to respond to both html and json formats, but maybe there are some resources you could toss in the readme that would make that part less confusing to novices to devise like myself. Apologies if this is out of the scope of the gem; having a hard time finding resources on getting Devise API-ready.

**Comment by waiting-for-dev** [comment]
Hi @JCDJulian ,

thanks for pointing that out. Effectively it is something more related with `devise` itself. However, it is true that it could be helpful for a lot of people adopting at the same time `devise` and `devise-jwt` for an API authentication system. For these reasons I would prefer just adding a link from the README to a Wiki page. I can do it myself when I have the time, although if someone is available right now any collaboration is appreciated ;)

Cheers

**Comment by waiting-for-dev** [comment]
Instruction added in the [wiki](https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs). Feel free to improve them.
