### ISSUE TITLE
Authorization headers not returned after sign_in

### ISSUE THREAD

**Issue by lakehouseru** [waiting-for-dev/devise-jwt#54]
Hello, no matter what I try the JWT token is not returned after Sign in

![image](https://user-images.githubusercontent.com/562902/33239079-96a65ba0-d2ab-11e7-8538-d45365116867.png)

user.rb

> class User < ActiveRecord::Base
>   devise :database_authenticatable, :recoverable, :rememberable,
>          :validatable, :lockable, :registerable, :confirmable, :jwt_authenticatable, jwt_revocation_strategy: Devise::JWT::RevocationStrategies::Null

routes.rb 

> devise_for :users, controllers: {
>     sessions: 'sessions',
>     passwords: 'passwords',
>     unlocks: 'unlocks',
>     registrations: 'registrations',
>     confirmations: 'confirmations'
>   }, skip: [:sessions, :passwords, :unlocks, :registrations, :confirmations]
> 
>   as :user do
>     get 'sign_in'     => 'sessions#new',      as: :new_user_session
>     post 'sign_in'    => 'sessions#create',   as: :user_session
>     delete 'sign_out' => 'sessions#destroy',  as: :destroy_user_session
>     get 'sign_up' => 'registrations#new',     as: :new_user_registration
>     post 'sign_up' => 'registrations#create', as: :user_registration
>     get 'reconfirm' => 'confirmations#new',   as: :new_confirmation
>     post 'confirm' => 'confirmations#create', as: :confirmation
>     get 'confirm' => 'confirmations#show'
>     scope '/account' do
>       # password reset
>       get  'reset_password' => 'passwords#new',    as: :new_user_password
>       put  'reset_password' => 'passwords#update', as: :user_password
>       post 'reset_password' => 'passwords#create'
>       get 'reset-password/change', to: 'passwords#edit', as: :edit_user_password
> 
>       # unlocks
>       post 'unlock',     to: 'unlocks#create', as: :unlock
>       get  'unlock/new', to: 'unlocks#new',    as: :new_unlock
>       get  'unlock',     to: 'unlocks#show'
>     end
>   end

devise.rb

> Devise.setup do |config|
> 
>   config.jwt do |jwt|
>     jwt.secret = ENV['DEVISE_JWT_SECRET_KEY']
>     jwt.request_formats = {
>                         user: [:json]
>                       }
>   end

> bundle exec rake middleware
> 
> use Airbrake::UserInformer
> use Rack::Cors
> use Rack::Sendfile
> use ActionDispatch::Static
> use Rack::Lock
> use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007f98542a8660>
> use Rack::Runtime
> use Rack::MethodOverride
> use ActionDispatch::RequestId
> use Rails::Rack::Logger
> use ActionDispatch::ShowExceptions
> use WebConsole::Middleware
> use ActionDispatch::DebugExceptions
> use BetterErrors::Middleware
> use Airbrake::Rails::Middleware
> use ActionDispatch::RemoteIp
> use ActionDispatch::Reloader
> use ActionDispatch::Callbacks
> use ActiveRecord::Migration::CheckPending
> use ActiveRecord::ConnectionAdapters::ConnectionManagement
> use ActiveRecord::QueryCache
> use ActionDispatch::Cookies
> use ActionDispatch::Session::CookieStore
> use ActionDispatch::Flash
> use ActionDispatch::ParamsParser
> use Rack::Head
> use Rack::ConditionalGet
> use Rack::ETag
> use Warden::Manager
> use Warden::JWTAuth::Middleware
> run OdinDemo::Application.routes

The sign_in is successful , but still no tokens in the headers. Any ideas how to debug this? Thank you!

**Comment by waiting-for-dev** [comment]
Hi @lakehouseru , do you have the `Authorization` header in the list of allowed request headers and exposed response headers?

**Comment by lakehouseru** [comment]
Hello, @waiting-for-dev and thank you for reply. 

If we are talking about rack-cors , I think yes:

`config.middleware.insert_before 0, "Rack::Cors" do
      allow do
        origins '*'
        resource '*', :headers => :any, :methods => [:get, :post, :options]
      end
    end`

**Comment by waiting-for-dev** [comment]
It seems you are not exposing `Authorization` header:

```ruby
resource '*',
  :headers => :any,
  :methods => [:get, :post, :options],
  :expose => %w(Authorization)
```

**Comment by lakehouseru** [comment]
Still no result. Only Access-Control-Expose-Headers:Authorization header string appeared

![image](https://user-images.githubusercontent.com/562902/33265911-8a0c2922-d384-11e7-9631-46057e756db5.png)

**Comment by waiting-for-dev** [comment]
Which is your output for `Devise::JWT.config`  and `Warden::JWTAuth.config`? Please, format the result to be readable in github with [code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by pablocrivella** [comment]
@lakehouseru Try removing this part:

```
jwt.request_formats = {
user: [:json]
}
```

I had the exact same issue, removing that solved it.

**Comment by waiting-for-dev** [comment]
@lakehouseru how is it going? Is this still a problem?

**Comment by waiting-for-dev** [comment]
Closing because it seems it has been abandoned
