### ISSUE TITLE
Undefined method `jwt_revocation_strategy'

### ISSUE THREAD

**Issue by BrunoQuaresma** [waiting-for-dev/devise-jwt#55]
I followed the instructions and when I run rails server this error is raised.

**Comment by StephanMeijer** [comment]
Invalid? Why

**Comment by waiting-for-dev** [comment]
OP closed the issue itself on the same day he opened it, so I supposed it was invalid.

**Comment by StephanMeijer** [comment]
Can we reopen this?

**Comment by waiting-for-dev** [comment]
Of course but, please, report here the issue you are having following the [`bug report template`](https://github.com/waiting-for-dev/devise-jwt/blob/master/issue_template.md).

**Comment by alinawaz42** [comment]
Just want add my 2 cents here. It happened to me as well, when I skipped `jwt_revocation_strategy` as I didn't want to setup any revocation strategy.

```ruby
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :jwt_authenticatable,
         jwt_revocation_strategy: Devise::JWT::RevocationStrategies::Null
end
```

**Comment by waiting-for-dev** [comment]
Thanks @alinawaz42  for your feedback. It can be very valuable to others. As you did, if you don't want any revocation behavior you just need to configure the null strategy. 

Due to the lack of response of @StephanMeijer and that we surely have reached the root of the problem, I'm going to close it again. Feel free to add more comments if needed.

**Comment by sondnpt00343** [comment]
Maybe you are missing the option of "jwt_authenticatable"

My model...
<img width="449" alt="screen shot 2018-11-03 at 12 23 28" src="https://user-images.githubusercontent.com/18712667/47948452-27aa5c80-df64-11e8-886c-f1c0c88367f8.png">

**Comment by addod19** [comment]
> Maybe you are missing the option of "jwt_authenticatable" and "jwt_revocation_strategy"
> 
> My model...
> <img alt="screen shot 2018-11-03 at 12 23 28" width="449" src="https://user-images.githubusercontent.com/18712667/47948452-27aa5c80-df64-11e8-886c-f1c0c88367f8.png">

Adding `:jwt_authenticatable` solve the error for me. Thanks
