### ISSUE TITLE
Missing authorization header ? 

### ISSUE THREAD

**Issue by iamkobold** [waiting-for-dev/devise-jwt#6]
Hey, first of thanks for making this gem. I am working on the configuration aspects however I am not able to see the Authorization header using cURL or even the normal HTTP login form. Authentication is working just fine as expected. However, i am not seeing the **Authorization: Bearer #{token}** in the HTTP response 

`curl -vvv -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' 'http://localhost/login?account%5Bemail%5D=user%40example.go&account%5Bpassword%5D=password'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> POST /login?account%5Bemail%5D=user%40example.gov&account%5Bpassword%5D=password HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost
> Content-Type: application/json
> Accept: application/json
>
< HTTP/1.1 201 Created
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Status: 201 Created
< Location: /
< Cache-Control: max-age=0, private, must-revalidate
< ETag: W/"76dbae3821e4e2fa727009e0f5b8238b"
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Runtime: 0.259600
< X-Request-Id: 35923e38-342a-411b-b347-f6814939c116
< Date: Thu, 06 Apr 2017 16:39:53 GMT
< Set-Cookie: my_app=bd95d0c2945e03bd1abc10e1644d584b; path=/; expires=Thu, 06 Apr 2017 18:09:53 -0000; HttpOnly
< X-Powered-By: Phusion Passenger 5.1.2
* Server nginx/1.10.2 + Phusion Passenger 5.1.2 is not blacklisted
< Server: nginx/1.10.2 + Phusion Passenger 5.1.2
<
* Connection #0 to host localhost left intact
{"data":{"id":"1","type":"administrators","attributes":{"active":true,"name":"Markus A. Kobold","email":"user@example.org","phone":"(555) 555-555","office":"xxx","created-at":"2012-04-24T19:49:01.000Z","updated-at":"2017-04-06T16:39:53.080Z","preferences":{"locale":{"tz":"Pacific Time (US \u0026 Canada)","date-format":"relative"},"source":{"sub-fellow-forms":false}},"auth":{"payload":{"jti":"1864e178-7cf8-41f6-a698-2d2e64b21825"}}}}}`

Using the JTI Matcher for revocation and it's all initialized properly. So i am not sure why the Authorization header isn't returning the JWT token for future requests.

**Comment by iamkobold** [comment]
Actually never mind; apparently this doesn't automatically configure the Warden parts of the JWTAuth module it wraps. So it's working now.

Thanks again.

**Comment by waiting-for-dev** [comment]
Never mind

**Comment by ramandika** [comment]
> Actually never mind; apparently this doesn't automatically configure the Warden parts of the JWTAuth module it wraps. So it's working now.

How did you make it work? I seems have the same problem with you
