### ISSUE TITLE
Devise controller test helpers not working

### ISSUE THREAD

**Issue by waffleau** [waiting-for-dev/devise-jwt#62]
Hi, you solved [this issue](https://github.com/waiting-for-dev/devise-jwt/issues/61) for me a few days ago, and that's all going well, but I've run into a new issue which is either stemming from it or was present before it.

I've started writing some tests, but I'm running into issues with the Devise test controller helpers not working. I've confirmed that removing the `devise-jwt` gem and related code allows the test to pass.

A simple RSpec example:

```
describe '#index' do
  it 'it redirects to login if not signed in' do
    get :index
    expect(response).to redirect_to(new_user_session_path)
  end

  it 'renders a successful response if signed in' do
    user = FactoryBot.create(:user)
    sign_in(user)  # this is the devise helper
    get :index
    expect(response).to be_success
  end
end
``` 

The second test fails, as the request gets redirected to the `new_user_session_path`.

In this case, the controller being tested is using `before_action :authenticate_user!`, and all this test is doing is just testing the behaviour of that filter. This controller would fail the above test: 

```
class ExampleController < ApplicationController
  before_action :authenticate_user!
   
  def index
  end
end     
```

Devise controller test helpers are added as so:

```
RSpec.configure do |config|
  config.include Devise::Test::ControllerHelpers, type: :controller
end
```

Devise controller testing docs: https://github.com/plataformatec/devise/wiki/How-To:-Test-controllers-with-Rails-3-and-4-%28and-RSpec%29

Let me know if there's any other info I can give you or testing I can do.

**Comment by waffleau** [comment]
My apologies, I totally missed the testing section in the documentation. Closing this and putting on the developer hat of shame.

**Comment by waiting-for-dev** [comment]
No problem @waffleau :smile:
