### ISSUE TITLE
Unable to send AJAX requests through standard Devise routes after adding gem

### ISSUE THREAD

**Issue by fcatuhe** [waiting-for-dev/devise-jwt#63]
I guess the issue is the same as Issue #61, but this time for JS AJAX requests:
```
Started PATCH "/users" for 127.0.0.1 at 2018-01-05 22:15:18 +0100
Processing by UsersController#update as JS
  Parameters: {"utf8"=>"✓", "user"=>{"photo"=>"", "first_name"=>"Happy", "last_name"=>"devise-jwt user", "phone_number"=>"+123", "description"=>"A happy devise-jwt user"}, "commit"=>"Update"}
  User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 4], ["LIMIT", 1]]
   (4.5ms)  BEGIN
   (0.5ms)  COMMIT
Completed 401 Unauthorized in 19ms (ActiveRecord: 5.7ms)
```

I'm on `0.5.3` already with JTI revocation strategy and standard configuration.

Seeing your commit on warden-jwt_auth reinforced my opinion that the issues are related. Tell me if you need more info!

**Comment by waiting-for-dev** [comment]
Hi @f3ndot , could you attach your request headers?

**Comment by fcatuhe** [comment]
This is my Chrome Network / Headers tab info:

General
```
Request URL:http://localhost:3000/users
Request Method:POST
Status Code:401 Unauthorized
Remote Address:127.0.0.1:3000
Referrer Policy:no-referrer-when-downgrade
```
Response Headers
```
Cache-Control:no-cache
Content-Type:text/javascript; charset=utf-8
Set-Cookie:_app_name_session=WDBXSERSOEtmbTU0TWJlbGVBNDV4L2xYYk9YZ0JZaFNsVFBJL3oyNERmUjNIdjJPM3FCdXFUbkRReDhoZEZiL0lCNjQ4R3dOUjhSSnlVZ0JtVkErb1pWNzc2a255M3Q5cGJwaWxrY1dFNDBsUVV5RG1Pa3FMRFN2MXlaR2ZRREIzTDJJelorRjdvN2c4dCtZUWNtZWdnPT0tLWZVclErK2wvek1TTjdYVUdGYzNjYkE9PQ%3D%3D--6b65e6ed2437ad473dd15da37dbbee17a908dabe; path=/; HttpOnly
Transfer-Encoding:chunked
X-Request-Id:eae03aeb-90e4-468f-bb92-dcfec669fad5
X-Runtime:0.014405
```
Request Headers
```
Accept:*/*;q=0.5, text/javascript, application/javascript, application/ecmascript, application/x-ecmascript
Accept-Encoding:gzip, deflate, br
Accept-Language:fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Connection:keep-alive
Content-Length:173
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:_cookoon_web_session=WDhyV3hWeXYzRkVFQmhXMWVCL0FCc3VpLzNpSDFKcUVTZm4yRytLSE5OTGs0L01DOEU4Rk8rbEVFbGdhcmxlNHpMRERZZ1NxZWQ2NlEvVmYvL25MRFp4SHZ3TU9FUll5STluOWR4ZmowZjdmYms1ZEpvRWxjL2JMQWhVOHJackZFMGdvSldSTGJuZDNmYXVDZ205dTZtMVE0Y3hMeTNHTlhSNUdRbGRINHdlNTRlUUExQVZrZVEySnJNdGx4YUZodXlzdTAwSERVTmloVFByU0YxM2ZqVGZqQWtxUmxhVStJVVZuMXdyRlA4VT0tLVhVWlhPOFJpVSs1SkltUVQveGRIUWc9PQ%3D%3D--3fb1b578b28ccab6b4305106848710d206af5cc1
Host:localhost:3000
Origin:http://localhost:3000
Referer:http://localhost:3000/users/edit
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
X-CSRF-Token:YSEGuahS40y9uT7hV3rnQKUb7sYHfsXo4rj+01ezgwWxK9U5l0Uk8hqdyNhW6beEObPVu0+vOJ56q1KtFylUjw==
X-Requested-With:XMLHttpRequest
```
Form Data
```
view URL encoded
utf8:✓
_method:patch
user[photo]:
user[first_name]:Happy
user[last_name]:User
user[phone_number]:123
user[description]:
commit:Update
```

**Comment by waiting-for-dev** [comment]
It seems you are not sending the token through the `Authorization` request header. This should be the reason why you are unauthorized.

**Comment by fcatuhe** [comment]
Yes, this is the point, through standard browser navigation, we should be using cookie authentication instead of JWT authentication. You fixed issue #61 for plain html requests, but here with AJAX / JS requests, the behavior should be the same, no?

In parallel, JWT authentication works well on the same route with JSON requests.

**Comment by waiting-for-dev** [comment]
But aren't you sending the data in JSON format and getting the response body in JSON format?

**Comment by fcatuhe** [comment]
These are the 3 different scenarii:

1. sending JSON and requesting JSON, Authorization header with 'Bearer {JWT}' => working
2. sending HTML and requesting HTML via web browser, authorized by cookie => working since #61 fix
3. sending JavaScript and requesting JavaScript via web browser (typically in Rails: form submission with `remote: true` parameter), authorized by cookie => not working, warden-jwt_auth intercepts the request and rejects because there is no Authorization header. It should not intercept, it should let devise deal with it, and authorize with cookie provided

**Comment by waiting-for-dev** [comment]
Can you try whether `devise-jwt-63` branch in `warden-jwt_auth` gem fixes your issue?

**Comment by fcatuhe** [comment]
Yes that works! Thank you for your great work on this gem!

**Comment by waiting-for-dev** [comment]
Fixed. Just need to update to `devise-jwt 0.5.4` :+1:
