### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by andreofthecape** [waiting-for-dev/devise-jwt#64]
Thank you for your work on the gem! Having a hard time to get it to work. Not getting token back in header. Do you by any chance have an example app with devise and devise-jwt to check implementation?

**Comment by waiting-for-dev** [comment]
Hi there. You can have a look at the [fixture app in tests](https://github.com/waiting-for-dev/devise-jwt/tree/master/spec/fixtures/rails_app) or to one of [this gem dependents](https://github.com/waiting-for-dev/devise-jwt/network/dependents).
