### ISSUE TITLE
NameError: undefined local variable or method 'flash'

### ISSUE THREAD

**Issue by fsdevblog** [waiting-for-dev/devise-jwt#66]
On Rails 5 API I receive the error `NameError: undefined local variable or method 'flash'`
I reproduce the error [here](https://github.com/fsdevblog/devise_api_err)
I wrote a simple spec for reproducing the error.

Seems like it's `devise` problem (not `devise-jwt`), but i think that `devise` not for API, because it's based on session and cookies which you can not say about `devise-jwt`

----
### In a few words about: 
I installed `devise-jwt`. Configured it 
``` ruby
# config/devise.rb
# ...
config.jwt do |jwt|
    jwt.secret = ENV.fetch('DEVISE_JWT_SECRET_KEY', 'blablabla')
    jwt.dispatch_requests = [['POST', %r{^/sign_in}]]
    jwt.revocation_requests = [['DELETE', %r{^/sign_out}]]
  end
```
``` ruby
# config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    post 'sign_in', to: 'sessions#create', as: :user_session
    delete 'sign_out', to: 'sessions#destroy', as: :destroy_user_session
    post 'sign_up', to: 'registrations#create', as: :user_registration
  end

  devise_for :users, path: '', defaults: { format: :json },
             skip: %i[sessions registrations passwords unlocks confirmations]
end
```
made sessions and registrations controllers
``` ruby
class SessionsController < Devise::SessionsController

  def create
    super { |r| @resource = r }
  end
#...
```

``` ruby
class ApplicationController < ActionController::API
  include ActionController::MimeResponds
  respond_to :json
end

```

Request: 
`curl -X POST -H "Accept: application/json, plain/text, */*" -F "user[email]=example@example.com" -F "user[password]=example" http://localhost:3000/sign_in`
raises the error `NameError: undefined local variable or method 'flash'`
And controller processing as `HTML`. But it' API
At the same time, if I change Accept header only for `application/json`
`curl -v -X POST -H "Accept: application/json" -F "user[email]=example@example.com" -F "user[password]=example" localhost:3000/sign_in`
Controller processing as `JSON`. It's work fine.

I know, that i can configure my API client to send only `application/json`, but the problem does not disappear anywhere. 

Maybe I something doing wrong?

Thank you.

**Comment by waiting-for-dev** [comment]
It just seems a problem with your configuration of devise. Have you followed the [guide in the wiki](https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs). Also look at [this issue in devise](https://github.com/plataformatec/devise/issues/4275) (specially [this comment](https://github.com/plataformatec/devise/issues/4275#issuecomment-244968778)) and also [this issue](https://github.com/lynndylanhurley/devise_token_auth/issues/1043).

**Comment by fsdevblog** [comment]
@waiting-for-dev 
did you seen my reproducing the error? https://github.com/fsdevblog/devise_api_err
I wrote there about links which you gave.
And yes, configuration like in guide in the wiki. You can check it yourself.

**Comment by waiting-for-dev** [comment]
My apologies, I looked at the repo but I overlooked the Readme.

`respond_to :json` will take as a json request what you have configured as such in `config/initializers/mime_types.rb`, falling back to the defaults:

```ruby
irb(main):001:0> Mime::Type.lookup_by_extension(:json)
=> #<Mime::Type:0x00000002611bb8 @synonyms=["text/x-json", "application/jsonrequest"], @symbol=:json, @string="application/json", @hash=-650590653070610539>
```

I guess your `*/*` is conflicting with it and making the request default to html. I would stick to the defaults, but otherwise you must configure your mime types accordingly.

**Comment by fsdevblog** [comment]
@waiting-for-dev 
thank you for your response 😄 
> I guess your `*/*` is conflicting with it and making the request default to html.

You are right, thats it. But i really don't understand how to fix it, i mean how to configure mime types accordingly. 
If you have an opportunity, can you help me please? I'am not a specialist.
Or close this issue

Another way which I see, it's configure routes constraints to respond only for `Accept: application/json; version=1`. And this will exclude opportunity to call an application in another format.

**Comment by waiting-for-dev** [comment]
> You are right, thats it. But i really don't understand how to fix it, i mean how to configure mime types accordingly.

Can't you just let `application/json` as your request `Accept` header, without the `*/*` and `plain/text` parts? It really makes no sense having them, because surely your client is expecting and parsing a json response, and not plain text or anything else.

From [w3.org](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1):

> The Accept request-header field can be used to specify certain media types which are acceptable for the response. Accept headers can be used to indicate that the request is specifically limited to a small set of desired types, as in the case of a request for an in-line image.

Anyway, in order to configure mime's just register them in `config/initializers/mime_types.rb`:

```ruby
Mime::Type.register "my/mime", :json
```

But, again, I think you don't need this. Here you have an [article with background about mime's and rails](https://blog.bigbinary.com/2010/11/23/mime-type-resolution-in-rails.html).

Closing this because it's not an issue here, but feel free to add more comments.

**Comment by fsdevblog** [comment]
> Can't you just let `application/json` as your request Accept header, without the `*/*` and plain/text parts?

I'am not talking about API client. I'am talking about any hackers / scanners looking for vulnerabilities. Error `500` it's not very well ) 
But as it were, the problem I solved through the constraints in the routing. Thank you for your time. Good luck :)

**Comment by waiting-for-dev** [comment]
> I'am not talking about API client. I'am talking about any hackers / scanners looking for vulnerabilities. Error 500 it's not very well.

I think error 500 is a quite good response for a hacker :) Otherwise just add responses for html format.

Cheers.

**Comment by torellicode** [comment]
I was running into the same error. Not a professional here, but maybe this helps others. 

My sessions controller was inheriting from Devise::SessionsController and this was the cause of the issue. Simply changing inheritance to ApplicationController resolved my issues while maintaining functionality in my app.
