### ISSUE TITLE
Refresh tokens

### ISSUE THREAD

**Issue by rmammina** [waiting-for-dev/devise-jwt#7]
Enforcing the user to re-login every time the JWT token expires would be annoying on a web experience. I wouldn't want to set a long expiration time on JWT token for security reasons. 

How would you recommend going about this?

**Comment by waiting-for-dev** [comment]
Hey  @rmammina . Set an expiration time acceptable for your desired user experience and use some of the revocation strategies that come out of the box with this gem (usually, I would recommend `JtiMatcher`). This way, once the user signs out the token won't be valid anymore. You can look at the articles linked in the README for a more in-depth reasoning about this.

Cheers

**Comment by BrahimDahmani** [comment]
Hey,

I really appreciate your work and your articles. In fact I have the question that rmammina, ask the user to connect each time the token expires make the user confused.
So what about auto refreshing the token ? is there any security problem with that ? Is it application-specific or can be a feature in `devise-jwt` or `warden-jwt_auth`? 

thx

**Comment by waiting-for-dev** [comment]
Hey @BrahimDahmani . 

Usually, the solution used to have users that never sign out is through refresh tokens. You use a short-lived access token to access your resources, while at the same time the client keeps a long-lived refresh token which purpose is to ask for a new access token once it has expired. This way, the most exposed (logs, cache, man-in-the-middle) token (the access token) has a short live and the less exposed one (the refresh token) lives longer.

But `devise-jwt` is just a simple solution that acts as a replacement for cookies when these can't be used. As cookies, it is mandatory for the token to have an expiration time. I think that trying to implement a refresh tokens feature would be reinventing the wheel. There is already a established standard solution for that: OAuth. Maybe a gem like [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) can be useful for your needs.

**Comment by waiting-for-dev** [comment]
I added a notice in the README to make it clearer ;)

**Comment by sintro** [comment]
@waiting-for-dev But it is fine for different authentication cookie-based solutions to refresh cookies to extend expriation time if user keep requesting server without long idle-times. 
Why one must relogin to website in the middle of using it?

**Comment by waiting-for-dev** [comment]
Hey @sintro . Well, you can still implement this behaviour using `warden-jwt_auth` and `devise-jwt` API. You can request new tokens for other endpoints, or have the client read the `exp` claim and ask for a new token if it is about to expire. But there are other established solutions for a workflow like OAuth2.

**Comment by waiting-for-dev** [comment]
Or, another example, you can configure `devise-jwt` to dispatch and revoke tokens at every authenticated request, this way at each user petition you get a refreshed expiration time.

**Comment by sintro** [comment]
Thank for answer, @waiting-for-dev.
Changing solution to OAuth2, i think, is too complicatated for such a small feature implementation. 
But your advices looks more handy. 
Still, refresh tokens every request for my opinion is overdoing, even while many JWT authorization libraries does this by default. 
Will try to implement your option with `warden-jwt_auth` and `devise-jwt`

**Comment by such** [comment]
@waiting-for-dev I was trying to implement the dispatch and revoke at every authenticated request approach but it's not really working for me. I guess it's because I'm doing multiple requests in parallel and I end up with a request that uses a revoked token. Would you have some kind of advice for cases like these?

**Comment by waiting-for-dev** [comment]
@such I'm afraid there is not simple solution for that... I guess you'd better off with OAuth. Otherwise you should do some manual work, like having the client ask for a new token for every request or something like that...

**Comment by ukazap** [comment]
@such @waiting-for-dev Would it be possible to change tokens at every authenticated request and implement batching of requests within a time buffer [this](https://devise-token-auth.gitbook.io/devise-token-auth/conceptual)?

**Comment by waiting-for-dev** [comment]
Is possible to dispatch tokens at every request and, instead of revoking them, configuring a short enough expiration time so that it can still be used for an immediate second request. However, you can't span the lifetime of the token depending on how incoming requests are coming.

**Comment by davidwparker** [comment]
What I ended up doing is this:

In my allowlist:
```ruby
def self.jwt_revoked?(payload, user)
  # Hook in here to refresh token
  token = user.allowlisted_jwts.where(payload.slice('jti', 'aud')).first
  if token.present? && (SOME LOGIC ABOUT YOUR EXPIRATION HERE)
    token.update_column(:exp, Time.now + SOME TIME)
  end
  token.blank?
end
```

There I would check the expiration. For example, if your token lasts 60 seconds and you want to refresh if at least 30 seconds old. You could write:

```ruby
if token.present? && token.exp < (Time.now+30.seconds)
  token.update_column(:exp, Time.now+60.seconds)
end
```

**Comment by phil-6** [comment]
I came across this thread while facing the same issue. Our approach was to create a new endpoint that lets our mobile app generate a new token before the previous token expires.

The endpoint was simply

``` ruby
  # GET /resource/renew_token
  def renew_token
    token = Warden::JWTAuth::UserEncoder.new.call(current_user, :user, nil)
    render json: { token: }
  end
```

**Comment by yugen** [comment]
[This solution](https://gist.github.com/jwaiswa7/2b58535c33fe15bed3e025708ca1e56c) from @jwaiswa7 seems like a good one to me.  Adds legit refresh tokens with minimal code.
