### ISSUE TITLE
Fail to pass :authenticate_user! after successfully sign in on web app

### ISSUE THREAD

**Issue by vshy108** [waiting-for-dev/devise-jwt#75]
The problem occurred when I use :jwt_authenticatable, jwt_revocation_strategy: self in web application. It has no problems in API part.

I signed in user with sessions#create of devise controller, it redirected to home page after signed in, but it redirect to login page because of the Authorization token is not passed in header for web application page. May I know how to put the token to pass the authorization? Do I need to do something like below (copied from [Changes you need to make in order to make Devise use JWT Header Authentication](https://gist.github.com/goncalvesjoao/5e5131954a12065ac4c601ecf1b827fe))

```erb
<% if user_signed_in? %>
  curl -X GET --header 'Authorization: Bearer <%= JWTWrapper.encode({ user_id: current_user.id }) %>' 'http://localhost:3000/api/v1/yada_yada'
<% end %>
```
in _layouts/application.html.erb_  ? thanks

![image](https://user-images.githubusercontent.com/808926/36781212-355ec0ea-1cb0-11e8-86a2-33f8e6eaddf3.png)
The Authorization header exists in response but after redirect to home page, the authenticate_user! cannot get it?

**Comment by vshy108** [comment]
I think i found the direction is prepare the header before the authenticate_user! action with prepend_before_action, but then I fail to get the token from the request.headers

**Comment by vshy108** [comment]
I found that the response in create session will not be passed to my home page as request header, therefore I cannot obtain the Authorization header from the home page request header...

**Comment by vshy108** [comment]
My session controller 

``` ruby
def create
    user = User.where(email: params[:user][:email]).first
    if user && user.valid_password?(params[:user][:password])
      set_flash_message!(:notice, :signed_in)
      sign_in :user, user, store: true
      yield user if block_given?
      respond_with user, location: after_sign_in_path_for(user)
      # Warden::JWTAuth::UserDecoder.new.call("eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNTE5ODAyNjE5LCJleHAiOjE1Mjg0NDI2MTksImp0aSI6IjQ3NDYyZTQ1LThiZDgtNDQxNi04NTM2LWE0ZmFiZWEyMjZhMCJ9.R0opd3YFvzkvSrZpDeF7zBZs_WUM_KL37XcjBP3xwYo", :user, '')
      # "warden-jwt_auth.token"
    else
      redirect_to :new_user_session
    end
  end
```

My simplest home page
```ruby
class HomesController < ApplicationController
  before_action :authenticate_user!

  def dashboard
  end
end
```

I saw the correct JWT token in the response of session controller with `@"warden-jwt_auth.token"` but then I cannot extract it and store in session to use for home page, still wondering how to make use of JWT authentication in web app....For further info, I am using whitelist strategy..

**Comment by vshy108** [comment]
Try to compare with the working repo https://github.com/talakoski/rails-devise-jwt/commits/master 
Will share the commit if I solve it.

**Comment by waiting-for-dev** [comment]
Hi @vshy108 ,

I don't understand which is your issue. Could you please recap and scope it?

At first sight, what I see is that you are heavily overwritting devise create session action. I see you are not calling [`warden.authenticate!`](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/sessions_controller.rb#L19). Without it the token won't be generated and therefore it won't be added to the response headers.

**Comment by vshy108** [comment]
HI @waiting-for-dev ,

Finally I can pass the devise's :authenticate_user! in those pages need authentication then only can surf.

I found that
1) sign_in :user cannot have store: false for web login.
2) Upgrade ruby and rails version solve problem.

Upgrade
ruby from 2.4.3 to 2.5.0
rails from 5.1.4 to 5.1.5
