### ISSUE TITLE
How to add token to SessionsController#create view

### ISSUE THREAD

**Issue by pedantic-git** [waiting-for-dev/devise-jwt#76]
Hi @waiting-for-dev 

This gem (and the associated warden gem) is amazing! I found all the other solutions to be flawed as they probably didn't care about warden and certainly didn't care about how to handle logout.

However, the frontend library I'm using, [@nuxtjs/auth](https://github.com/nuxt-community/auth-module), requires the JWT to be included in the body of the response to the signin request (there's an [outstanding issue](https://github.com/nuxt-community/auth-module/issues/76) with that library).

Is there an easy way for me to get a JWT for a given user by adding a method to the user model? I think I've got this far:

```ruby
def jwt
  Warden::JWTAuth::UserEncoder.new.call(self, :user, 'aud')&.first
end
```

but obviously 'aud' is the wrong value there so the token generated is invalid.

Any help you can offer would be greatly appreciated!!

**Comment by waiting-for-dev** [comment]
Hi @pedantic-git ,

you can take the already prepared token from the env hash, in `warden-jwt_auth.token` key. Maybe you can set it to an instance var ready for the view from a before action hook.

**Comment by pedantic-git** [comment]
Hi @waiting-for-dev - thanks for your quick response!

I've just tried that but there's nothing in `ENV` (the global environment - is this what you mean?) that looks anything like the token. The token *is* being set in the response headers so I know your gem is running. Is it possible that variable is scoped within warden somehow and inaccessible to views?

**Comment by pedantic-git** [comment]
Woohoo! That's all working! Thanks for your help!

If you'd like to add this to the docs, what I did was:

```ruby
class SessionsController < Devise::SessionsController
  def create
    super { @token = current_token }
  end

  private

  def current_token
    request.env['warden-jwt_auth.token']
  end
end
```

create.json.jbuilder:

```ruby
json.user do
  json.(current_user, :id, :email)
end
json.token @token
```

**Comment by waiting-for-dev** [comment]
Great @pedantic-git , happy to help. Thanks for sharing your solution, it may be helpful for others.

**Comment by benjaminsigidi** [comment]
@pedantic-git `request.env['warden-jwt_auth.token'` returns null. Do you mind explaining how to get the token.

**Comment by pedantic-git** [comment]
@benjaminsigidi Is your user definitely signed in successfully? That should only be `nil` if the user is not signed in.

**Comment by benjaminsigidi** [comment]
@pedantic-git user does successfully sign in. I have asked the question on [stackoverflow](https://stackoverflow.com/questions/51077622/return-jwt-token-when-user-signs-in-rails), but nothing gets returned.

**Comment by pedantic-git** [comment]
@benjaminsigidi I posted a step-by-step guide on Medium if it's any help for you (skip ahead to part 3): https://medium.com/@fishpercolator/how-to-separate-frontend-backend-with-rails-api-nuxt-js-and-devise-jwt-cf7dd9da9d16

**Comment by benjaminsigidi** [comment]
@pedantic-git ohh thanks for the link. I didn't realise you were the author of the post. I did read it. However this is the response. 

> HTTP/1.1 200 OK
> X-Frame-Options: SAMEORIGIN
> X-XSS-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> Content-Type: application/json; charset=utf-8
> ETag: W/"29f14bb580a1dd56271971aebc7bd12e"
> Cache-Control: max-age=0, private, must-revalidate
> Set-Cookie: _poppy_session=b3BySWlmWmNaN2V5Q2d3bXlOY09YQlMycDhUVWV2bG15bS9lVSsrTlNXVm01T3VBeWdLKzRVd0NoVFYwTC9xdmdxZitHZGlXZndOQ2g5amR4d0NweXA4cFRoMU1KY0JTeHpJNzhCN0NmTldBc2tHY25vcXU5ZFV3RDRpT2Z3REZMbzRlbCtCbHp2VjNQbGhhcWdIRW5BPT0tLWNXMWYxZ3hSZHNWYlZUMFFRK1ZFYnc9PQ%3D%3D--94a68a4f4abe1a324eecbca69c5fd7b109184b70; path=/; HttpOnly
> X-Request-Id: bdeac2a5-a19f-476e-afc7-cc231a3429de
> X-Runtime: 0.398445
> Vary: Origin
> Transfer-Encoding: chunked
> 
> {"success":true,"jwt":null,"response":"Authentication successful"}

**Comment by pedantic-git** [comment]
There's no "Authorization" header in that response either, which suggests to me that devise-jwt isn't installed correctly? Have you definitely got `:jwt_authenticatable` on your user object and a jwt.secret in your config file somewhere? When I do POST /users/sign_in on my app, I get back an Authorization header.

**Comment by waiting-for-dev** [comment]
You can get a token for a User using [UserEncoder](https://github.com/waiting-for-dev/warden-jwt_auth/blob/master/lib/warden/jwt_auth/user_encoder.rb) class. Does it help?

**Comment by jorgebasilio** [comment]
Something similar happens to me and I am using the UserEncoder, I show you my code:

```ruby
class Users::OmniauthController < Devise::SessionsController
  PREPARED_TOKEN_ENV_KEY = 'warden-jwt_auth.token'
  def custom
    @user = User.from_omniauth(params[:user])
    if @user.persisted?
      sign_in :user, @user 
      token, payload = Warden::JWTAuth::UserEncoder.new.call(@user, :json, 'JWT_AUD')
      request.env[PREPARED_TOKEN_ENV_KEY] = token
      response.set_header('Authorization', current_token)
      render json: @user
    else
      session["devise.custom_data"] = params[:user]
      render json: @user.errors
    end
  end
  
  private
  
  def current_token
    request.env['warden-jwt_auth.token']
  end
end
```
But what ends up happening is that the generated token is not maintained, this happens, when making a request with this new token it does not recognize to which user it belongs

**Comment by waiting-for-dev** [comment]
> But what ends up happening is that the generated token is not maintained, this happens, when making a request with this new token it does not recognize to which user it belongs

Which error are you getting? Are you sure your scope is `:json` and not `:user`?

**Comment by jorgebasilio** [comment]
indeed, it is a type, the scope is: user.

What happens with this, I generate the token in the Authorization header, but, at the time of making a request to a private endpoint (user profile) I send the Authorization token in the header, but, it returns me that I must log in again, I imagine it happens because Token generated to the user was not registered in any way, can this make sense?

**Comment by waiting-for-dev** [comment]
I assume you are encoding the user through:

```ruby
Warden::JWTAuth::UserEncoder.new.call(@user, :user, 'JWT_AUD')
```

Can you paste here the payload of the generated token (you can get it from here https://jwt.io/#debugger-io) ?

**Comment by jorgebasilio** [comment]
Yes, I have it exactly as you say.

This is what generated the page: [url](https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5Iiwic2NwIjoidXNlciIsImF1ZCI6IkpXVF9BVUQiLCJpYXQiOjE1NjY5MTY3NjQsImV4cCI6MTU2NjkyMDM2NCwianRpIjoiNjIwOWM4MjEtNDkyMC00NTQ0LWFkMWEtMjU5NWEwMjI5NjNhIn0.JXyBIR_LrFP9F2aZdAKjXqmHrFWt_58akf962j9k0o8)

thanks for your attention

**Comment by waiting-for-dev** [comment]
Ok. Please, submit a new issue with all the required debugging information it demands. I'll be able to help you better.

**Comment by omarish** [comment]
I ran into this as well, turns out I didn't have `jwt.dispatch_requests` and `jwt.revocation_requests` in my `config.jwt` block. Adding those fixed it.

`config/initializers/devise.rb`:

```ruby
Devise.setup do |config|
  ...
  config.jwt do |jwt|
    jwt.secret = ENV['DEVISE_JWT_SECRET_KEY']
    jwt.dispatch_requests = [
      ['POST', %r{^/users\/sign_in}]
    ]
    jwt.revocation_requests = [
      ['DELETE', %r{^\/logout}]
    ]
    jwt.expiration_time = 1.day.to_i
  end
end
```
