### ISSUE TITLE
How to remove WhitelistedJwt in Web App?

### ISSUE THREAD

**Issue by vshy108** [waiting-for-dev/devise-jwt#78]
I found that it will always generate jwt token if user successfully sign in with devise. But it will never delete corresponding **WhitelistedJwt** in success sign out. May I know how the web app get the jwt token in devise session destroy action? thanks

**Comment by waiting-for-dev** [comment]
In a sign out, whitelist strategy [will destroy given JWT](https://github.com/waiting-for-dev/devise-jwt/blob/master/lib/devise/jwt/revocation_strategies/whitelist.rb#L34).

> May I know how the web app get the jwt token in devise session destroy action?

Do you mean how the server app (Rails) gets the token? If so, the response is from the request headers, as in any other request.

**Comment by vshy108** [comment]
I checked the session#destroy action in devise will not have Authentication header therefore revoke_jwt method is not triggered and that is why jwt token is not destroy after sign out. May I ask about the jwt token will be used also in those non-api( non-json) action?

**Comment by vshy108** [comment]
Just found that issue #76 "How to add token to SessionsController#create view" gives the way how to get token from the sign in response.. but now missing one part is how the web app know current user using which jwt token in sign out of web app

**Comment by waiting-for-dev** [comment]
> May I ask about the jwt token will be used also in those non-api( non-json) action?

It is up to you to add the token to the request headers or not. But it makes no sense to use `devise-jwt` for non-api requests, where you can rely on standard cookies.

**Comment by vshy108** [comment]
I think I should stop creation WhitistedJwt  after success sign in for non-api instead of passing the Authentication header in sign out request to remove corresponding WhitelistedJwt.

**Comment by waiting-for-dev** [comment]
Check [`request_formats` config option](https://github.com/waiting-for-dev/devise-jwt#request_formats) in order for `devise-jwt` to ignore non-api requests.

> May I know any hints to use jwt token instead of standard cookies for non-api request? Or jwt is not recommended to use in this way?

There are no special hints. Just configure non-api paths to dispatch/revoke tokens and disable your session storage. But it is not recommended. If you can use cookies just use them. They are more battle-tested that tokens, so surely more secure.

**Comment by vshy108** [comment]
Yes, refer to solution issue #69 , 

`jwt.request_formats = { user: [], api_user: [:json] }`

WhitistedJwt is not created in non-api sign in action, thanks.
