### ISSUE TITLE
Add possibility to use RS256 as JWT Verification Strategy

### ISSUE THREAD

**Issue by knightq** [waiting-for-dev/devise-jwt#80]
`Currently, HS256 algorithm is the one in use`

It would be useful to be able to select RS256 or any other asymmetric strategy.

**Comment by waiting-for-dev** [comment]
Can I ask why do you need asymmetric encryption? Aren't the encoder and the decoder the same server?

**Comment by knightq** [comment]
They are, but not only there.

There are other microservices (even from 3rd part vendor) other than the Authentication microservice itself (the service where we use Devise) that need to verify the JWT token and we do not want do share any PSK with them.

Using an asymetric algorithm, and in particular using as public key the same key contained into the SSL certificate of our server, we have a standard (and trusted) way to share the public key even outside our microservice architecture.

**Comment by waiting-for-dev** [comment]
The idea here is that the JWT created by `devise-jwt` is only used for authentication purposes. Doesn't make more sense in your case to use a different JWT for the other information? Also, probably, it would be better to use a JWE. Keep in mind that, at least for now, tokens dispatched by `devise-jwt` are not encrypted, so they are readable by anyone. For this reason they are only meant to store non-private information used to authorize a user. If you add other kind of information probably it is not the best place to store it.

**Comment by waiting-for-dev** [comment]
Hey @knightq , does it make sense? Are you still interested in this issue?

**Comment by waiting-for-dev** [comment]
Closing now but feel free to add more comments if you are still interested in it

**Comment by jkallay1** [comment]
We have a use case where we need to proxy some requests to a second service that will want to validate the auth tokens but not issue them. Asymmetric encryption would be nice so that we don't have to share the signing secret between the two services.

**Comment by waiting-for-dev** [comment]
Hey @jkallay1 . I'm not against supporting it. However, right now I don't have the time nor need to implement it. I can provide support to anybody willing to work on this. It shouldn't be too difficult.

**Comment by b0ric** [comment]
I also find this important and vote it. For example, if we'd like to offload token validation to API Gateway we'd rather use RS256 or other asymmetric option.
