### ISSUE TITLE
authorization token not returned in case of overriding devise route

### ISSUE THREAD

**Issue by sarah-mostafa-m** [waiting-for-dev/devise-jwt#81]
hello,
i receive the authorization token, but when I override devise sign in path the token no more returns in the header, any help?
this is how my route looks like
      devise_for :users, skip: :all
      devise_scope :user do
        post "/users/sign-in" => "sessions#create"   **#works fine if sign_in instead of sign-in**

**Comment by waiting-for-dev** [comment]
If you don't use devise controller it won't work, it is expected behavior. If you are still using devise controller, take a look at [`dispatch_requests`](https://github.com/waiting-for-dev/devise-jwt#dispatch_requests) config option.

**Comment by sarah-mostafa-m** [comment]
i am using devise controller i just override the path
i also configured dispatch requests, still same result

**Comment by waiting-for-dev** [comment]
Have you checked if it is a CORS issue?

If not, which is your output for `Devise::JWT.config`  and `Warden::JWTAuth.config`?

Can you also paste the request information and response headers for the sign in which doesn't return the token?

**Comment by waiting-for-dev** [comment]
Please, if you are still interested in it, fill in the following form and I'll reopen the issue to address it. Thanks.

## Expected behavior

## Actual behavior

## Steps to Reproduce the Problem

1.
2.
3.

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- Version of `devise-jwt` in use
- Version of `rails` in use
- Output of `Devise::JWT.config`
- Output of `Warden::JWTAuth.config`
- Output of `Devise.mappings`
- If your issue is related with not getting a JWT from the server:
  - Involved request path, method and request headers
  - Response headers for that request
- If your issue is related with not being able to revoke a JWT:
  - Involved request path, method and request headers

**Comment by fatalhck** [comment]
> Please, if you are still interested in it, fill in the following bug report and I'll reopen the issue to address it. Thanks.
> 
> ## Expected behavior
Return Authorization token after signup
> ## Actual behavior
Don't return Authorization header on signup response
> ## Steps to Reproduce the Problem
> Extends the devise registration controller, `RegistrationsController < Devise::RegistrationsController`
> Edit routes to a new one in `devise for`
> Try to make a registration request, works fine but no token is returned
> ## Debugging information
> Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.
> 
> * Version of `devise-jwt` in use 0.5.8
> * Version of `rails` in use 5.1.3
> * Output of `Devise::JWT.config` 
```
{:secret=>"32ca22caddb4d61ccf463cbc90c0cd634e83e251a87913bdd8a6b493bc191b4231145b81a132f5a27b77d18b77c18f2d1a8ede5a3e1c664995653744b61583bf",
   :expiration_time=>86400,
   :dispatch_requests=>nil,
   :revocation_requests=>nil,
   :aud_header=>nil,
   :request_formats=>{}}>
``` 
PS **already tried to add dispatch_requests**
> * Output of `Warden::JWTAuth.config`
  {:secret=>"32ca22caddb4d61ccf463cbc90c0cd634e83e251a87913bdd8a6b493bc191b4231145b81a132f5a27b77d18b77c18f2d1a8ede5a3e1c664995653744b61583bf",
   :expiration_time=>86400,
   :aud_header=>"JWT_AUD",
   :mappings=>{:user=>"User"},
   :dispatch_requests=>[["POST", /^\/login$/], ["POST", /^\/signup$/]],
   :revocation_requests=>[["DELETE", /^\/logout$/]],
   :revocation_strategies=>{:user=>"JwtBlacklist"}}>
> * Output of `Devise.mappings`
```
{:user=>
  #<Devise::Mapping:0x00007fae440e7730
   @class_name="User",
   @controllers={:sessions=>"sessions", :registrations=>"registrations", :passwords=>"devise/passwords"},
   @failure_app=Devise::FailureApp,
   @format=nil,
   @klass=#<Devise::Getter:0x00007fae440e6c90 @name="User">,
   @modules=[:database_authenticatable, :recoverable, :registerable, :jwt_authenticatable],
   @path="",
   @path_names={:registration=>"signup", :new=>"new", :edit=>"edit", :sign_in=>"login", :sign_out=>"logout", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel"},
   @path_prefix=nil,
   @router_name=nil,
   @routes=[:session, :password, :registration],
   @scoped_path="users",
   @sign_out_via=:delete,
   @singular=:user,
   @used_helpers=[:session, :password, :registration],
   @used_routes=[:session, :password, :registration]>}
```
> * If your issue is related with not getting a JWT from the server:
>   
>   * Involved request path, method and request headers
```
curl -X POST \
  http://127.0.0.1:3000/signup \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 2a378963-f6a9-ac3b-9982-07036429cc7c' \
  -d '{
	"user": {
		"password":"samplepwd",
        "email": "xpto@domain.com.br",
        "name": "XPTO"
      }
}'
```
>   * Response headers for that request
```
Cache-Control:max-age=0, private, must-revalidate
Content-Type:application/json; charset=utf-8
ETag:W/"de32982ba6c3a71c5e1e3203ce2b720b"
Transfer-Encoding:chunked
Vary:Origin
X-Request-Id:b16e3f38-d02c-4957-b787-7686c519fd06
X-Runtime:346.581951
```

Could you check this?
