### ISSUE TITLE
Add stricter referential integrity to WhitelistedJwt migration

### ISSUE THREAD

**Issue by christophweegen** [waiting-for-dev/devise-jwt#85]
A thing that came to my mind while using whitelisted strategy:

Shouldn't the migration for whitelisted jwts user reference look like this

`t.references :user, foreign_key: { on_delete: :cascade }, null: false`

instead of

`t.references :user, foreign_key: true`

since you never want to store whitelisted jwts for a user that got deleted, so every associated whitelisted jwt get instantly deleted when a user is deleted? 

Additionally you don't want to have whitelisted jwts in your database that don't point to a user. So setting it to `null: false` makes this is a bit stricter. 

I always like to add referential integrity to the database as best as possible, cause it can help prevent bugs when you can trust that only allowed values are saved to the database and you instantly get noticed about it in development if you try to save something invalid. That's not always the case if you just rely on rails validations.

I like this blog post about that topic https://robots.thoughtbot.com/referential-integrity-with-foreign-keys just in case you didn't already read it.

**Comment by waiting-for-dev** [comment]
It makes total sense.

As the migration is just a recommendation in the README (it is not generated by us), we only need to update it. I'll update it or feel free to send a PR.

**Comment by christophweegen** [comment]
If it's ok I would like to make a PR. To be honest i must admit i never did a pull request in my life, since I always worked on my own. Somewhat embarrassing, so this is maybe a good way to get into it. Haha :-D

**Comment by waiting-for-dev** [comment]
Nothing to be embarrassed! Let me know if you need any help :)

**Comment by christophweegen** [comment]
Thanks I will :-)

**Comment by waiting-for-dev** [comment]
Closed by #89
