### ISSUE TITLE
Supporting refreshing jwt tokens on server-side

### ISSUE THREAD

**Issue by dachinat** [waiting-for-dev/devise-jwt#88]
Currently, if you set for example 1 hour for `expiration_time`, after 1 hour jwt token will be revoked even if you have done requests with that jwt token in a time.

Right now I'm handling this situation by sending subsequent renewal requests from frontend SPA.

Is it possible to refresh a token on request, after certain time, until `expiration_time`, or maybe even on every request if configured that way?

Nice gem.
Thanks.

**Comment by waiting-for-dev** [comment]
You can configure as many dispatch requests as you want. A possible use case is to revoke and dispatch tokens at every request, configuring `dispatch_requests` and `revocation_requests` with generic regexp for each request method. This way a token is used for a single request and the expiration time, if high enough, is never reached. Does it help?

**Comment by dachinat** [comment]
Thanks for your response. It helped. Thanks.
