### ISSUE TITLE
Example of How to use this with Rails 5 only API

### ISSUE THREAD

**Issue by henriquesacramento** [waiting-for-dev/devise-jwt#9]
How i can use devise-jwt gem with rails 5 api only?

**Comment by waiting-for-dev** [comment]
You should be fine following the instructions on the Readme. You may encounter issues, but they will be related with devise itself and not with this gem. You can look for some tutorials out there about integrating devise with JSON API. I plan to write my own when I find the time.

**Comment by henriquesacramento** [comment]
Rails 5 API doesn't works with only JSON requests. I Did not found any about that in readme

**Comment by waiting-for-dev** [comment]
Which concrete issue have you found?

**Comment by waiting-for-dev** [comment]
Going to close it now. Feel free to reopen with more information.
