### ISSUE TITLE
Return generated token in sign_in response body

### ISSUE THREAD

**Issue by soulhunter1987** [waiting-for-dev/devise-jwt#91]
Hi.

I created the following custom session controller:
```ruby
module Users
  class SessionsController < Devise::SessionsController
    def create
      self.resource = warden.authenticate!(auth_options)
      sign_in(resource_name, resource)
      render json: { access_token: response.headers['Authorization'] }
    end
  end
end
```
but response.headers['Authorization'] is always nil, even when authentification is successfull. How may I get a value of the generated token from within a controller action?

Thanks.

**Comment by waiting-for-dev** [comment]
Are you sure you need to overwrite your whole action for that? Surely this issue can help you: https://github.com/waiting-for-dev/devise-jwt/issues/76

**Comment by soulhunter1987** [comment]
Thanks a lot! That solved my issue...
