### ISSUE TITLE
Dispatch request for mountable engine route

### ISSUE THREAD

**Issue by dachinat** [waiting-for-dev/devise-jwt#96]
Hello. I'm using a mountable engine, that allows you to execute code on its root route `/` from configuration.

So `mount RailsAdmin::Engine => '/admin', as: 'rails_admin'`, I can execute code when user goes to `/admin` without overriding, just configuring an initializer.

When I configure `devise-jwt` dispatch request with `["GET", %r{^/admin.*$}]` I'm not getting any jwt headers there. But if I configure like `["GET", %r{^.*$}]` then it's there.

So the thing is that for mountable engine `/admin` route, I have to write dispatch request regex like `/`, for `/admin/dashboard` -> `/dashboard`.

Do you think there is a way to write normal regexes and maintain correct behavior?

**Comment by waiting-for-dev** [comment]
Hi @dachinat ,

please fill in the template for bug reports that appears when you open a new issue.

Thanks.
